 /*****************************************
Table  Name:CGOrderSend
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderSend
	/// This entiy code is generated by codesmith. this entity is CGOrderSend.
	/// </summary>
	[Serializable()]
	public class ReportCGOrderEntity
    {
        #region Public Properties	
         
        /// <summary>
        /// 订单编号
        /// <summary>
        private Int64 _B2BCode;
        public Int64 B2BCode
        {
            get
            {
                return _B2BCode;
            }
            set
            {
                _B2BCode = value;
            }
        }
        /// <summary>
        /// 采购订单编号
        /// <summary>
        private Int64 _CGCode;
        public Int64 CGCode
        {
            get
            {
                return _CGCode;
            }
            set
            {
                _CGCode = value;
            }
        }
        
        /// <summary>
        /// 生成时间
        /// <summary>
        private DateTime _CreateTime;
        public DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                _CreateTime = value;
            }
        } 
        /// <summary>
        /// 收货人姓名
        /// <summary>
        private int _CgMemId;
        public int CgMemId
        {
            get
            {
                return _CgMemId;
            }
            set
            {
                _CgMemId = value;
            }
        }
        /// <summary>
        /// 供应商联系人名称
        /// <summary>
        private string _CgMemName;
        public string CgMemName
        {
            get
            {
                return _CgMemName;
            }
            set
            {
                _CgMemName = value;
            }
        }

        /// <summary>
        /// 供应商公司名称
        /// <summary>
        private string _CgCompanyName;
        public string CgCompanyName
        {
            get
            {
                return _CgCompanyName;
            }
            set
            {
                _CgCompanyName = value;
            }
        }
        /// <summary>
        /// 供应商公司名称
        /// <summary>
        private string _CgMemPhone;
        public string CgMemPhone
        {
            get
            {
                return _CgMemPhone;
            }
            set
            {
                _CgMemPhone = value;
            }
        }
        /// <summary>
        /// 产品名称
        /// <summary>
        private string _ProductName;
        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }

 /// <summary>
 /// 
 /// </summary>
        private decimal _CGPrice;
        public decimal CGPrice
        {
            get
            {
                return _CGPrice;
            }
            set
            {
                _CGPrice = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private decimal _B2BPrice;
        public decimal B2BPrice
        {
            get
            {
                return _B2BPrice;
            }
            set
            {
                _B2BPrice = value;
            }
        }

        /// <summary>
        /// 状态：0待报价：1第一轮报价，2第二轮报价，3第三轮报价,4进入线下客服处理流程，11已派单,12供应商已打印发货单，13供应商已发货，14供应商上传客户收货凭证，15送货完成，21财务批准打款，22款已支付，31订单取消，32已退货，99订单关闭
        /// <summary>
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        public string StatusName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((CGOrderStatus)Status);
            }

        }
        /// <summary>
        /// 
        /// <summary>
        private int _Num;
        public int Num
        {
            get
            {
                return _Num;
            }
            set
            {
                _Num = value;
            }
        }
         
        #endregion
    }
}
