 /*****************************************
Table  Name:CGOrderOffer
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderOffer
	/// This entiy code is generated by codesmith. this entity is CGOrderOffer.
	/// </summary>
	[Serializable()]
	public class CGOrderOfferEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 采购单报价记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _CGOrderCode;
	 	public Int64 CGOrderCode
		{
			get
			{
				return _CGOrderCode;
			}
			set
			{
				_CGOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 报价
		/// <summary>
		private  decimal _QuotedPrice;
	 	public decimal QuotedPrice
		{
			get
			{
				return _QuotedPrice;
			}
			set
			{
				_QuotedPrice=value;
			}
		}


        /// <summary>
        /// 报价
        /// <summary>
        private decimal _QuotedTransFee;
        public decimal QuotedTransFee
        {
            get
            {
                return _QuotedTransFee;
            }
            set
            {
                _QuotedTransFee = value;
            }
        }


        /// <summary>
        /// 报价
        /// <summary>
        private decimal _QuotedTotalPrice;
        public decimal QuotedTotalPrice
        {
            get
            {
                return _QuotedTotalPrice;
            }
            set
            {
                _QuotedTotalPrice = value;
            }
        }

        /// <summary>
        /// 报价时间
        /// <summary>
        private  DateTime _QuotedTime;
	 	public DateTime QuotedTime
		{
			get
			{
				return _QuotedTime;
			}
			set
			{
				_QuotedTime=value;
			}
		}
        /// <summary>
        /// 报价时间
        /// <summary>
        private DateTime _CreateTime;
        public DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                _CreateTime = value;
            }
        }
        /// <summary>
        /// 1已接单，2单子被别人抢走了
        /// <summary>
        private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
