 /*****************************************
Table  Name:CGOrderVoucher
Create Time:2017/1/20 23:29:15
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderVoucher
	/// This entiy code is generated by codesmith. this entity is CGOrderVoucher.
	/// </summary>
	[Serializable()]
	public class CGOrderVoucherEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 收货凭证上传表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 采购单编号
		/// <summary>
		private long _CGOrderCode;
	 	public long CGOrderCode
		{
			get
			{
				return _CGOrderCode;
			}
			set
			{
				_CGOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PicSuffix;
	 	public string PicSuffix
		{
			get
			{
				return _PicSuffix;
			}
			set
			{
				_PicSuffix=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
