/*****************************************
Table  Name:CGOrder
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrder
	/// This entiy code is generated by codesmith. this entity is CGOrder.
	/// </summary>
	[Serializable()]
	public class CGOrderEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 采购订单表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 订单编号
		/// <summary>
		private  Int64 _Code;
	 	public Int64 Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}
        private Int32 _CGMemId;
        public Int32 CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }
        /// <summary>
        /// 订单名称
        /// <summary>
        private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 来源订单编号
		/// <summary>
		private  Int64 _SourceCode;
	 	public Int64 SourceCode
		{
			get
			{
				return _SourceCode;
			}
			set
			{
				_SourceCode=value;
			}
		}

	    /// <summary>
		/// 生成时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		} 
	    /// <summary>
		/// 
		/// <summary>
		private  decimal _TransFee;
	 	public decimal TransFee
        {
			get
			{
				return _TransFee;
			}
			set
			{
                _TransFee = value;
			}
		}

	    /// <summary>
		/// 状态：0待报价：1第一轮报价，2第二轮报价，3第三轮报价,4进入线下客服处理流程，11已派单,12供应商已打印发货单，13供应商已发货，14供应商上传客户收货凭证，15送货完成，21财务批准打款，22款已支付，31订单取消，32已退货，99订单关闭
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
        public string StatusName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((CGOrderStatus)Status);
            }

        } 
	    /// <summary>
		/// 发送报价时间
		/// <summary>
		private  DateTime _SendTime;
	 	public DateTime SendTime
		{
			get
			{
				return _SendTime;
			}
			set
			{
				_SendTime=value;
			}
		}
        /// <summary>
        /// 备注
        /// <summary>
        private int _ExpressCom;
        public int ExpressCom
        {
            get
            {
                return _ExpressCom;
            }
            set
            {
                _ExpressCom = value;
            }
        }
        /// <summary>
        /// 备注
        /// <summary>
        private int _OrderStyle;
        public int OrderStyle
        {
            get
            {
                return _OrderStyle;
            }
            set
            {
                _OrderStyle = value;
            }
        }
        /// <summary>
        /// 备注
        /// <summary> 
        public string ExpressComName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((WLComPany)ExpressCom);
            }
        }
        /// <summary>
        /// 备注
        /// <summary>
        private string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

         
     
        #endregion
    }
}
