 /*****************************************
Table  Name:CGOrderTake
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderTake
	/// This entiy code is generated by codesmith. this entity is CGOrderTake.
	/// </summary>
	[Serializable()]
	public class CGOrderTakeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 供应商接单信息表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 采购单编号
		/// <summary>
		private  Int64 _CGOrderCode;
	 	public Int64 CGOrderCode
		{
			get
			{
				return _CGOrderCode;
			}
			set
			{
				_CGOrderCode=value;
			}
		}

	    /// <summary>
		/// 供应商Id
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
        } 
        /// <summary>
        /// 供应商 
        /// <summary>
        private string _CGMemName;
        public string CGMemName
        {
            get
            {
                return _CGMemName;
            }
            set
            {
                _CGMemName = value;
            }
        }

        /// <summary>
        /// 接单时间
        /// <summary>
        private  DateTime _TakeTime;
	 	public DateTime TakeTime
		{
			get
			{
				return _TakeTime;
			}
			set
			{
				_TakeTime=value;
			}
		}

	    /// <summary>
		/// 接单价格
		/// <summary>
		private  decimal _TakePrice;
	 	public decimal TakePrice
		{
			get
			{
				return _TakePrice;
			}
			set
			{
				_TakePrice=value;
			}
		}
        /// <summary>
        /// 接单价格
        /// <summary>
        private decimal _TransFee;
        public decimal TransFee
        {
            get
            {
                return _TransFee;
            }
            set
            {
                _TransFee = value;
            }
        }
        private decimal _TotalPrice;
        public decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                _TotalPrice = value;
            }
        }
        /// <summary>
        /// 打印送货单时间
        /// <summary>
        private  DateTime _PrintNoteTime;
	 	public DateTime PrintNoteTime
		{
			get
			{
				return _PrintNoteTime;
			}
			set
			{
				_PrintNoteTime=value;
			}
		}

	    /// <summary>
		/// 发货时间
		/// <summary>
		private  DateTime _DeliveryTime;
	 	public DateTime DeliveryTime
		{
			get
			{
				return _DeliveryTime;
			}
			set
			{
				_DeliveryTime=value;
			}
		}

	    /// <summary>
		/// 上传收货凭证时间
		/// <summary>
		private  DateTime _VoucherTime;
	 	public DateTime VoucherTime
		{
			get
			{
				return _VoucherTime;
			}
			set
			{
				_VoucherTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _VoucherUrl;
	 	public string VoucherUrl
		{
			get
			{
				return _VoucherUrl;
			}
			set
			{
				_VoucherUrl=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private string _Remark;
        public string Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                _Remark = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  DateTime _PayTime;
	 	public DateTime PayTime
		{
			get
			{
				return _PayTime;
			}
			set
			{
				_PayTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _PayMemId;
	 	public int PayMemId
		{
			get
			{
				return _PayMemId;
			}
			set
			{
				_PayMemId=value;
			}
		}

        /// <summary>
        /// 
        /// <summary>
        private string _DeliveryManName;
        public string DeliveryManName
        {
            get
            {
                return _DeliveryManName;
            }
            set
            {
                _DeliveryManName = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private string _DeliveryManPhone;
        public string DeliveryManPhone
        {
            get
            {
                return _DeliveryManPhone;
            }
            set
            {
                _DeliveryManPhone = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private string _WLComName;
        public string WLComName
        {
            get
            {
                return _WLComName;
            }
            set
            {
                _WLComName = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private string _WLCode;
        public string WLCode
        {
            get
            {
                return _WLCode;
            }
            set
            {
                _WLCode = value;
            }
        }
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        private string _StatusName;
        public string StatusName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((CGOrderTake)Status);
            }
             
        }
        

        private int _ProductId;
        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }

        private ProductEntity _ProductItem;
        public ProductEntity ProductItem
        {
            get
            {
                return _ProductItem;
            }
            set
            {
                _ProductItem = value;
            }
        }

        #endregion
    }
}
