 /*****************************************
Table  Name:CGOrderOfferSub
Create Time:2017/2/5 18:00:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderOfferSub
	/// This entiy code is generated by codesmith. this entity is CGOrderOfferSub.
	/// </summary>
	[Serializable()]
	public class CGOrderOfferSubEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _OfferId;
	 	public int OfferId
		{
			get
			{
				return _OfferId;
			}
			set
			{
				_OfferId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _CGOrderCode;
	 	public Int64 CGOrderCode
		{
			get
			{
				return _CGOrderCode;
			}
			set
			{
				_CGOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _CGPrice;
	 	public decimal CGPrice
		{
			get
			{
				return _CGPrice;
			}
			set
			{
				_CGPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _CGTotalPrice;
	 	public decimal CGTotalPrice
		{
			get
			{
				return _CGTotalPrice;
			}
			set
			{
				_CGTotalPrice=value;
			}
		}

		#endregion				
	}
}
