 /*****************************************
Table  Name:ProductSpecialDetails
Create Time:2017/5/16 11:30:33
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductSpecialDetails
	/// This entiy code is generated by codesmith. this entity is ProductSpecialDetails.
	/// </summary>
	[Serializable()]
	public class VWProductSpecialDetailsEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _SpecialId;
	 	public int SpecialId
		{
			get
			{
				return _SpecialId;
			}
			set
			{
				_SpecialId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}
        private decimal _Price;
        public decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                _Price = value;
            }
        }
        public VWProductEntity ProductDetail;
        #endregion
    }
}
