 /*****************************************
Table  Name:ProductBaoPin
Create Time:2017/4/15 15:37:40
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductBaoPin
	/// This entiy code is generated by codesmith. this entity is ProductBaoPin.
	/// </summary>
	[Serializable()]
	public class VWProductSimilarHotEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 爆品记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品价格明细表Id
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

        public VWProductEntity ProductDetail;
       
        /// <summary>
        /// 
        /// <summary>
        private int _Sort;
        public int Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                _Sort = value;
            }
        }

        /// <summary>
        /// 类别Id
        /// <summary>
        private int _ClassId;
        public int ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                _ClassId = value;
            }
        }

        /// <summary>
        /// 款式Id
        /// <summary>
        private int _ProductId;
        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }

        /// <summary>
        /// 销量
        /// <summary>
        private int _SalesNum;
        public int SalesNum
        {
            get
            {
                return _SalesNum;
            }
            set
            {
                _SalesNum = value;
            }
        }

        #endregion
    }
}
