 /*****************************************
Table  Name:产品规格属性
Create Time:2017/3/15 0:42:16
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductExt
	/// This entiy code is generated by codesmith. this entity is ProductExt.
	/// </summary>
	[Serializable()]
	public class VWProductNomalParamEntity
    {
	    #region Public Properties	
	   
	    /// <summary>
		/// 产品id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 详情说明
		/// <summary>
		private  string _DetailDescrip;
	 	public string DetailDescrip
		{
			get
			{
				return _DetailDescrip;
			}
			set
			{
				_DetailDescrip=value;
			}
		}

	    /// <summary>
		/// 规格型号
		/// <summary>
		private  string _SpecModel;
	 	public string SpecModel
		{
			get
			{
				return _SpecModel;
			}
			set
			{
				_SpecModel=value;
			}
		}

	    /// <summary>
		/// 包装规格
		/// <summary>
		private  string _SpecPacking;
	 	public string SpecPacking
		{
			get
			{
				return _SpecPacking;
			}
			set
			{
				_SpecPacking=value;
			}
		}

	    /// <summary>
		/// 适配车型
		/// <summary>
		private  string _APPModels;
	 	public string APPModels
		{
			get
			{
				return _APPModels;
			}
			set
			{
				_APPModels=value;
			}
		}

	    /// <summary>
		/// OEM编号
		/// <summary>
		private  string _OEMPartNos;
	 	public string OEMPartNos
		{
			get
			{
				return _OEMPartNos;
			}
			set
			{
				_OEMPartNos=value;
			}
		}
        private int _BrandId;
        public int BrandId
        {
            get
            {
                return _BrandId;
            }
            set
            {
                _BrandId = value;
            }
        }

        /// <summary>
        /// 品牌名称
        /// </summary>
        private string _BrandName;
        public string BrandName
        {
            get
            {
                return _BrandName;
            }
            set
            {
                _BrandName = value;
            }
        }
        /// <summary>
        /// 生产厂家
        /// </summary>
        private string _Factory;
        public string Factory
        {
            get
            {
                return _Factory;
            }
            set
            {
                _Factory = value;
            }
        }
        /// <summary>
        /// 产品名称
        /// </summary>
        private string _ProductName;
        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }
        /// <summary>
        /// 生产零件号
        /// </summary>
        private string _FacCode;
        public string FacCode
        {
            get
            {
                return _FacCode;
            }
            set
            {
                _FacCode = value;
            }
        }
        private int _UnitId;
        public int  UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                _UnitId = value;
            }
        }
        /// <summary>
        /// 计量单位
        /// </summary>
        private string _UnitName;
        public string UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                _UnitName = value;
            }
        }
        private int _ClassId;
        public int ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                _ClassId = value;
            }
        }
        private string _ClassName;
        public string ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                _ClassName = value;
            }
        }
        #endregion
    }
}
