 /*****************************************
Table  Name:B2BNotice
Create Time:2016/12/19 18:15:10
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>B2BNotice
	/// This entiy code is generated by codesmith. this entity is B2BNotice.
	/// </summary>
	[Serializable()]
	public class B2BNoticeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// B2B平台公众通知
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 通知标题
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 通知内容
		/// <summary>
		private  string _NoticeContent;
	 	public string NoticeContent
		{
			get
			{
				return _NoticeContent;
			}
			set
			{
				_NoticeContent=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 上架时间
		/// <summary>
		private  DateTime _ShowTime;
	 	public DateTime ShowTime
		{
			get
			{
				return _ShowTime;
			}
			set
			{
				_ShowTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}
        /// <summary>
        /// 是否热门
        /// <summary>
        private int _IsHot;
        public int IsHot
        {
            get
            {
                return _IsHot;
            }
            set
            {
                _IsHot = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private int _SystemType;
        public int SystemType
        {
            get
            {
                return _SystemType;
            }
            set
            {
                _SystemType = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private int _NoticeType;
        public int NoticeType
        {
            get
            {
                return _NoticeType;
            }
            set
            {
                _NoticeType = value;
            }
        }
        #endregion
    }
}
