 /*****************************************
Table  Name:EmailSend
Create Time:2017/2/21 22:37:02
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>EmailSend
	/// This entiy code is generated by codesmith. this entity is EmailSend.
	/// </summary>
	[Serializable()]
	public class EmailSendEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 邮件内容记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// Email地址
		/// <summary>
		private  string _Email;
	 	public string Email
		{
			get
			{
				return _Email;
			}
			set
			{
				_Email=value;
			}
		}

	    /// <summary>
		/// 标题
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 内容
		/// <summary>
		private  string _Body;
	 	public string Body
		{
			get
			{
				return _Body;
			}
			set
			{
				_Body=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 发送时间
		/// <summary>
		private  DateTime _SendTime;
	 	public DateTime SendTime
		{
			get
			{
				return _SendTime;
			}
			set
			{
				_SendTime=value;
			}
		}

	    /// <summary>
		/// 状态
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
