  
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary> 
	/// This entiy code is generated by codesmith. this entity is  .
	/// </summary>
	[Serializable()]
	public class MemProductClickEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 用户点击量表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品明细Id
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 点击时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 点击量
		/// <summary>
		private  int _ClickNum;
	 	public int ClickNum
		{
			get
			{
				return _ClickNum;
			}
			set
			{
				_ClickNum=value;
			}
		}

	    /// <summary>
		/// 系统类别，B2B，。。。商用车，
		/// <summary>
		private  int _SystemId;
	 	public int SystemId
		{
			get
			{
				return _SystemId;
			}
			set
			{
				_SystemId=value;
			}
		}
        /// <summary>
        /// 产品明细Id
        /// <summary>
        private string _ClickIp;
        public string ClickIp
        {
            get
            {
                return _ClickIp;
            }
            set
            {
                _ClickIp = value;
            }
        }
        #endregion
    }
}
