 /*****************************************
Table  Name:MobileMessage
Create Time:2016/11/15 15:31:14
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MobileMessage
	/// This entiy code is generated by codesmith. this entity is MobileMessage.
	/// </summary>
	[Serializable()]
	public class MobileMessageEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _MobilePhone;
	 	public string MobilePhone
		{
			get
			{
				return _MobilePhone;
			}
			set
			{
				_MobilePhone=value;
			}
		}

        /// <summary>
        /// 
        /// <summary>
        private string _SendProvider;
        public string SendProvider
        {
            get
            {
                return _SendProvider;
            }
            set
            {
                _SendProvider = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private string _MessageContent;
	 	public string MessageContent
		{
			get
			{
				return _MessageContent;
			}
			set
			{
				_MessageContent=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _IpAddress;
	 	public string IpAddress
		{
			get
			{
				return _IpAddress;
			}
			set
			{
				_IpAddress=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private string _ResultSMS;
        public string ResultSMS
        {
            get
            {
                return _ResultSMS;
            }
            set
            {
                _ResultSMS = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private  Int64 _IpInt;
	 	public Int64 IpInt
		{
			get
			{
				return _IpInt;
			}
			set
			{
				_IpInt=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
