 /*****************************************
Table  Name:SMSTemplet
Create Time:2017/2/2 9:46:29
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SMSTemplet
	/// This entiy code is generated by codesmith. this entity is SMSTemplet.
	/// </summary>
	[Serializable()]
	public class SMSTempletEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 短信模板表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 编码
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 短信内容
		/// <summary>
		private  string _SMSTContent;
	 	public string SMSTContent
		{
			get
			{
				return _SMSTContent;
			}
			set
			{
				_SMSTContent=value;
			}
		}

		#endregion				
	}
}
