 /*****************************************
Table  Name:SuggestRecord
Create Time:2017/5/9 11:53:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SuggestRecord
	/// This entiy code is generated by codesmith. this entity is SuggestRecord.
	/// </summary>
	[Serializable()]
	public class SuggestRecordEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 客户建议记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 产品数量建议
		/// <summary>
		private  string _ProductNum;
	 	public string ProductNum
		{
			get
			{
				return _ProductNum;
			}
			set
			{
				_ProductNum=value;
			}
		}

	    /// <summary>
		/// 产品售价建议
		/// <summary>
		private  string _ProductPrice;
	 	public string ProductPrice
		{
			get
			{
				return _ProductPrice;
			}
			set
			{
				_ProductPrice=value;
			}
		}

	    /// <summary>
		/// 客户服务建议
		/// <summary>
		private  string _KFService;
	 	public string KFService
		{
			get
			{
				return _KFService;
			}
			set
			{
				_KFService=value;
			}
		}

	    /// <summary>
		/// 物流服务建议
		/// <summary>
		private  string _WLService;
	 	public string WLService
		{
			get
			{
				return _WLService;
			}
			set
			{
				_WLService=value;
			}
		}

	    /// <summary>
		/// 具体建议说明
		/// <summary>
		private  string _SuggestDetail;
	 	public string SuggestDetail
		{
			get
			{
				return _SuggestDetail;
			}
			set
			{
				_SuggestDetail=value;
			}
		}

	    /// <summary>
		/// 是否审核
		/// <summary>
		private  int _HasCheck;
	 	public int HasCheck
		{
			get
			{
				return _HasCheck;
			}
			set
			{
				_HasCheck=value;
			}
		}

	    /// <summary>
		/// 是否采纳
		/// <summary>
		private  int _HasRecived;
	 	public int HasRecived
		{
			get
			{
				return _HasRecived;
			}
			set
			{
				_HasRecived=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 审核时间
		/// <summary>
		private  DateTime _CheckTime;
	 	public DateTime CheckTime
		{
			get
			{
				return _CheckTime;
			}
			set
			{
				_CheckTime=value;
			}
		}

		#endregion				
	}
}
