 /*****************************************
Table  Name:WeChatMsg
Create Time:2017/8/26 16:39:01
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WeChatMsg
	/// This entiy code is generated by codesmith. this entity is WeChatMsg.
	/// </summary>
	[Serializable()]
	public class WeChatMsgEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _WeChatOpenId;
	 	public string WeChatOpenId
		{
			get
			{
				return _WeChatOpenId;
			}
			set
			{
				_WeChatOpenId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _TemplateIid;
	 	public string TemplateIid
		{
			get
			{
				return _TemplateIid;
			}
			set
			{
				_TemplateIid=value;
			}
		}
        
        /// <summary>
        /// 
        /// <summary>
        private string _RedirectUrl;
        public string RedirectUrl
        {
            get
            {
                return _RedirectUrl;
            }
            set
            {
                _RedirectUrl = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  string _WeChatUrl;
	 	public string WeChatUrl
		{
			get
			{
				return _WeChatUrl;
			}
			set
			{
				_WeChatUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ParamStr;
	 	public string ParamStr
		{
			get
			{
				return _ParamStr;
			}
			set
			{
				_ParamStr=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Result;
	 	public string Result
		{
			get
			{
				return _Result;
			}
			set
			{
				_Result=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

		#endregion				
	}
}
