 /*****************************************
Table  Name:CmsContent
Create Time:2016/10/31 13:28:24
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CmsContent
	/// This entiy code is generated by codesmith. this entity is CmsContent.
	/// </summary>
	[Serializable()]
	public class CmsContentEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// Cms内容表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 标题说明
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 模板Id
		/// <summary>
		private  int _CmsTempletId;
	 	public int CmsTempletId
		{
			get
			{
				return _CmsTempletId;
			}
			set
			{
				_CmsTempletId=value;
			}
		}

	    /// <summary>
		/// 内容类别
		/// <summary>
		private  int _CMSType;
	 	public int CMSType
		{
			get
			{
				return _CMSType;
			}
			set
			{
				_CMSType=value;
			}
		}

	    /// <summary>
		/// 内容
		/// <summary>
		private  string _CmsContent;
	 	public string CmsContent
		{
			get
			{
				return _CmsContent;
			}
			set
			{
				_CmsContent=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
