 /*****************************************
Table  Name:CmsTemplet
Create Time:2016/10/31 13:28:24
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CmsTemplet
	/// This entiy code is generated by codesmith. this entity is CmsTemplet.
	/// </summary>
	[Serializable()]
	public class CmsTempletEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// CMS生成模板
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 标题
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 模板名
		/// <summary>
		private  string _TempletContent;
	 	public string TempletContent
		{
			get
			{
				return _TempletContent;
			}
			set
			{
				_TempletContent=value;
			}
		}

	    /// <summary>
		/// 产品数量，模板需要包含的产品数量
		/// <summary>
		private  int _ProductNum;
	 	public int ProductNum
		{
			get
			{
				return _ProductNum;
			}
			set
			{
				_ProductNum=value;
			}
		}

	    /// <summary>
		/// 模板类型：1首页导航，2左侧导航，3首页中部广告等
		/// <summary>
		private  int _CMSType;
	 	public int CMSType
		{
			get
			{
				return _CMSType;
			}
			set
			{
				_CMSType=value;
			}
		}

	    /// <summary>
		/// 制定日期
		/// <summary>
		private  DateTime _CreateDate;
	 	public DateTime CreateDate
		{
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

		#endregion				
	}
}
