 /*****************************************
Table  Name:ClassProDetails
Create Time:2016/10/31 13:00:03
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ClassProDetails
	/// This entiy code is generated by codesmith. this entity is ClassProDetails.
	/// </summary>
	[Serializable()]
	public class BasicSiteProDetailsEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 属性内容表:只能新增,不能删除
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 属性内容名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

	    /// <summary>
		/// 属性Id
		/// <summary>
		private  int _PropertyId;
	 	public int PropertyId
		{
			get
			{
				return _PropertyId;
			}
			set
			{
				_PropertyId=value;
			}
		}

	    /// <summary>
		/// 状态，1有效，2待审核，3拒绝，0失效
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

	    /// <summary>
		/// 属性内容的父级Id
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _Active;
	 	public int Active
		{
			get
			{
				return _Active;
			}
			set
			{
				_Active=value;
			}
		}

	    /// <summary>
		/// 排序 降序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
