/*****************************************
Table  Name:BasicSiteProperties
Create Time:2016/10/31 13:00:04
Creator    :jc001
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>BasicSiteProperties
	/// This entiy code is generated by codesmith. this entity is BasicSiteProperties.
	/// </summary>
	[Serializable()]
	public class BasicSitePropertiesEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 属性编码
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 属性名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 基础分类3级Id
		/// <summary>
		private  int _SiteId;
	 	public int SiteId
		{
			get
			{
				return _SiteId;
			}
			set
			{
                _SiteId = value;
			}
		}

	    /// <summary>
		/// 上级Id
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
                _ParentId = value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 是否排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 属性根节点，没有层级关系的以自身代替
		/// <summary>
		private  int _RootPropertyId;
	 	public int RootPropertyId
		{
			get
			{
				return _RootPropertyId;
			}
			set
			{
				_RootPropertyId=value;
			}
		}

	    /// <summary>
		/// 属性规格种类（1默认规格，选择项，可输入，2 输入项，3只能选择项，
		/// <summary>
		private  int _CanInput;
	 	public int CanInput
		{
			get
			{
				return _CanInput;
			}
			set
			{
				_CanInput=value;
			}
		}

	    /// <summary>
		/// 是否是规格
		/// <summary>
		private  int _IsSpec;
	 	public int IsSpec
		{
			get
			{
				return _IsSpec;
			}
			set
			{
				_IsSpec=value;
			}
		}
        public IList<BasicSiteProDetailsEntity> ProDetails;

        /// <summary>
        /// 通用属性的Id,0:代表不适用通用属性
        /// <summary>
        private int _ComPropertyId;
	 	public int ComPropertyId
		{
			get
			{
				return _ComPropertyId;
			}
			set
			{
				_ComPropertyId=value;
			}
		}
		#endregion				
	}
}
