 /*****************************************
Table  Name:Brand
Create Time:2016/10/31 13:00:02
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Brand
	/// This entiy code is generated by codesmith. this entity is Brand.
	/// </summary>
	[Serializable()]
	public class BrandEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 汽车品牌表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 编号，按照编号规则自定义
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 品牌名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 显示的标题：选择品牌，选择车系，选择年份等
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 缩写
		/// <summary>
		private  string _PYShort;
	 	public string PYShort
		{
			get
			{
				return _PYShort;
			}
			set
			{
				_PYShort=value;
			}
		}

	    /// <summary>
		/// 全拼
		/// <summary>
		private  string _PYFull;
	 	public string PYFull
		{
			get
			{
				return _PYFull;
			}
			set
			{
				_PYFull=value;
			}
		}

	    /// <summary>
		/// 是否排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 是否热门品牌
		/// <summary>
		private  int _IsHot;
	 	public int IsHot
		{
			get
			{
				return _IsHot;
			}
			set
			{
				_IsHot=value;
			}
		}

	    /// <summary>
		/// 上级Id
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}


        /// <summary>
        /// 生产商
        /// <summary>
        private string _Manufacturer;
        public string Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                _Manufacturer = value;
            }
        }
        /// <summary>
        /// 生产商
        /// <summary>
        private string _PicUrl;
        public string PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                _PicUrl = value;
            }
        }

        
        #endregion
    }
}
