 /*****************************************
Table  Name:CarType
Create Time:2016/10/31 13:00:03
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CarType
	/// This entiy code is generated by codesmith. this entity is CarType.
	/// </summary>
	[Serializable()]
	public class CarTypeEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 车子品牌记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 编码
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}
        /// <summary>
		/// 图片路径
		/// <summary>
		private string _PicUrl;
        public string PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                _PicUrl = value;
            }
        }
        /// <summary>
        /// 图片路径
        /// <summary>
        private string _FirstPY;
        public string FirstPY
        {
            get
            {
                return _FirstPY;
            }
            set
            {
                _FirstPY = value;
            }
        }
        /// <summary>
        /// 年份
        /// <summary>
        private  string _Year;
	 	public string Year
		{
			get
			{
				return _Year;
			}
			set
			{
				_Year=value;
			}
		}

	    /// <summary>
		/// 上级ID
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}
        private int _CarTypeClassId;
        public int CarTypeClassId
        {
            get
            {
                return _CarTypeClassId;
            }
            set
            {
                _CarTypeClassId = value;
            }
        }
        private int _RedirectCarTypeId;
        public int RedirectCarTypeId
        {
            get
            {
                return _RedirectCarTypeId;
            }
            set
            {
                _RedirectCarTypeId = value;
            }
        }

        private int _IsStandard;
        public int IsStandard
        {
            get
            {
                return _IsStandard;
            }
            set
            {
                _IsStandard = value;
            }
        }
        private int _ClassType;
        public int ClassType
        {
            get
            {
                return _ClassType;
            }
            set
            {
                _ClassType = value;
            }
        }
        /// <summary>
        /// 层级关系
        /// <summary>
        private  int _CarTypeLevel;
	 	public int CarTypeLevel
		{
			get
			{
				return _CarTypeLevel;
			}
			set
			{
				_CarTypeLevel=value;
			}
		}

	    /// <summary>
		/// 排序降序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}
        /// <summary>
        /// 是否热门品牌
        /// <summary>
        private int _IsHot;
        public int IsHot
        {
            get
            {
                return _IsHot;
            }
            set
            {
                _IsHot = value;
            }
        }
        

        #endregion
    }
}
