 /*****************************************
Table  Name:CarTypeBrand
Create Time:2017/4/21 11:46:53
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CarTypeBrand
	/// This entiy code is generated by codesmith. this entity is CarTypeBrand.
	/// </summary>
	[Serializable()]
	public class CarTypeBrandEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _BrandName;
	 	public string BrandName
		{
			get
			{
				return _BrandName;
			}
			set
			{
				_BrandName=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PYFirst;
	 	public string PYFirst
		{
			get
			{
				return _PYFirst;
			}
			set
			{
				_PYFirst=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}
        private int _IsHot;
        public int IsHot
        {
            get
            {
                return _IsHot;
            }
            set
            {
                _IsHot = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private  string _ParentCode;
	 	public string ParentCode
		{
			get
			{
				return _ParentCode;
			}
			set
			{
				_ParentCode=value;
			}
		}

	    /// <summary>
		/// 父级品牌 
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}

	    /// <summary>
		/// 是否标准品牌：大品牌1级品牌为标准品牌
		/// <summary>
		private  int _IsStandardBrand;
	 	public int IsStandardBrand
		{
			get
			{
				return _IsStandardBrand;
			}
			set
			{
				_IsStandardBrand=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
