 /*****************************************
Table  Name:CarTypeSeries
Create Time:2017/4/21 11:46:53
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CarTypeSeries
	/// This entiy code is generated by codesmith. this entity is CarTypeSeries.
	/// </summary>
	[Serializable()]
	public class CarTypeSeriesEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 车系记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 全称
		/// <summary>
		private  string _FullName;
	 	public string FullName
		{
			get
			{
				return _FullName;
			}
			set
			{
				_FullName=value;
			}
		}

	    /// <summary>
		/// 简称
		/// <summary>
		private  string _ShortName;
	 	public string ShortName
		{
			get
			{
				return _ShortName;
			}
			set
			{
				_ShortName=value;
			}
		}

	    /// <summary>
		/// 大品牌Id
		/// <summary>
		private  int _StandardBrandId;
	 	public int StandardBrandId
		{
			get
			{
				return _StandardBrandId;
			}
			set
			{
				_StandardBrandId=value;
			}
		}

	    /// <summary>
		/// 上级子品牌Id
		/// <summary>
		private  int _ParentBrandId;
	 	public int ParentBrandId
		{
			get
			{
				return _ParentBrandId;
			}
			set
			{
				_ParentBrandId=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 有效性
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

		#endregion				
	}
}
