 /*****************************************
Table  Name:ClassesMenuAD
Create Time:2017/6/15 15:25:36
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ClassesMenuAD
	/// This entiy code is generated by codesmith. this entity is ClassesMenuAD.
	/// </summary>
	[Serializable()]
	public class ClassesMenuADEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 首页菜单展示位绑定品牌产品广告位记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 类别Id
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}

	    /// <summary>
		/// 相关品牌展示或产品展示的Id，ShowType确定是品牌还是产品
		/// <summary>
		private  int _BrandOrProductId;
	 	public int BrandOrProductId
		{
			get
			{
				return _BrandOrProductId;
			}
			set
			{
				_BrandOrProductId=value;
			}
		}

	    /// <summary>
		/// 排序，降序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 1品牌，2产品
		/// <summary>
		private  int _ShowType;
	 	public int ShowType
		{
			get
			{
				return _ShowType;
			}
			set
			{
				_ShowType=value;
			}
		}

	    /// <summary>
		/// 开始广告时间
		/// <summary>
		private  DateTime _BeginTime;
	 	public DateTime BeginTime
		{
			get
			{
				return _BeginTime;
			}
			set
			{
				_BeginTime=value;
			}
		}

	    /// <summary>
		/// 结束广告时间
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

		#endregion				
	}
}
