 /*****************************************
Table  Name:ClassesFound
Create Time:2016/10/31 13:00:03
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ClassesFound
	/// This entiy code is generated by codesmith. this entity is ClassesFound.
	/// </summary>
	[Serializable()]
	public class ClassesFoundEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 编号
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}
        /// <summary>
        /// 名称
        /// <summary>
        private string _FullName;
        public string FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                _FullName = value;
            }
        }
        /// <summary>
        /// 缩写
        /// <summary>
        private  string _PYFirst;
	 	public string PYFirst
		{
			get
			{
				return _PYFirst;
			}
			set
			{
				_PYFirst=value;
			}
		}

	    /// <summary>
		/// 缩写
		/// <summary>
		private  string _PYShort;
	 	public string PYShort
		{
			get
			{
				return _PYShort;
			}
			set
			{
				_PYShort=value;
			}
		}

	    /// <summary>
		/// 全拼
		/// <summary>
		private  string _PYFull;
	 	public string PYFull
		{
			get
			{
				return _PYFull;
			}
			set
			{
				_PYFull=value;
			}
		}

	    /// <summary>
		/// 广告ID
		/// <summary>
		private  int _AdId;
	 	public int AdId
		{
			get
			{
				return _AdId;
			}
			set
			{
				_AdId=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 是否热门
		/// <summary>
		private  int _IsHot;
	 	public int IsHot
		{
			get
			{
				return _IsHot;
			}
			set
			{
				_IsHot=value;
			}
		}

	    /// <summary>
		/// 创建时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 修改时间
		/// <summary>
		private  DateTime _UpdateTime;
	 	public DateTime UpdateTime
		{
			get
			{
				return _UpdateTime;
			}
			set
			{
				_UpdateTime=value;
			}
		}

	    /// <summary>
		/// 分类级别
		/// <summary>
		private  int _ClassLevel;
	 	public int ClassLevel
		{
			get
			{
				return _ClassLevel;
			}
			set
			{
				_ClassLevel=value;
			}
		}

	    /// <summary>
		/// 是否叶子分类
		/// <summary>
		private  int _IsEnd;
	 	public int IsEnd
		{
			get
			{
				return _IsEnd;
			}
			set
			{
				_IsEnd=value;
			}
		}

	    /// <summary>
		/// 根据分类是否能确定产品属性0不能1根据此分类,不管上级分类能否确定，2根据上级分类确定
		/// <summary>
		private  int _HasProperties;
	 	public int HasProperties
		{
			get
			{
				return _HasProperties;
			}
			set
			{
				_HasProperties=value;
			}
		}
 
	    /// <summary>
		/// 上级ID
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}
        /// <summary>
        /// 是否可对该分类添加产品1是0否
        /// <summary>
        private int _HasProduct;
        public int HasProduct
        {
            get
            {
                return _HasProduct;
            }
            set
            {
                _HasProduct = value;
            }
        }
        /// <summary>
        /// 是否可对该分类添加产品1是0否
        /// <summary>
        private int _ListShowMethod;
        public int ListShowMethod
        {
            get
            {
                return _ListShowMethod;
            }
            set
            {
                _ListShowMethod = value;
            }
        }
        /// <summary>
        /// 关联的属性所属分类
        /// <summary>
        private int _PropertiesClassId;
        public int PropertiesClassId
        {
            get
            {
                return _PropertiesClassId;
            }
            set
            {
                _PropertiesClassId = value;
            }
        }
        /// <summary>
        /// 产品种类数量
        /// <summary>
        private int _ClassType;
        public int ClassType
        {
            get
            {
                return _ClassType;
            }
            set
            {
                _ClassType = value;
            }
        }
        public string ClassTypeName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((CarTypeMenus)ClassType); 
            }
        }
        /// <summary>
        /// 虚拟分类导向的分类 
        /// <summary>
        private int _RedirectClassId;
        public int RedirectClassId
        {
            get
            {
                return _RedirectClassId;
            }
            set
            {
                _RedirectClassId = value;
            }
        }

        /// <summary>
        /// 分类所属类别
        /// <summary>
        private int _ClassMenuType;
        public int ClassMenuType
        {
            get
            {
                return _ClassMenuType;
            }
            set
            {
                _ClassMenuType = value;
            }
        }
        private int _SiteId;
        public int SiteId
        {
            get
            {
                return _SiteId;
            }
            set
            {
                _SiteId = value;
            }
        }
        #endregion
    }
}
