 /*****************************************
Table  Name:ComProperty
Create Time:2016/10/31 13:00:04
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ComProperty
	/// This entiy code is generated by codesmith. this entity is ComProperty.
	/// </summary>
	[Serializable()]
	public class ComPropertyEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 通用属性如：颜色，尺码等等
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 编码
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

		#endregion				
	}
}
