 /*****************************************
Table  Name:ConfigNavMenu
Create Time:2017/4/21 15:47:13
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ConfigNavMenu
	/// This entiy code is generated by codesmith. this entity is ConfigNavMenu.
	/// </summary>
	[Serializable()]
	public class ConfigNavMenuEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 菜单枚举记录表（配置相关）
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 分类Id
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}

	    /// <summary>
		/// 品牌Id
		/// <summary>
		private  int _BrandId;
	 	public int BrandId
		{
			get
			{
				return _BrandId;
			}
			set
			{
				_BrandId=value;
			}
		}

	    /// <summary>
		/// 如果不为空，链接到对应Url
		/// <summary>
		private  string _UrlPath;
	 	public string UrlPath
		{
			get
			{
				return _UrlPath;
			}
			set
			{
				_UrlPath=value;
			}
		}

	    /// <summary>
		/// 显示图片路径
		/// <summary>
		private  string _ImagePath;
	 	public string ImagePath
		{
			get
			{
				return _ImagePath;
			}
			set
			{
				_ImagePath=value;
			}
		}

	    /// <summary>
		/// 名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 上级Id（本表自己的Id）
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}

	    /// <summary>
		/// 导航类型：11手机分类导航
		/// <summary>
		private  int _NavMenuType;
	 	public int NavMenuType
		{
			get
			{
				return _NavMenuType;
			}
			set
			{
				_NavMenuType=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 显示方式(具体根据导航类型的不同，页面显示场景不同设置）
		/// <summary>
		private  int _ShowMethod;
	 	public int ShowMethod
		{
			get
			{
				return _ShowMethod;
			}
			set
			{
				_ShowMethod=value;
			}
		}

		#endregion				
	}
}
