 /*****************************************
Table  Name:StaticCarType
Create Time:2016/12/30 13:47:37
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StaticCarType
	/// This entiy code is generated by codesmith. this entity is StaticCarType.
	/// </summary>
	[Serializable()]
	public class StaticCarTypeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarTypeId1;
	 	public int CarTypeId1
		{
			get
			{
				return _CarTypeId1;
			}
			set
			{
				_CarTypeId1=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarTypeName1;
	 	public string CarTypeName1
		{
			get
			{
				return _CarTypeName1;
			}
			set
			{
				_CarTypeName1=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarTypeId2;
	 	public int CarTypeId2
		{
			get
			{
				return _CarTypeId2;
			}
			set
			{
				_CarTypeId2=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarTypeName2;
	 	public string CarTypeName2
		{
			get
			{
				return _CarTypeName2;
			}
			set
			{
				_CarTypeName2=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarTypeId3;
	 	public int CarTypeId3
		{
			get
			{
				return _CarTypeId3;
			}
			set
			{
				_CarTypeId3=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarTypeName3;
	 	public string CarTypeName3
		{
			get
			{
				return _CarTypeName3;
			}
			set
			{
				_CarTypeName3=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarTypeId4;
	 	public int CarTypeId4
		{
			get
			{
				return _CarTypeId4;
			}
			set
			{
				_CarTypeId4=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarTypeName4;
	 	public string CarTypeName4
		{
			get
			{
				return _CarTypeName4;
			}
			set
			{
				_CarTypeName4=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarTypeClassId;
	 	public int CarTypeClassId
		{
			get
			{
				return _CarTypeClassId;
			}
			set
			{
				_CarTypeClassId=value;
			}
		}

		#endregion				
	}
}
