 /*****************************************
Table  Name:StaticClassesFound
Create Time:2016/12/30 13:47:38
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StaticClassesFound
	/// This entiy code is generated by codesmith. this entity is StaticClassesFound.
	/// </summary>
	[Serializable()]
	public class StaticClassesFoundEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ClassId1;
	 	public int ClassId1
		{
			get
			{
				return _ClassId1;
			}
			set
			{
				_ClassId1=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ClassName1;
	 	public string ClassName1
		{
			get
			{
				return _ClassName1;
			}
			set
			{
				_ClassName1=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ClassId2;
	 	public int ClassId2
		{
			get
			{
				return _ClassId2;
			}
			set
			{
				_ClassId2=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ClassName2;
	 	public string ClassName2
		{
			get
			{
				return _ClassName2;
			}
			set
			{
				_ClassName2=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ClassId3;
	 	public int ClassId3
		{
			get
			{
				return _ClassId3;
			}
			set
			{
				_ClassId3=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ClassName3;
	 	public string ClassName3
		{
			get
			{
				return _ClassName3;
			}
			set
			{
				_ClassName3=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ClassId4;
	 	public int ClassId4
		{
			get
			{
				return _ClassId4;
			}
			set
			{
				_ClassId4=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ClassName4;
	 	public string ClassName4
		{
			get
			{
				return _ClassName4;
			}
			set
			{
				_ClassName4=value;
			}
		}

	    /// <summary>
		/// 尾子分类
		/// <summary>
		private  int _ClassEndId;
	 	public int ClassEndId
		{
			get
			{
				return _ClassEndId;
			}
			set
			{
				_ClassEndId=value;
			}
		}
        private int _ClassType;
        public int ClassType
        {
            get
            {
                return _ClassType;
            }
            set
            {
                _ClassType = value;
            }
        }
        
        #endregion
    }
}
