 /*****************************************
Table  Name:PayOrderReback
Create Time:2017/11/29 16:19:49
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>PayOrderReback
	/// This entiy code is generated by codesmith. this entity is PayOrderReback.
	/// </summary>
	[Serializable()]
	public class PayOrderRebackEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 退款记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 退款编号
		/// <summary>
		private  string _PayRebackCode;
	 	public string PayRebackCode
		{
			get
			{
				return _PayRebackCode;
			}
			set
			{
				_PayRebackCode=value;
			}
		}

	    /// <summary>
		/// 支付编号
		/// <summary>
		private  string _PayOrderCode;
	 	public string PayOrderCode
		{
			get
			{
				return _PayOrderCode;
			}
			set
			{
				_PayOrderCode=value;
			}
		}

	    /// <summary>
		/// 系统订单编号
		/// <summary>
		private  string _SysOrderCode;
	 	public string SysOrderCode
		{
			get
			{
				return _SysOrderCode;
			}
			set
			{
				_SysOrderCode=value;
			}
		}

	    /// <summary>
		/// 应用系统类别
		/// <summary>
		private  int _SysType;
	 	public int SysType
		{
			get
			{
				return _SysType;
			}
			set
			{
				_SysType=value;
			}
		}

	    /// <summary>
		/// 支付方式
		/// <summary>
		private  int _PayMethod;
	 	public int PayMethod
		{
			get
			{
				return _PayMethod;
			}
			set
			{
				_PayMethod=value;
			}
		}

	    /// <summary>
		/// 付款外部接口唯一码
		/// <summary>
		private  string _ExternalCode;
	 	public string ExternalCode
		{
			get
			{
				return _ExternalCode;
			}
			set
			{
				_ExternalCode=value;
			}
		}
        
        /// <summary>
        /// 总金额
        /// <summary>
        private decimal _TotalPrice;
        public decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                _TotalPrice = value;
            }
        }
        /// <summary>
        /// 退款金额
        /// <summary>
        private  decimal _RebackPrice;
	 	public decimal RebackPrice
		{
			get
			{
				return _RebackPrice;
			}
			set
			{
				_RebackPrice=value;
			}
		}

	    /// <summary>
		/// 退款备注
		/// <summary>
		private  string _RebackRemark;
	 	public string RebackRemark
		{
			get
			{
				return _RebackRemark;
			}
			set
			{
				_RebackRemark=value;
			}
		}

	    /// <summary>
		/// 时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 退款状态0待退款，1已退款，2作废
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
