 /*****************************************
Table  Name:WeChatResult
Create Time:2017/11/29 10:53:09
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WeChatResult
	/// This entiy code is generated by codesmith. this entity is WeChatResult.
	/// </summary>
	[Serializable()]
	public class WeChatResultEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 微信的返回信息记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Appid;
	 	public string Appid
		{
			get
			{
				return _Appid;
			}
			set
			{
				_Appid=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Bank_type;
	 	public string Bank_type
		{
			get
			{
				return _Bank_type;
			}
			set
			{
				_Bank_type=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Cash_fee;
	 	public string Cash_fee
		{
			get
			{
				return _Cash_fee;
			}
			set
			{
				_Cash_fee=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Fee_type;
	 	public string Fee_type
		{
			get
			{
				return _Fee_type;
			}
			set
			{
				_Fee_type=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Is_subscribe;
	 	public string Is_subscribe
		{
			get
			{
				return _Is_subscribe;
			}
			set
			{
				_Is_subscribe=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Mch_id;
	 	public string Mch_id
		{
			get
			{
				return _Mch_id;
			}
			set
			{
				_Mch_id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Nonce_str;
	 	public string Nonce_str
		{
			get
			{
				return _Nonce_str;
			}
			set
			{
				_Nonce_str=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Openid;
	 	public string Openid
		{
			get
			{
				return _Openid;
			}
			set
			{
				_Openid=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Out_trade_no;
	 	public string Out_trade_no
		{
			get
			{
				return _Out_trade_no;
			}
			set
			{
				_Out_trade_no=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Result_code;
	 	public string Result_code
		{
			get
			{
				return _Result_code;
			}
			set
			{
				_Result_code=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Return_code;
	 	public string Return_code
		{
			get
			{
				return _Return_code;
			}
			set
			{
				_Return_code=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Sign;
	 	public string Sign
		{
			get
			{
				return _Sign;
			}
			set
			{
				_Sign=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Time_end;
	 	public string Time_end
		{
			get
			{
				return _Time_end;
			}
			set
			{
				_Time_end=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Total_fee;
	 	public string Total_fee
		{
			get
			{
				return _Total_fee;
			}
			set
			{
				_Total_fee=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Trade_type;
	 	public string Trade_type
		{
			get
			{
				return _Trade_type;
			}
			set
			{
				_Trade_type=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Transaction_id;
	 	public string Transaction_id
		{
			get
			{
				return _Transaction_id;
			}
			set
			{
				_Transaction_id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
