 /*****************************************
Table  Name:DisCount
Create Time:2016/8/16 13:54:28
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>DisCount
	/// This entiy code is generated by codesmith. this entity is DisCount.
	/// </summary>
	[Serializable()]
	public class DisCountEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 折扣码（自动生成）
		/// <summary>
		private  string _DisCountCode;
	 	public string DisCountCode
		{
			get
			{
				return _DisCountCode;
			}
			set
			{
				_DisCountCode=value;
			}
		}

	    /// <summary>
		/// 优惠券名称
		/// <summary>
		private  string _DisCountName;
	 	public string DisCountName
		{
			get
			{
				return _DisCountName;
			}
			set
			{
				_DisCountName=value;
			}
		}

	    /// <summary>
		/// 折扣类型：1.订单满减，2.按照产品折扣率优惠.3.单品优惠，4.订单满送赠品,5.抵扣券
		/// <summary>
		private  int _DisType;
	 	public int DisType
		{
			get
			{
				return _DisType;
			}
			set
			{
				_DisType=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  double _DiscountRate;
	 	public double DiscountRate
		{
			get
			{
				return _DiscountRate;
			}
			set
			{
				_DiscountRate=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _DiscountAmt;
	 	public decimal DiscountAmt
		{
			get
			{
				return _DiscountAmt;
			}
			set
			{
				_DiscountAmt=value;
			}
		}

	    /// <summary>
		/// 商家Id
		/// <summary>
		private  int _SellerId;
	 	public int SellerId
		{
			get
			{
				return _SellerId;
			}
			set
			{
				_SellerId=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 是否自动使用
		/// <summary>
		private  int _IsDefault;
	 	public int IsDefault
		{
			get
			{
				return _IsDefault;
			}
			set
			{
				_IsDefault=value;
			}
		}

		#endregion				
	}
}
