 /*****************************************
Table  Name:ProductMenu
Create Time:2017/2/15 9:13:34
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model 
{ 	
	/// <summary>ProductMenu
	/// This entiy code is generated by codesmith. this entity is ProductMenu.
	/// </summary>
	[Serializable()]
	public class ProductMenuEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 菜单显示产品记录表(爆品，限量乐购等
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品明细Id,可以为0代表品牌或分类
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 分类ID
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _BrandId;
	 	public int BrandId
		{
			get
			{
				return _BrandId;
			}
			set
			{
				_BrandId=value;
			}
		}

	    /// <summary>
		/// 类型：1爆品产品，11爆品品牌，2限量乐购，
		/// <summary>
		private  int _MenuType;
	 	public int MenuType
		{
			get
			{
				return _MenuType;
			}
			set
			{
				_MenuType=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ProductSmallPicUrl;
	 	public string ProductSmallPicUrl
		{
			get
			{
				return _ProductSmallPicUrl;
			}
			set
			{
				_ProductSmallPicUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ProductPicUrl;
	 	public string ProductPicUrl
		{
			get
			{
				return _ProductPicUrl;
			}
			set
			{
				_ProductPicUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _BeginTime;
	 	public DateTime BeginTime
		{
			get
			{
				return _BeginTime;
			}
			set
			{
				_BeginTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

		#endregion				
	}
}
