 /*****************************************
Table  Name:ProductStyle
Create Time:2016/8/23 16:49:59
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductStyle
	/// This entiy code is generated by codesmith. this entity is ProductStyle.
	/// </summary>
	[Serializable()]
	public class ProductStyleEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _AdTitle;
	 	public string AdTitle
		{
			get
			{
				return _AdTitle;
			}
			set
			{
				_AdTitle=value;
			}
		}
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    
	    /// <summary>
		/// 品牌名称
		/// <summary>
		private  int _BrandId;
	 	public int BrandId
		{
			get
			{
				return _BrandId;
			}
			set
			{
				_BrandId=value;
			}
		}

	    /// <summary>
		/// 显示价格
		/// <summary>
		private  decimal _Price;
	 	public decimal Price
		{
			get
			{
				return _Price;
			}
			set
			{
				_Price=value;
			}
		}
        /// <summary>
        /// 显示价格
        /// <summary>
        private decimal _Cost;
        public decimal Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                _Cost = value;
            }
        }
        
        /// <summary>
        /// 市场价
        /// <summary>
        private  decimal _MarketPrice;
	 	public decimal MarketPrice
		{
			get
			{
				return _MarketPrice;
			}
			set
			{
				_MarketPrice=value;
			}
		}
        /// <summary>
        /// 市场价
        /// <summary>
        private decimal _TradePrice;
        public decimal TradePrice
        {
            get
            {
                return _TradePrice;
            }
            set
            {
                _TradePrice = value;
            }
        }
        
        /// <summary>
        /// 列表页显示图片地址
        /// <summary>
        private  string _PicUrl="";
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

        /// <summary>
        /// 图片扩展名
        /// </summary>
        private string _PicSuffix;
        public string PicSuffix
        {
            get
            {
                return _PicSuffix;
            }
            set
            {
                _PicSuffix = value;
            }
        }


	    /// <summary>
		/// 默认的产品Id，列表页的连接
		/// <summary>
		private  int _DefaultProductId;
	 	public int DefaultProductId
		{
			get
			{
				return _DefaultProductId;
			}
			set
			{
				_DefaultProductId=value;
			}
		}

	    /// <summary>
		/// 终极分类Id
		/// <summary>
		private  int _ClassFoundId;
	 	public int ClassId
		{
			get
			{
				return _ClassFoundId;
			}
			set
			{
				_ClassFoundId=value;
			}
		}

	    /// <summary>
		/// 是否已生成对应的产品静态页或缓存等
		/// <summary>
		private  int _HasHtml;
	 	public int HasHtml
		{
			get
			{
				return _HasHtml;
			}
			set
			{
				_HasHtml=value;
			}
		}
        /// <summary>
        /// 显示价格
        /// <summary>
        private decimal _SellerId;
        public decimal SellerId
        {
            get
            {
                return _SellerId;
            }
            set
            {
                _SellerId = value;
            }
        }
        /// <summary>
        /// 显示价格
        /// <summary>
        private decimal _Num;
        public decimal Num
        {
            get
            {
                return _Num;
            }
            set
            {
                _Num = value;
            }
        }
      
        /// <summary>
        /// 是否有Product
        /// <summary>
        private decimal _HasProduct;
        public decimal HasProduct
        {
            get
            {
                return _HasProduct;
            }
            set
            {
                _HasProduct = value;
            }
        }
        /// <summary>
        /// SaleNum
        /// <summary>
        private decimal _SaleNum;
        public decimal SaleNum
        {
            get
            {
                return _SaleNum;
            }
            set
            {
                _SaleNum = value;
            }
        }
        private int _Sort;
        public int Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                _Sort = value;
            }
        }
        
        private decimal _Weight;
        public decimal Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                _Weight = value;
            }
        }
        private decimal _Volume;
        public decimal Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                _Volume = value;
            }
        }
        private int _PostDisCountId;
        public int PostDisCountId
        {
            get
            {
                return _PostDisCountId;
            }
            set
            {
                _PostDisCountId = value;
            }
        }


        /// <summary>
        /// 品牌名称
        /// </summary>
        private string _BrandName;
        public string BrandName
        {
            get
            {
                return _BrandName;
            }
            set
            {
                _BrandName = value;
            }
        }


        /// <summary>
        /// 分类名称
        /// </summary>
        private string _ClassName;
        public string ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                _ClassName = value;
            }
        }



        #endregion
    }
}
