 /*****************************************
Table  Name:ProductSimilarHot
Create Time:2016/9/8 15:01:42
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductSimilarHot
	/// This entiy code is generated by codesmith. this entity is ProductSimilarHot.
	/// </summary>
	[Serializable()]
	public class ProductSimilarHotEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 同类热销款式
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 类别Id
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}

	    /// <summary>
		/// 款式Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 销量
		/// <summary>
		private  int _SalesNum;
	 	public int SalesNum
		{
			get
			{
				return _SalesNum;
			}
			set
			{
				_SalesNum=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
