 /*****************************************
Table  Name:ProductProperty
Create Time:2016/10/31 16:27:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductProperty
	/// This entiy code is generated by codesmith. this entity is ProductProperty.
	/// </summary>
	[Serializable()]
	public class ProductPropertiesEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 款式属性记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 款式属性名称Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
                _ProductId = value;
			}
		}
        public string Property1 { get; set; }
        public string Property2 { get; set; }
        public string Property3 { get; set; }
        public string Property4 { get; set; }
        public string Property5 { get; set; }
        public string Property6 { get; set; }
        public string Property7 { get; set; }
        public string Property8 { get; set; }
        public string Property9 { get; set; }
        public string Property10 { get; set; }
        #endregion
    }
}
