 /*****************************************
Table  Name:ProductSpecial
Create Time:2017/5/16 11:30:33
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductSpecial
	/// This entiy code is generated by codesmith. this entity is ProductSpecial.
	/// </summary>
	[Serializable()]
	public class ProductSpecialEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 产品专区记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 短名称
		/// <summary>
		private  string _ShortName;
	 	public string ShortName
		{
			get
			{
				return _ShortName;
			}
			set
			{
				_ShortName=value;
			}
		}

	    /// <summary>
		/// 全名称
		/// <summary>
		private  string _FullName;
	 	public string FullName
		{
			get
			{
				return _FullName;
			}
			set
			{
				_FullName=value;
			}
		}

	    /// <summary>
		/// 备注说明：如优惠信息
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

	    /// <summary>
		/// 入口图片
		/// <summary>
		private  string _EnPicUrl;
	 	public string EnPicUrl
		{
			get
			{
				return _EnPicUrl;
			}
			set
			{
				_EnPicUrl=value;
			}
		}

	    /// <summary>
		/// 入口图后缀
		/// <summary>
		private  string _EnPicSuffix;
	 	public string EnPicSuffix
		{
			get
			{
				return _EnPicSuffix;
			}
			set
			{
				_EnPicSuffix=value;
			}
		}

	    /// <summary>
		/// 展示图
		/// <summary>
		private  string _ExPicUrl;
	 	public string ExPicUrl
		{
			get
			{
				return _ExPicUrl;
			}
			set
			{
				_ExPicUrl=value;
			}
		}

	    /// <summary>
		/// 展示图后缀
		/// <summary>
		private  string _ExPicSuffix;
	 	public string ExPicSuffix
		{
			get
			{
				return _ExPicSuffix;
			}
			set
			{
				_ExPicSuffix=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _BeginTime;
	 	public DateTime BeginTime
		{
			get
			{
				return _BeginTime;
			}
			set
			{
				_BeginTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 系统类别
		/// <summary>
		private  int _SystemType;
	 	public int SystemType
		{
			get
			{
				return _SystemType;
			}
			set
			{
				_SystemType=value;
			}
		}

	    /// <summary>
		/// 专区类别：1常规专区,2隐藏专区
		/// <summary>
		private  int _SpecialType;
	 	public int SpecialType
		{
			get
			{
				return _SpecialType;
			}
			set
			{
				_SpecialType=value;
			}
		}
        private string _RedirectUrl;
        public string RedirectUrl
        {
            get
            {
                return _RedirectUrl;
            }
            set
            {
                _RedirectUrl = value;
            }
        }
        
        #endregion
    }
}
