 /*****************************************
Table  Name:StyleSpec
Create Time:2016/8/16 13:54:29
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StyleSpec
	/// This entiy code is generated by codesmith. this entity is StyleSpec.
	/// </summary>
	[Serializable()]
	public class ProductStyleSpecEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 款式规格列表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 款式Id
		/// <summary>
		private  int _StyleId;
	 	public int StyleId
		{
			get
			{
				return _StyleId;
			}
			set
			{
				_StyleId=value;
			}
		}

	    /// <summary>
		/// 规格Id
		/// <summary>
		private  int _SpecId;
	 	public int SpecId
		{
			get
			{
				return _SpecId;
			}
			set
			{
				_SpecId=value;
			}
		}

	    /// <summary>
		/// 规格内容Id
		/// <summary>
		private  int _SpecDetailId;
	 	public int SpecDetailId
		{
			get
			{
				return _SpecDetailId;
			}
			set
			{
				_SpecDetailId=value;
			}
		}

	    /// <summary>
		/// 规格内容排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
