 /*****************************************
Table  Name:ProductExt
Create Time:2017/3/15 0:42:16
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductExt
	/// This entiy code is generated by codesmith. this entity is ProductExt.
	/// </summary>
	[Serializable()]
	public class ProductExtEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _DetailDescrip;
	 	public string DetailDescrip
		{
			get
			{
				return _DetailDescrip;
			}
			set
			{
				_DetailDescrip=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _SpecModel;
	 	public string SpecModel
		{
			get
			{
				return _SpecModel;
			}
			set
			{
				_SpecModel=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _SpecPacking;
	 	public string SpecPacking
		{
			get
			{
				return _SpecPacking;
			}
			set
			{
				_SpecPacking=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        private string _Manufacturer;
        public string Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                _Manufacturer = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private  string _APPModels;
	 	public string APPModels
		{
			get
			{
				return _APPModels;
			}
			set
			{
				_APPModels=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _OEMPartNos;
	 	public string OEMPartNos
		{
			get
			{
				return _OEMPartNos;
			}
			set
			{
				_OEMPartNos=value;
			}
		}

		#endregion				
	}
}
