 /*****************************************
Table  Name:ProductCarType
Create Time:2016/10/31 16:27:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductCarType
	/// This entiy code is generated by codesmith. this entity is ProductCarType.
	/// </summary>
	[Serializable()]
	public class ProductCarTypeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 款式适合车型记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 款式Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 车型品牌1级：乘用车，商用车。。。CarType
		/// <summary>
		private  int _CarType1;
	 	public int CarType1
		{
			get
			{
				return _CarType1;
			}
			set
			{
				_CarType1=value;
			}
		}

	    /// <summary>
		/// 车品牌2：奥迪。。。
		/// <summary>
		private  int _CarType2;
	 	public int CarType2
		{
			get
			{
				return _CarType2;
			}
			set
			{
				_CarType2=value;
			}
		}

	    /// <summary>
		/// 车系3级：Q5...
		/// <summary>
		private  int _CarType3;
	 	public int CarType3
		{
			get
			{
				return _CarType3;
			}
			set
			{
				_CarType3=value;
			}
		}

	    /// <summary>
		/// 车型4级：2015 豪华型。。。
		/// <summary>
		private  int _CarType4;
	 	public int CarType4
		{
			get
			{
				return _CarType4;
			}
			set
			{
				_CarType4=value;
			}
		}
        /// <summary>
        /// 车型品牌1级：乘用车，商用车。。。CarType
        /// <summary>
        private string _CarType1Name;
        public string CarType1Name
        {
            get
            {
                return _CarType1Name;
            }
            set
            {
                _CarType1Name = value;
            }
        }

        /// <summary>
        /// 车品牌2：奥迪。。。
        /// <summary>
        private string _CarType2Name;
        public string CarType2Name
        {
            get
            {
                return _CarType2Name;
            }
            set
            {
                _CarType2Name = value;
            }
        }

        /// <summary>
        /// 车系3级：Q5...
        /// <summary>
        private string _CarType3Name;
        public string CarType3Name
        {
            get
            {
                return _CarType3Name;
            }
            set
            {
                _CarType3Name = value;
            }
        }

        /// <summary>
        /// 车型4级：2015 豪华型。。。
        /// <summary>
        private string _CarType4Name;
        public string CarType4Name
        {
            get
            {
                return _CarType4Name;
            }
            set
            {
                _CarType4Name = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
