 /*****************************************
Table  Name:ProductBaoPin
Create Time:2017/4/15 15:37:40
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductBaoPin
	/// This entiy code is generated by codesmith. this entity is ProductBaoPin.
	/// </summary>
	[Serializable()]
	public class ProductBaoPinEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 爆品记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品价格明细表Id
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 爆品开始时间
		/// <summary>
		private  DateTime _BeginTime;
	 	public DateTime BeginTime
		{
			get
			{
				return _BeginTime;
			}
			set
			{
				_BeginTime=value;
			}
		}

	    /// <summary>
		/// 爆品结束时间
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
