 /*****************************************
Table  Name:ProductCarTypeModel
Create Time:2017/6/20 16:42:43
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductCarTypeModel
	/// This entiy code is generated by codesmith. this entity is ProductCarTypeModel.
	/// </summary>
	[Serializable()]
	public class ProductCarTypeModelEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 产品车型数据记录
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 车型编码
		/// <summary>
		private  string _ModelCode;
	 	public string ModelCode
		{
			get
			{
				return _ModelCode;
			}
			set
			{
				_ModelCode=value;
			}
		}

	    /// <summary>
		/// 添加时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 操作人Id
		/// <summary>
		private  int _CreateManId;
	 	public int CreateManId
		{
			get
			{
				return _CreateManId;
			}
			set
			{
				_CreateManId=value;
			}
		}

		#endregion				
	}
}
