 /*****************************************
Table  Name:ProductDailyGrab
Create Time:2017/10/10 9:07:27
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ProductDailyGrab
	/// This entiy code is generated by codesmith. this entity is ProductDailyGrab.
	/// </summary>
	[Serializable()]
	public class ProductDailyGrabEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 每日一抢记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 产品详情Id
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 最少购买数量
		/// <summary>
		private  int _MinLimitNum;
	 	public int MinLimitNum
		{
			get
			{
				return _MinLimitNum;
			}
			set
			{
				_MinLimitNum=value;
			}
		}

	    /// <summary>
		/// 抢购返金额，如果购买多个，以最多的金额返还，不累加
		/// <summary>
		private  decimal _ReturnPrice;
	 	public decimal ReturnPrice
		{
			get
			{
				return _ReturnPrice;
			}
			set
			{
				_ReturnPrice=value;
			}
		}

	    /// <summary>
		/// 状态1当前有效每日一抢 
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

		#endregion				
	}
}
