 /*****************************************
Table  Name:StatisticData
Create Time:2016/8/16 13:54:29
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StatisticData
	/// This entiy code is generated by codesmith. this entity is StatisticData.
	/// </summary>
	[Serializable()]
	public class StatisticDataEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 商家数据统计表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 商家编号
		/// <summary>
		private  int _SellerId;
	 	public int SellerId
		{
			get
			{
				return _SellerId;
			}
			set
			{
				_SellerId=value;
			}
		}

	    /// <summary>
		/// 总量
		/// <summary>
		private  int _TotalNum;
	 	public int TotalNum
		{
			get
			{
				return _TotalNum;
			}
			set
			{
				_TotalNum=value;
			}
		}

	    /// <summary>
		/// 手机端量
		/// <summary>
		private  int _PcNum;
	 	public int PcNum
		{
			get
			{
				return _PcNum;
			}
			set
			{
				_PcNum=value;
			}
		}

	    /// <summary>
		/// 电脑端量
		/// <summary>
		private  int _MobileNum;
	 	public int MobileNum
		{
			get
			{
				return _MobileNum;
			}
			set
			{
				_MobileNum=value;
			}
		}

	    /// <summary>
		/// 数据类型：1点击量，2订单量，3成交量，4退单量，5退单率，6收入，7支出，
		/// <summary>
		private  int _SDataType;
	 	public int SDataType
		{
			get
			{
				return _SDataType;
			}
			set
			{
				_SDataType=value;
			}
		}

	    /// <summary>
		/// 日期
		/// <summary>
		private  string _CreateDate;
	 	public string CreateDate
		{
			get
			{
				return _CreateDate;
			}
			set
			{
				_CreateDate=value;
			}
		}

		#endregion				
	}
}
