 /*****************************************
Table  Name:StatisticProductSpec
Create Time:2016/11/10 16:01:18
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StatisticProductSpec
	/// This entiy code is generated by codesmith. this entity is StatisticProductSpec.
	/// </summary>
	[Serializable()]
	public class StatisticProductSpecEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 统计表：提高查询效率，款式对应的所有选择项
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 款式ID
		/// <summary>
		private  int _StyleId;
	 	public int StyleId
		{
			get
			{
				return _StyleId;
			}
			set
			{
				_StyleId=value;
			}
		}

	    /// <summary>
		/// 选择项1的集合：名称_图片路径|名称_图片路径|名称_图片路径
		/// <summary>
		private  string _Spec1Merge;
	 	public string Spec1Merge
		{
			get
			{
				return _Spec1Merge;
			}
			set
			{
				_Spec1Merge=value;
			}
		}

	    /// <summary>
		/// 选择项2的集合：名称_图片路径|名称_图片路径|名称_图片路径
		/// <summary>
		private  string _Spec2Merge;
	 	public string Spec2Merge
		{
			get
			{
				return _Spec2Merge;
			}
			set
			{
				_Spec2Merge=value;
			}
		}

	    /// <summary>
		/// 选择项3的集合：名称_图片路径|名称_图片路径|名称_图片路径
		/// <summary>
		private  string _Spec3Merge;
	 	public string Spec3Merge
		{
			get
			{
				return _Spec3Merge;
			}
			set
			{
				_Spec3Merge=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _UpdateTime;
	 	public DateTime UpdateTime
		{
			get
			{
				return _UpdateTime;
			}
			set
			{
				_UpdateTime=value;
			}
		}

		#endregion				
	}
}
