 /*****************************************
Table  Name:WzAdClassR
Create Time:2016/8/16 13:54:29
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WzAdClassR
	/// This entiy code is generated by codesmith. this entity is WzAdClassR.
	/// </summary>
	[Serializable()]
	public class WzAdClassREntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 1级分类Id
		/// <summary>
		private  int _ClassFound1;
	 	public int ClassFound1
		{
			get
			{
				return _ClassFound1;
			}
			set
			{
				_ClassFound1=value;
			}
		}

	    /// <summary>
		/// 2级分类Id
		/// <summary>
		private  int _ClassFound2;
	 	public int ClassFound2
		{
			get
			{
				return _ClassFound2;
			}
			set
			{
				_ClassFound2=value;
			}
		}

	    /// <summary>
		/// 3级分类Id
		/// <summary>
		private  int _ClassFound3;
	 	public int ClassFound3
		{
			get
			{
				return _ClassFound3;
			}
			set
			{
				_ClassFound3=value;
			}
		}

	    /// <summary>
		/// 广告Id
		/// <summary>
		private  int _AdId;
	 	public int AdId
		{
			get
			{
				return _AdId;
			}
			set
			{
				_AdId=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _UpdateTime;
	 	public DateTime UpdateTime
		{
			get
			{
				return _UpdateTime;
			}
			set
			{
				_UpdateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _UpdateManId;
	 	public int UpdateManId
		{
			get
			{
				return _UpdateManId;
			}
			set
			{
				_UpdateManId=value;
			}
		}

		#endregion				
	}
}
