 /*****************************************
Table  Name:CGProCertifacate
Create Time:2017/1/5 14:30:48
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProCertifacate
	/// This entiy code is generated by codesmith. this entity is CGProCertifacate.
	/// </summary>
	[Serializable()]
	public class CGProCertifacateEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 供应商Id
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 证件名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 路径
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

	    /// <summary>
		/// 后缀名
		/// <summary>
		private  string _PicSuffix;
	 	public string PicSuffix
		{
			get
			{
				return _PicSuffix;
			}
			set
			{
				_PicSuffix=value;
			}
		}

	    /// <summary>
		/// 上传时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 状态,0待审核,1审核过 
		/// <summary>
		private  int _HasChecked;
	 	public int HasChecked
        {
			get
			{
				return _HasChecked;
			}
			set
			{
                _HasChecked = value;
			}
		}
        /// <summary>
        /// 是否
        /// </summary>
        private int _IsEffective;
        public int IsEffective
        {
            get
            {
                return _IsEffective;
            }
            set
            {
                _IsEffective = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  int _CheckManId;
	 	public int CheckManId
		{
			get
			{
				return _CheckManId;
			}
			set
			{
				_CheckManId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CheckTime;
	 	public DateTime CheckTime
		{
			get
			{
				return _CheckTime;
			}
			set
			{
				_CheckTime=value;
			}
		}

		#endregion				
	}
}
