 /*****************************************
Table  Name:CGProductStockApp
Create Time:2017/1/17 11:52:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProductStockApp
	/// This entiy code is generated by codesmith. this entity is CGProductStockApp.
	/// </summary>
	[Serializable()]
	public class CGProductStockAppEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _StockNum;
	 	public int StockNum
		{
			get
			{
				return _StockNum;
			}
			set
			{
				_StockNum=value;
			}
		}
        private decimal _SuggestPrice;
        public decimal SuggestPrice
        {
            get
            {
                return _SuggestPrice;
            }
            set
            {
                _SuggestPrice = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CheckTime;
	 	public DateTime CheckTime
		{
			get
			{
				return _CheckTime;
			}
			set
			{
				_CheckTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CheckManId;
	 	public int CheckManId
		{
			get
			{
				return _CheckManId;
			}
			set
			{
				_CheckManId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProvinceId;
	 	public int ProvinceId
		{
			get
			{
				return _ProvinceId;
			}
			set
			{
				_ProvinceId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CityId;
	 	public int CityId
		{
			get
			{
				return _CityId;
			}
			set
			{
				_CityId=value;
			}
		}

   

        #endregion
    }
}
