 /*****************************************
Table  Name:CGProductsLongitude
Create Time:2016/12/28 15:59:31
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProductsLongitude
	/// This entiy code is generated by codesmith. this entity is CGProductsLongitude.
	/// </summary>
	[Serializable()]
	public class CGProductsLongitudeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 车型第一级
		/// <summary>
		private  int _CarTypeId1;
	 	public int CarTypeId1
		{
			get
			{
				return _CarTypeId1;
			}
			set
			{
				_CarTypeId1=value;
			}
		}

	    /// <summary>
		/// 车型第二级Id
		/// <summary>
		private  int _CarTypeId2;
	 	public int CarTypeId2
		{
			get
			{
				return _CarTypeId2;
			}
			set
			{
				_CarTypeId2=value;
			}
		}

	    /// <summary>
		/// 车型第三级Id
		/// <summary>
		private  int _CarTypeId3;
	 	public int CarTypeId3
		{
			get
			{
				return _CarTypeId3;
			}
			set
			{
				_CarTypeId3=value;
			}
		}

	    /// <summary>
		/// 车型第四级Id
		/// <summary>
		private  int _CarTypeId4;
	 	public int CarTypeId4
		{
			get
			{
				return _CarTypeId4;
			}
			set
			{
				_CarTypeId4=value;
			}
		}
        /// <summary>
        /// 车型第一级
        /// <summary>
        private string _CarTypeName1;
        public string CarTypeName1
        {
            get
            {
                return _CarTypeName1;
            }
            set
            {
                _CarTypeName1 = value;
            }
        }

        /// <summary>
        /// 车型第二级Id
        /// <summary>
        private string _CarTypeName2;
        public string CarTypeName2
        {
            get
            {
                return _CarTypeName2;
            }
            set
            {
                _CarTypeName2 = value;
            }
        }

        /// <summary>
        /// 车型第三级Id
        /// <summary>
        private string _CarTypeName3;
        public string CarTypeName3
        {
            get
            {
                return _CarTypeName3;
            }
            set
            {
                _CarTypeName3 = value;
            }
        }

        /// <summary>
        /// 车型第四级Id
        /// <summary>
        private string _CarTypeName4;
        public string CarTypeName4
        {
            get
            {
                return _CarTypeName4;
            }
            set
            {
                _CarTypeName4 = value;
            }
        }
        /// <summary>
        /// 状态,0待审核,1审核过 
        /// <summary>
        private int _HasChecked;
        public int HasChecked
        {
            get
            {
                return _HasChecked;
            }
            set
            {
                _HasChecked = value;
            }
        }
        /// <summary>
        /// 是否
        /// </summary>
        private int _IsEffective;
        public int IsEffective
        {
            get
            {
                return _IsEffective;
            }
            set
            {
                _IsEffective = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
