 /*****************************************
Table  Name:CGProductsTransverse
Create Time:2016/12/28 15:59:32
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProductsTransverse
	/// This entiy code is generated by codesmith. this entity is CGProductsTransverse.
	/// </summary>
	[Serializable()]
	public class CGProductsTransverseEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 第一级分类Id
		/// <summary>
		private  int _ClassId1;
	 	public int ClassId1
		{
			get
			{
				return _ClassId1;
			}
			set
			{
				_ClassId1=value;
			}
		}

	    /// <summary>
		/// 第二级分类Id
		/// <summary>
		private  int _ClassId2;
	 	public int ClassId2
		{
			get
			{
				return _ClassId2;
			}
			set
			{
				_ClassId2=value;
			}
		}

	    /// <summary>
		/// 第三级分类Id
		/// <summary>
		private  int _ClassId3;
	 	public int ClassId3
		{
			get
			{
				return _ClassId3;
			}
			set
			{
				_ClassId3=value;
			}
		}

	    /// <summary>
		/// 第四级分类Id
		/// <summary>
		private  int _ClassId4;
	 	public int ClassId4
		{
			get
			{
				return _ClassId4;
			}
			set
			{
				_ClassId4=value;
			}
		}

	    /// <summary>
		/// 品牌Id
		/// <summary>
		private  int _BrandId;
	 	public int BrandId
		{
			get
			{
				return _BrandId;
			}
			set
			{
				_BrandId=value;
			}
		}
        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }
        
        /// <summary>
        /// 第一级分类Id
        /// <summary>
        private string _ClassName1;
        public string ClassName1
        {
            get
            {
                return _ClassName1;
            }
            set
            {
                _ClassName1 = value;
            }
        }

        /// <summary>
        /// 第二级分类Id
        /// <summary>
        private string _ClassName2;
        public string ClassName2
        {
            get
            {
                return _ClassName2;
            }
            set
            {
                _ClassName2 = value;
            }
        }

        /// <summary>
        /// 第三级分类Id
        /// <summary>
        private string _ClassName3;
        public string ClassName3
        {
            get
            {
                return _ClassName3;
            }
            set
            {
                _ClassName3 = value;
            }
        }

        /// <summary>
        /// 第四级分类Id
        /// <summary>
        private string _ClassName4;
        public string ClassName4
        {
            get
            {
                return _ClassName4;
            }
            set
            {
                _ClassName4 = value;
            }
        }

        /// <summary>
        /// 品牌Id
        /// <summary>
        private string _BrandName ;
        public string BrandName 
        {
            get
            {
                return _BrandName ;
            }
            set
            {
                _BrandName  = value;
            }
        }

        /// <summary>
        /// 状态,0待审核,1审核过 
        /// <summary>
        private int _HasChecked;
        public int HasChecked
        {
            get
            {
                return _HasChecked;
            }
            set
            {
                _HasChecked = value;
            }
        }
        /// <summary>
        /// 是否
        /// </summary>
        private int _IsEffective;
        public int IsEffective
        {
            get
            {
                return _IsEffective;
            }
            set
            {
                _IsEffective = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
