 /*****************************************
Table  Name:CGProductLLog
Create Time:2017/1/5 14:30:48
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProductLLog
	/// This entiy code is generated by codesmith. this entity is CGProductLLog.
	/// </summary>
	[Serializable()]
	public class CGProductLLogEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 操作人Id
		/// <summary>
		private  int _ManId;
	 	public int ManId
		{
			get
			{
				return _ManId;
			}
			set
			{
				_ManId=value;
			}
		}

	    /// <summary>
		/// 操作说明
		/// <summary>
		private  string _OperationDES;
	 	public string OperationDES
		{
			get
			{
				return _OperationDES;
			}
			set
			{
				_OperationDES=value;
			}
		}

	    /// <summary>
		/// 纵向件Id
		/// <summary>
		private  int _ProductsLId;
	 	public int ProductsLId
		{
			get
			{
				return _ProductsLId;
			}
			set
			{
				_ProductsLId=value;
			}
		}

	    /// <summary>
		/// 操作类型，1审核通过，2审核拒绝，3唤醒，4删除
		/// <summary>
		private  int _OpType;
	 	public int OpType
		{
			get
			{
				return _OpType;
			}
			set
			{
				_OpType=value;
			}
		}

		#endregion				
	}
}
