/*****************************************
Table  Name:Brand
Create Time:2016/10/31 13:00:02
Creator    :jc001
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Brand
	/// This entiy code is generated by codesmith. this entity is Brand.
	/// </summary>
	[Serializable()]
	public class VWTreeBrandEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 汽车品牌表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}
        

	    /// <summary>
		/// 品牌名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}


	    /// <summary>
		/// 缩写
		/// <summary>
		private  string _PYFirst;
	 	public string PYFirst
        {
			get
			{
				return _PYFirst;
			}
			set
			{
                _PYFirst = value;
			}
		}
 
	    /// <summary>
		/// 是否排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}
         
	    /// <summary>
		/// 上级Id
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}


        public IList<VWTreeBrandEntity> Children;
      
        #endregion
    }
}
