/*****************************************
Table  Name:Brand
Create Time:2016/10/31 13:00:02
Creator    :jc001
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Brand
	/// This entiy code is generated by codesmith. this entity is Brand.
	/// </summary>
	[Serializable()]
	public class VWTreeCTModelEntity
    {
        #region Public Properties	

        public IList<string>  Capacitys;
        /// <summary>
        ///  
        /// <summary>
        public IList<string>  CarYears;
	 	 
         
        public IList<CarTypeModelEntity> Children;
      
        #endregion
    }
}
