 /*****************************************
Table  Name:CommentPic
Create Time:2016/9/22 11:08:08
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CommentPic
	/// This entiy code is generated by codesmith. this entity is CommentPic.
	/// </summary>
	[Serializable()]
	public class CommentPicEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 评论上传图片表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 图片路径
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}
        /// <summary>
		/// 图片路径
		/// <summary>
		private string _PicSuffix;
        public string PicSuffix
        {
            get
            {
                return _PicSuffix;
            }
            set
            {
                _PicSuffix = value;
            }
        }
        /// <summary>
        /// 品论Id
        /// <summary>
        private  int _CommentId;
	 	public int CommentId
		{
			get
			{
				return _CommentId;
			}
			set
			{
				_CommentId=value;
			}
		}

		#endregion				
	}
}
