 /*****************************************
Table  Name:StatisticCommentNum
Create Time:2016/11/11 23:30:56
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>StatisticCommentNum
	/// This entiy code is generated by codesmith. this entity is StatisticCommentNum.
	/// </summary>
	[Serializable()]
	public class StatisticCommentNumEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}

	    /// <summary>
		/// 款式Id
		/// <summary>
		private  int _StyleId;
	 	public int StyleId
		{
			get
			{
				return _StyleId;
			}
			set
			{
				_StyleId=value;
			}
		}
        /// <summary>
        /// 好评数
        /// <summary>
        private int _AllNum;
        public int AllNum
        {
            get
            {
                return _AllNum;
            }
            set
            {
                _AllNum = value;
            }
        }
        /// <summary>
        /// 好评数
        /// <summary>
        private  int _FavNum;
	 	public int FavNum
		{
			get
			{
				return _FavNum;
			}
			set
			{
				_FavNum=value;
			}
		}

	    /// <summary>
		/// 中评数
		/// <summary>
		private  int _GeneralNum;
	 	public int GeneralNum
		{
			get
			{
				return _GeneralNum;
			}
			set
			{
				_GeneralNum=value;
			}
		}

	    /// <summary>
		/// 差评数
		/// <summary>
		private  int _BadNum;
	 	public int BadNum
		{
			get
			{
				return _BadNum;
			}
			set
			{
				_BadNum=value;
			}
		}

        /// <summary>
        /// 好评数
        /// <summary>
        private int _FavRate;
        public int FavRate
        {
            get
            {
                return _FavRate;
            }
            set
            {
                _FavRate = value;
            }
        }

        /// <summary>
        /// 中评数
        /// <summary>
        private int _GeneralRate;
        public int GeneralRate
        {
            get
            {
                return _GeneralRate;
            }
            set
            {
                _GeneralRate = value;
            }
        }

        /// <summary>
        /// 差评数
        /// <summary>
        private int _BadRate;
        public int BadRate
        {
            get
            {
                return _BadRate;
            }
            set
            {
                _BadRate = value;
            }
        }
        /// 评论显示详情
        /// <summary>
        private string _CommentContent;
        public string CommentContent
        {
            get
            {
                return _CommentContent;
            }
            set
            {
                _CommentContent = value;
            }
        }
        
        #endregion
    }
}
