 /*****************************************
Table  Name:CGOrderSend
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderSend
	/// This entiy code is generated by codesmith. this entity is CGOrderSend.
	/// </summary>
	[Serializable()]
	public class VWCGOrderReturnEntity
    {
  
        private long _B2BOrderCode;
        public long B2BOrderCode
        {
            get
            {
                return _B2BOrderCode;
            }
            set
            {
                _B2BOrderCode = value;
            }
        }

        private long _CGOrderCode;
        public long CGOrderCode
        {
            get
            {
                return _CGOrderCode;
            }
            set
            {
                _CGOrderCode = value;
            }
        }

        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }

        private int _ProductId;
        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }

        private int _Num;
        public int Num
        {
            get
            {
                return _Num;
            }
            set
            {
                _Num = value;
            }
        }
        private int _ReturnNum;
        public int ReturnNum
        {
            get
            {
                return _ReturnNum;
            }
            set
            {
                _ReturnNum = value;
            }
        }

        private string _StoreName;
        public string StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                _StoreName = value;
            }
        }

        private string _ContactsManName;
        public string ContactsManName
        {
            get
            {
                return _ContactsManName;
            }
            set
            {
                _ContactsManName = value;
            }
        }

        private string _MobilePhone;
        public string MobilePhone
        {
            get
            {
                return _MobilePhone;
            }
            set
            {
                _MobilePhone = value;
            }
        }


        private string _Address;
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }


        private int _ProvinceId;
        public int ProvinceId
        {
            get
            {
                return _ProvinceId;
            }
            set
            {
                _ProvinceId = value;
            }
        }

        private int _CityId;
        public int CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                _CityId = value;
            }
        }





    }
}
