 /*****************************************
Table  Name:CGOrderOfferSub
Create Time:2017/2/5 18:00:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderOfferSub
	/// This entiy code is generated by codesmith. this entity is CGOrderOfferSub.
	/// </summary>
	[Serializable()]
	public class VWCGOrderOfferSubEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _OfferId;
	 	public int OfferId
		{
			get
			{
				return _OfferId;
			}
			set
			{
				_OfferId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _CGOrderCode;
	 	public Int64 CGOrderCode
		{
			get
			{
				return _CGOrderCode;
			}
			set
			{
				_CGOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private string _ProductName;
        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  decimal _CGPrice;
	 	public decimal CGPrice
		{
			get
			{
				return _CGPrice;
			}
			set
			{
				_CGPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}
        private int _Unit;
        public int Unit
        {
            get
            {
                return _Unit;
            }
            set
            {
                _Unit = value;
            }
        }
        private string _UnitName;
        public string UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                _UnitName = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  decimal _CGTotalPrice;
	 	public decimal CGTotalPrice
		{
			get
			{
				return _CGTotalPrice;
			}
			set
			{
				_CGTotalPrice=value;
			}
		}

        /// <summary>
        /// 产品图片路径
        /// <summary>
        private string _PicUrl;
        public string PicUrl
        {
            get
            {
                return _PicUrl;
            }
            set
            {
                _PicUrl = value;
            }
        }

        /// <summary>
        /// 图片后缀名
        /// <summary>
        private string _PicSuffix;
        public string PicSuffix
        {
            get
            {
                return _PicSuffix;
            }
            set
            {
                _PicSuffix = value;
            }
        }
        /// <summary>
        /// 产品名称
        /// <summary>
        private string _Name;
        public string Name
        {
            get
            {
                return _Name;
            }
            set
            {
                _Name = value;
            }
        }

        /// <summary>
        /// 产品标题全名
        /// <summary>
        private string _Title;
        public string Title
        {
            get
            {
                return _Title;
            }
            set
            {
                _Title = value;
            }
        }

        /// <summary>
        /// 产品选择项1
        /// <summary>
        private string _Spec1;
        public string Spec1
        {
            get
            {
                return _Spec1;
            }
            set
            {
                _Spec1 = value;
            }
        }

        /// <summary>
        /// 产品选择项2
        /// <summary>
        private string _Spec2;
        public string Spec2
        {
            get
            {
                return _Spec2;
            }
            set
            {
                _Spec2 = value;
            }
        }

        /// <summary>
        /// 产品选择项3
        /// <summary>
        private string _Spec3;
        public string Spec3
        {
            get
            {
                return _Spec3;
            }
            set
            {
                _Spec3 = value;
            }
        }
        #endregion
    }
}
