/*****************************************
Table  Name:CGOrderSend
Create Time:2016/12/31 9:41:06
Creator    :jc001
******************************************/
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGOrderSend
	/// This entiy code is generated by codesmith. this entity is CGOrderSend.
	/// </summary>
	[Serializable()]
	public class VWCGOrderEntity
    {
        #region Public Properties	
        /// <summary>
        /// 采购订单表
        /// <summary>
        private int _Id;
        public int Id
        {
            get
            {
                return _Id;
            }
            set
            {
                _Id = value;
            }
        }

        /// <summary>
        /// 订单编号
        /// <summary>
        private Int64 _Code;
        public Int64 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                _Code = value;
            }
        }

        /// <summary>
        /// 订单名称
        /// <summary>
        private string _Title;
        public string Title
        {
            get
            {
                return _Title;
            }
            set
            {
                _Title = value;
            }
        }

        /// <summary>
        /// 来源订单编号
        /// <summary>
        private Int64 _SourceCode;
        public Int64 SourceCode
        {
            get
            {
                return _SourceCode;
            }
            set
            {
                _SourceCode = value;
            }
        }

        /// <summary>
        /// 生成时间
        /// <summary>
        private DateTime _CreateTime;
        public DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                _CreateTime = value;
            }
        }

        /// <summary>
        /// 收货人姓名
        /// <summary>
        private string _ReceiptName;
        public string ReceiptName
        {
            get
            {
                return _ReceiptName;
            }
            set
            {
                _ReceiptName = value;
            }
        }

        /// <summary>
        /// 收货人所属省
        /// <summary>
        private int _ReceiptProvince;
        public int ReceiptProvince
        {
            get
            {
                return _ReceiptProvince;
            }
            set
            {
                _ReceiptProvince = value;
            }
        }
        private string _ReceiptProvinceName;
        public string ReceiptProvinceName
        {
            get
            {
                return _ReceiptProvinceName;
            }
            set
            {
                _ReceiptProvinceName = value;
            }
        }
        private string _ReceiptCityName;
        public string ReceiptCityName
        {
            get
            {
                return _ReceiptCityName ;
            }
            set
            {
                _ReceiptCityName  = value;
            }
        }
        /// <summary>
        /// 收货人所属城市
        /// <summary>
        private int _ReceiptCity;
        public int ReceiptCity
        {
            get
            {
                return _ReceiptCity;
            }
            set
            {
                _ReceiptCity = value;
            }
        }

        /// <summary>
        /// 收货人所在县
        /// <summary>
        private int _ReceiptTown;
        public int ReceiptTown
        {
            get
            {
                return _ReceiptTown;
            }
            set
            {
                _ReceiptTown = value;
            }
        }

        /// <summary>
        /// 收货人具体地址
        /// <summary>
        private string _ReceiptAddress;
        public string ReceiptAddress
        {
            get
            {
                return _ReceiptAddress;
            }
            set
            {
                _ReceiptAddress = value;
            }
        }

        /// <summary>
        /// 收货人手机号码
        /// <summary>
        private string _ReceiptPhone;
        public string ReceiptPhone
        {
            get
            {
                return _ReceiptPhone;
            }
            set
            {
                _ReceiptPhone = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private decimal _TransFee;
        public decimal TransFee
        {
            get
            {
                return _TransFee;
            }
            set
            {
                _TransFee = value;
            }
        }

        /// <summary>
        /// 状态：0待报价：1第一轮报价，2第二轮报价，3第三轮报价,4进入线下客服处理流程，11已派单,12供应商已打印发货单，13供应商已发货，14供应商上传客户收货凭证，15送货完成，21财务批准打款，22款已支付，31订单取消，32已退货，99订单关闭
        /// <summary>
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        public string StatusName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((CGOrderStatus)Status);
            }
        }
     
          

        /// <summary>
        /// 发送报价时间
        /// <summary>
        private DateTime _SendTime;
        public DateTime SendTime
        {
            get
            {
                return _SendTime;
            }
            set
            {
                _SendTime = value;
            }
        }

        /// <summary>
        /// 备注
        /// <summary>
        private string _Remark;
        public string Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                _Remark = value;
            }
        }
        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }

        private int _ExpressCom;
        public int ExpressCom
        {
            get
            {
                return _ExpressCom;
            }
            set
            {
                _ExpressCom = value;
            }
        }
        public string  ExpressComName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((WLComPany)ExpressCom);
            }

        }
        public IList<CGOrderDetailEntity> OrderDetails
        {
            get;
            set;
        }

        #endregion
    }
}
