 /*****************************************
Table  Name:ConfirmOrder
Create Time:2017/10/12 14:15:16
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ConfirmOrder
	/// This entiy code is generated by codesmith. this entity is ConfirmOrder.
	/// </summary>
	[Serializable()]
	public class ConfirmOrderEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 询价订单记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 订单编号
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}
        /// <summary>
        /// 询价订单编号
        /// <summary>
        private string _InquiryOrderCode;
        public string InquiryOrderCode
        {
            get
            {
                return _InquiryOrderCode;
            }
            set
            {
                _InquiryOrderCode = value;
            }
        }
        /// <summary>
        /// Vin码
        /// <summary>
        private  string _VinNo;
	 	public string VinNo
		{
			get
			{
				return _VinNo;
			}
			set
			{
				_VinNo=value;
			}
		}

	    /// <summary>
		/// 车架号照片
		/// <summary>
		private  string _VinPic;
	 	public string VinPic
		{
			get
			{
				return _VinPic;
			}
			set
			{
				_VinPic=value;
			}
		}
        /// <summary>
        /// 发动机编号
        /// </summary>
        private string _EngineModelNo;
        public string EngineModelNo
        {
            get
            {
                return _EngineModelNo;
            }
            set
            {
                _EngineModelNo = value;
            }
        }

        /// <summary>
        /// 发动机照片
        /// <summary>
        private string _EngineModelPic;
        public string EngineModelPic
        {
            get
            {
                return _EngineModelPic;
            }
            set
            {
                _EngineModelPic = value;
            }
        }
        /// <summary>
        /// 车型品牌Id
        /// <summary>
        private  int _CarBrandId;
	 	public int CarBrandId
		{
			get
			{
				return _CarBrandId;
			}
			set
			{
				_CarBrandId=value;
			}
		}

	    /// <summary>
		/// 车型品牌名称
		/// <summary>
		private  string _CarBrandName;
	 	public string CarBrandName
		{
			get
			{
				return _CarBrandName;
			}
			set
			{
				_CarBrandName=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CarSeriesId;
	 	public int CarSeriesId
		{
			get
			{
				return _CarSeriesId;
			}
			set
			{
				_CarSeriesId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarSeriesName;
	 	public string CarSeriesName
		{
			get
			{
				return _CarSeriesName;
			}
			set
			{
				_CarSeriesName=value;
			}
		}

	    /// <summary>
		/// 车型匹配Id
		/// <summary>
		private  int _CarTypeModelId;
	 	public int CarTypeModelId
		{
			get
			{
				return _CarTypeModelId;
			}
			set
			{
				_CarTypeModelId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CarTypeModelName;
	 	public string CarTypeModelName
		{
			get
			{
				return _CarTypeModelName;
			}
			set
			{
				_CarTypeModelName=value;
			}
		}

	    /// <summary>
		/// 备注
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

	    /// <summary>
		/// 要货时间，0很急，1今天到，2明天到，3后天到 
		/// <summary>
		private  int _NeedDay;
	 	public int NeedDay
		{
			get
			{
				return _NeedDay;
			}
			set
			{
				_NeedDay=value;
			}
		}
        private int _WLMemId;
        public int WLMemId
        {
            get
            {
                return _WLMemId;
            }
            set
            {
                _WLMemId = value;
            }
        }
        /// <summary>
        /// 物流送货备注
        /// <summary>
        private  string _WLRemark;
	 	public string WLRemark
		{
			get
			{
				return _WLRemark;
			}
			set
			{
				_WLRemark=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _CGTotalPrice;
	 	public decimal CGTotalPrice
		{
			get
			{
				return _CGTotalPrice;
			}
			set
			{
				_CGTotalPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _TotalPrice;
	 	public decimal TotalPrice
		{
			get
			{
				return _TotalPrice;
			}
			set
			{
				_TotalPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}
         

        /// <summary>
        /// 提交人Id
        /// <summary>
        private int _CreateManId;
	 	public int CreateManId
		{
			get
			{
				return _CreateManId;
			}
			set
			{
				_CreateManId=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 订单状态明细 1用户提交，2接洽员审核，3供应商报价，4销售价格审核，5用户确认订单，6物流配送完成，7已派送供应商供报价，8已选择供应商，99订单关闭
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

	    /// <summary>
		/// 取消原因
		/// <summary>
		private  int _CancelReasonId;
	 	public int CancelReasonId
		{
			get
			{
				return _CancelReasonId;
			}
			set
			{
				_CancelReasonId=value;
			}
		}

	    /// <summary>
		/// 取消说明
		/// <summary>
		private  string _CancelRemark;
	 	public string CancelRemark
		{
			get
			{
				return _CancelRemark;
			}
			set
			{
				_CancelRemark=value;
			}
		}
        private int _ScopeType;
        public int ScopeType
        {
            get
            {
                return _ScopeType;
            }
            set
            {
                _ScopeType = value;
            }
        }
        #endregion
    }
}
