 /*****************************************
Table  Name:InquiryOrderFeedBack
Create Time:2017/10/14 15:02:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InquiryOrderFeedBack
	/// This entiy code is generated by codesmith. this entity is InquiryOrderFeedBack.
	/// </summary>
	[Serializable()]
	public class InquiryOrderFeedBackEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 用户询价单反馈记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 询价单编号
		/// <summary>
		private  string _InquiryOrderCode;
	 	public string InquiryOrderCode
		{
			get
			{
				return _InquiryOrderCode;
			}
			set
			{
				_InquiryOrderCode=value;
			}
		}

	    /// <summary>
		/// 反馈原因Id
		/// <summary>
		private  int _FeedBackReasonId;
	 	public int FeedBackReasonId
		{
			get
			{
				return _FeedBackReasonId;
			}
			set
			{
				_FeedBackReasonId=value;
			}
		}
        public string FeedBackReasonName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((InquiryOrderFeedBackEnum)FeedBackReasonId);
            }
        }
        
        /// <summary>
        /// 备注
        /// <summary>
        private  string _FeedBackRemark;
	 	public string FeedBackRemark
		{
			get
			{
				return _FeedBackRemark;
			}
			set
			{
				_FeedBackRemark=value;
			}
		}

	    /// <summary>
		/// 反馈时间
		/// <summary>
		private  DateTime _FeedBackTime;
	 	public DateTime FeedBackTime
		{
			get
			{
				return _FeedBackTime;
			}
			set
			{
				_FeedBackTime=value;
			}
		}

	    /// <summary>
		/// 用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		#endregion				
	}
}
