 /*****************************************
Table  Name:InquiryProductSub
Create Time:2017/8/26 21:30:28
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InquiryProductSub
	/// This entiy code is generated by codesmith. this entity is InquiryProductSub.
	/// </summary>
	[Serializable()]
	public class InquiryProductSubEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}
        
        /// <summary>
        /// 
        /// <summary>
        private string _InquiryOrderCode;
        public string InquiryOrderCode
        {
            get
            {
                return _InquiryOrderCode;
            }
            set
            {
                _InquiryOrderCode = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private  int _InquiryProductId;
	 	public int InquiryProductId
		{
			get
			{
				return _InquiryProductId;
			}
			set
			{
				_InquiryProductId=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private int _CreateManId;
        public int CreateManId
        {
            get
            {
                return _CreateManId;
            }
            set
            {
                _CreateManId = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private DateTime _CreateTime;
        public DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                _CreateTime = value;
            }
        }

        /// <summary>
        /// 
        /// <summary>
        private int _InquiryProductType;
	 	public int InquiryProductType
		{
			get
			{
				return _InquiryProductType;
			}
			set
			{
				_InquiryProductType=value;
			}
		} 
        public string InquiryProductTypeName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((InquiryProductTypeEnum)InquiryProductType);
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private decimal _Price;
        public decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                _Price = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private string _Remark;
        public string Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                _Remark = value;
            }
        }
        private int _HasStock;
        public int HasStock
        {
            get
            {
                return _HasStock;
            }
            set
            {
                _HasStock = value;
            }
        }
        #endregion
    }
}
