 /*****************************************
Table  Name:InquiryOrderPics
Create Time:2017/8/23 11:12:19
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InquiryOrderPics
	/// This entiy code is generated by codesmith. this entity is InquiryOrderPics.
	/// </summary>
	[Serializable()]
	public class InquiryOrderPicsEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 询价订单图片记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 询价订单编号
		/// <summary>
		private  string _InquiryOrderCode;
	 	public string InquiryOrderCode
		{
			get
			{
				return _InquiryOrderCode;
			}
			set
			{
				_InquiryOrderCode=value;
			}
		}

	    /// <summary>
		/// 图片路径
		/// <summary>
		private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
