 /*****************************************
Table  Name:InquiryOrderMember
Create Time:2017/8/23 11:12:19
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InquiryOrderMember
	/// This entiy code is generated by codesmith. this entity is InquiryOrderMember.
	/// </summary>
	[Serializable()]
	public class InquiryOrderMemberEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 询价人记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 询价订单编号
		/// <summary>
		private  string _InquiryOrderCode;
	 	public string InquiryOrderCode
		{
			get
			{
				return _InquiryOrderCode;
			}
			set
			{
				_InquiryOrderCode=value;
			}
		}

	    /// <summary>
		/// 如果注册，订购用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 人员名
		/// <summary>
		private  string _MemName;
	 	public string MemName
		{
			get
			{
				return _MemName;
			}
			set
			{
				_MemName=value;
			}
		}

	    /// <summary>
		/// 联系手机
		/// <summary>
		private  string _MemPhone;
	 	public string MemPhone
		{
			get
			{
				return _MemPhone;
			}
			set
			{
				_MemPhone=value;
			}
		}

	    /// <summary>
		/// 地址
		/// <summary>
		private  string _CompanyAddress;
	 	public string CompanyAddress
		{
			get
			{
				return _CompanyAddress;
			}
			set
			{
				_CompanyAddress=value;
			}
		}

	    /// <summary>
		/// 公司名称
		/// <summary>
		private  string _CompanyName;
	 	public string CompanyName
		{
			get
			{
				return _CompanyName;
			}
			set
			{
				_CompanyName=value;
			}
		}

		#endregion				
	}
}
