 /*****************************************
Table  Name:InQuiryOrderFlow
Create Time:2017/8/23 11:12:18
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InQuiryOrderFlow
	/// This entiy code is generated by codesmith. this entity is InQuiryOrderFlow.
	/// </summary>
	[Serializable()]
	public class InQuiryOrderFlowEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 订单流转记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 订单编号
		/// <summary>
		private  string _InquiryOrderCode;
	 	public string InquiryOrderCode
		{
			get
			{
				return _InquiryOrderCode;
			}
			set
			{
				_InquiryOrderCode=value;
			}
		}

	    /// <summary>
		/// 备注说明
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

	    /// <summary>
		/// 操作名称
		/// <summary>
		private  string _MethodName;
	 	public string MethodName
		{
			get
			{
				return _MethodName;
			}
			set
			{
				_MethodName=value;
			}
		}

	    /// <summary>
		/// 操作人Id
		/// <summary>
		private  int _CreateManId;
	 	public int CreateManId
		{
			get
			{
				return _CreateManId;
			}
			set
			{
				_CreateManId=value;
			}
		}

	    /// <summary>
		/// 操作时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
