 /*****************************************
Table  Name:CGProductStock
Create Time:2017/1/17 11:52:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CGProductStock
	/// This entiy code is generated by codesmith. this entity is CGProductStock.
	/// </summary>
	[Serializable()]
	public class VWCGProductStockEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
        }  /// <summary>
           /// 
           /// <summary>
        private string _ProductCode;
        public string ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                _ProductCode = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private string _ProductSelfName;
        public string ProductSelfName
        {
            get
            {
                return _ProductSelfName;
            }
            set
            {
                _ProductSelfName = value;
            }
        }


        /// <summary>
        /// 采购价格
        /// <summary>
        private decimal _SuggestPrice;
	 	public decimal SuggestPrice
		{
			get
			{
				return _SuggestPrice;
			}
			set
			{
				_SuggestPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _StockNum;
	 	public int StockNum
		{
			get
			{
				return _StockNum;
			}
			set
			{
				_StockNum=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
        public VWProductEntity Product;
         
		#endregion				
	}
}
