 /*****************************************
Table  Name:ConfirmOrderCGMem
Create Time:2017/10/18 16:28:51
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ConfirmOrderCGMem
	/// This entiy code is generated by codesmith. this entity is ConfirmOrderCGMem.
	/// </summary>
	[Serializable()]
	public class VWConfirmOrderCGMemEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 确认订单编号
		/// <summary>
		private  string _ConfirmOrderCode;
	 	public string ConfirmOrderCode
		{
			get
			{
				return _ConfirmOrderCode;
			}
			set
			{
				_ConfirmOrderCode=value;
			}
		}

	    /// <summary>
		/// 供应商Id
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  decimal _CGTotalPrice;
	 	public decimal CGTotalPrice
		{
			get
			{
				return _CGTotalPrice;
			}
			set
			{
				_CGTotalPrice=value;
			}
		}

	    /// <summary>
		/// 选择时间
		/// <summary>
		private  DateTime _SelectTime;
	 	public DateTime SelectTime
		{
			get
			{
				return _SelectTime;
			}
			set
			{
				_SelectTime=value;
			}
		}
        
        private int _HasInStock;
        public int HasInStock
        {
            get
            {
                return _HasInStock;
            }
            set
            {
                _HasInStock = value;
            }
        }
        public string InStockName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((QuoteInStock)HasInStock);
            }
        }
        private string _RemarkByCGMem;
        public string RemarkByCGMem
        {
            get
            {
                return _RemarkByCGMem;
            }
            set
            {
                _RemarkByCGMem = value;
            }
        }
        public VWMemberEntity member;
		#endregion				
	}
}
