 /*****************************************
Table  Name:InquiryProduct
Create Time:2017/8/23 11:12:19
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text;
using System.Collections.Generic;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>InquiryProduct
	/// This entiy code is generated by codesmith. this entity is InquiryProduct.
	/// </summary>
	[Serializable()]
	public class VWInquiryProductEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 询价产品记录
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 询价订单编号
		/// <summary>
		private  string _InquiryOrderCode;
	 	public string InquiryOrderCode
		{
			get
			{
				return _InquiryOrderCode;
			}
			set
			{
				_InquiryOrderCode=value;
			}
		}

	    /// <summary>
		/// 产品编码
		/// <summary>
		private  string _ProductCode;
	 	public string ProductCode
		{
			get
			{
				return _ProductCode;
			}
			set
			{
				_ProductCode=value;
			}
		}

	    /// <summary>
		/// 产品对应所属元器件Id
		/// <summary>
		private  int _ClassesId;
	 	public int ClassesId
		{
			get
			{
				return _ClassesId;
			}
			set
			{
				_ClassesId=value;
			}
		}
        /// <summary>
        /// 产品对应所属元器件Id
        /// <summary>
        private string _ClassesName;
        public string ClassesName
        {
            get
            {
                return _ClassesName;
            }
            set
            {
                _ClassesName = value;
            }
        }
        /// <summary>
        /// 产品名称
        /// <summary>
        private int _ProductId;
        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }
        /// <summary>
        /// 产品名称
        /// <summary>
        private  string _ProductName;
	 	public string ProductName
		{
			get
			{
				return _ProductName;
			}
			set
			{
				_ProductName=value;
			}
		}

	    /// <summary>
		/// 数量
		/// <summary>
		private  int _ProductNum;
	 	public int ProductNum
		{
			get
			{
				return _ProductNum;
			}
			set
			{
				_ProductNum=value;
			}
		}

	    /// <summary>
		/// 单位
		/// <summary>
		private  string _ProductUnitName;
	 	public string ProductUnitName
		{
			get
			{
				return _ProductUnitName;
			}
			set
			{
				_ProductUnitName=value;
			}
		}

	    /// <summary>
		/// 备注
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}
        public IList<InquiryProductSubEntity> ProductSubList;
         
		#endregion				
	}
}
