 /*****************************************
Table  Name:Member
Create Time:2016/8/8 15:27:40
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Member
	/// This entiy code is generated by codesmith. this entity is Member.
	/// </summary> 
	public partial class MemberEntity
	{
        // 账号
        public string MemGradeName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((MemberGrade)MemGrade);
            }
        }
    }
}
