 /*****************************************
Table  Name:CacheConfig
Create Time:2016/7/30 10:41:22
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>CacheConfig
	/// This entiy code is generated by codesmith. this entity is CacheConfig.
	/// </summary>
	[Serializable()]
	public class CacheConfigEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 缓存键值
	 	public string CacheKey
		{
			get;
			set;
		}

		// 版本
	 	public int Version
		{
			get;
			set;
		}

		// 建立时间
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		// 修改时间
	 	public DateTime UpdateTime
		{
			get;
			set;
		}

		// 修改人
	 	public int UpdateMan
		{
			get;
			set;
		}

		// 备注
	 	public string Remark
		{
			get;
			set;
		}

		// 是否有扩展缓存
	 	public int HasExpend
		{
			get;
			set;
		}

		// 是否有效
	 	public int IsActive
		{
			get;
			set;
		}

		// 失效时间
	 	public DateTime DisableTime
		{
			get;
			set;
		}

		#endregion				
	}
}
