 /*****************************************
Table  Name:ConfigPicComPress
Create Time:2018/4/17 23:52:20
Creator    :lgzh
******************************************/
using System;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ConfigPicComPress
	/// This entiy code is generated by codesmith. this entity is ConfigPicComPress.
	/// </summary>
	[Serializable()]
	public class ConfigPicComPressEntity
	{
	    #region Public Properties	
		// 记录压缩图片格式
	 	public int Id
		{
			get;
			set;
		}

		// 
	 	public string Title
		{
			get;
			set;
		}

		// 
	 	public int Width
		{
			get;
			set;
		}

		// 
	 	public int Height
		{
			get;
			set;
		}

		// 压缩后的图片名称
	 	public string PicName
		{
			get;
			set;
		}

		// 压缩后的图片名称类型1名称为原始名+picname，2名称为图片名picname
	 	public int PicNameType
		{
			get;
			set;
		}

		// 来源图片，1产品图，2。。。
	 	public int SourcePicType
		{
			get;
			set;
		}

		// 
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		#endregion				
	}
}
