 /*****************************************
Table  Name:DicEnum
Create Time:2016/7/14 17:40:08
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model 
{
    /// <summary>DicEnum
    /// This entiy code is generated by codesmith. this entity is DicEnum.
    /// </summary> 
    [Serializable()]
    public class DicEnumEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}
       
		// 编号，键值，与程序呼应
	 	public string Code 
		{
			get;
			set;
		}

		// 名称
	 	public string Name
		{
			get;
			set;
		}

		// 说明
	 	public string Description
		{
			get;
			set;
		}

		// 上级编号
	 	public string ParentCode
		{
			get;
			set;
		}

		// 上级id
	 	public int ParentId
		{
			get;
			set;
		}
        // 上级id
        public int ParentId1
        {
            get;
            set;
        }
        // 上级id
        public int ParentId2
        {
            get;
            set;
        }
        // 上级id
        public int ParentId3
        {
            get;
            set;
        }
        private int _IsActive = 1;
        // 是否有效
        public int IsActive
		{
            get { return _IsActive; }
            set { _IsActive = value; }
        }
        //public bool IsActiveB
        //{
        //    get { return IsActive == 1; }
        //    set { IsActive = value ? 1 : 0; }
        //}
        // 建立时间
        public DateTime CreateTime
		{
			get;
			set;
		}

		// 建立人员
	 	public int CreateMan
		{
			get;
			set;
		}

        private int _CanEdit =1;
        // 是否可编辑
        public int CanEdit
		{
            get { return _CanEdit;  }
            set { _CanEdit = value; }
        }
        //public bool CanEditB
        //{
        //    get { return CanEdit == 1; }
        //    set { CanEdit = value ? 1 : 0; }
        //}
        #endregion
    }
}
