 /*****************************************
Table  Name:GYProvince
Create Time:2016/7/30 10:41:22
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>GYProvince
	/// This entiy code is generated by codesmith. this entity is GYProvince.
	/// </summary>
	[Serializable()]
	public class GYProvinceEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 省编号（内部）
	 	public string Code
		{
			get;
			set;
		}

		// 省名称
	 	public string Name
		{
			get;
			set;
		}

		// 全名
	 	public string FullName
		{
			get;
			set;
		}

		// 国家编号（默认中国）
	 	public string ParentCode
		{
			get;
			set;
		}

		// 
	 	public int IsActive
		{
			get;
			set;
		}

		// 拼音首字母
	 	public string PYFirst
		{
			get;
			set;
		}

		// 拼音全拼
	 	public string PYFull
		{
			get;
			set;
		}

        // 失效时间
      public DateTime DisableTime
        {
            get;
            set;
        }
        // 失效时间
        public int Sort
        {
            get;
            set;
        }

        #endregion
    }
}
