 /*****************************************
Table  Name:GYRole
Create Time:2016/7/30 10:41:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>GYRole
	/// This entiy code is generated by codesmith. this entity is GYRole.
	/// </summary>
	[Serializable()]
	public class GYRoleEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 角色编号
	 	public string Code
		{
			get;
			set;
		}

		// 角色名称
	 	public string Name
		{
			get;
			set;
		}

		// 是否有效
	 	public int IsActive
		{
			get;
			set;
		}

		#endregion				
	}
}
