 /*****************************************
Table  Name:GYRoleAuth
Create Time:2016/7/30 10:41:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>GYRoleAuth
	/// This entiy code is generated by codesmith. this entity is GYRoleAuth.
	/// </summary>
	[Serializable()]
	public class GYRoleAuthEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 角色Id
	 	public int RoleId
		{
			get;
			set;
		}

		// 权限Id
	 	public int AuthId
		{
			get;
			set;
		}

		#endregion				
	}
}
