 /*****************************************
Table  Name:SysUser
Create Time:2016/7/30 10:41:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SysUser
	/// This entiy code is generated by codesmith. this entity is SysUser.
	/// </summary>
	[Serializable()]
	public class SysUserEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 用户编码
	 	public string UserCode
		{
			get;
			set;
		}

		// 用户名
	 	public string UserName
		{
			get;
			set;
		}

		// 密码
	 	public string PassWord
		{
			get;
			set;
		}

		// 是否有效
	 	public int IsActive
		{
			get;
			set;
		}

		// 
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		// 用户等级
	 	public int UserLevel
		{
			get;
			set;
		}

		#endregion				
	}
}
