 /*****************************************
Table  Name:WeChatNavigation
Create Time:2017/8/16 16:21:37
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WeChatNavigation
	/// This entiy code is generated by codesmith. this entity is WeChatNavigation.
	/// </summary>
	[Serializable()]
	public class WeChatNavigationEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 微信链接导航记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 导航关键词（可以在代码做枚举），不能重复
		/// <summary>
		private  int _WeChatNavCode;
	 	public int WeChatNavCode
		{
			get
			{
				return _WeChatNavCode;
			}
			set
			{
				_WeChatNavCode=value;
			}
		}

	    /// <summary>
		/// 导出的链接地址
		/// <summary>
		private  string _RedirectUrl;
	 	public string RedirectUrl
		{
			get
			{
				return _RedirectUrl;
			}
			set
			{
				_RedirectUrl=value;
			}
		}
        /// <summary>
        /// 导出的链接地址
        /// <summary>
        private string _WeChatUrl;
        public string WeChatUrl
        {
            get
            {
                return _WeChatUrl;
            }
            set
            {
                _WeChatUrl = value;
            }
        }

        /// <summary>
        /// 备注说明
        /// <summary>
        private string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}
        /// <summary>
        /// 导航类型
        /// <summary>
        private int _WeChatUrlType;
        public int WeChatUrlType
        {
            get
            {
                return _WeChatUrlType;
            }
            set
            {
                _WeChatUrlType = value;
            }
        }
        public string WeChatUrlTypeName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((WeChatUrTypeEnum)WeChatUrlType);
            }

        }
        #endregion
    }
}
