 /*****************************************
Table  Name:XTCode
Create Time:2016/7/30 10:41:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>XTCode
	/// This entiy code is generated by codesmith. this entity is XTCode.
	/// </summary>
	[Serializable()]
	public class XTCodeEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 编码唯一
	 	public string Code
		{
			get;
			set;
		}

		// 名称说明
	 	public string Name
		{
			get;
			set;
		}

		// 是否需要前缀
	 	public int HasPre
		{
			get;
			set;
		}

		// 
	 	public int NeedDate
		{
			get;
			set;
		}

		// 占几位数字
	 	public int NumLen
		{
			get;
			set;
		}

		// 填充字符
	 	public string FillChar
		{
			get;
			set;
		}

		#endregion				
	}
}
