 /*****************************************
Table  Name:XTCodeNum
Create Time:2016/7/30 10:41:23
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>XTCodeNum
	/// This entiy code is generated by codesmith. this entity is XTCodeNum.
	/// </summary>
	[Serializable()]
	public class XTCodeNumEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 编码外键
	 	public int CodeId
		{
			get;
			set;
		}

		// 前缀
	 	public string PreFix
		{
			get;
			set;
		}

		// 日期
	 	public DateTime DateFix
		{
			get;
			set;
		}

		// 最大数字
	 	public Int64 Number
		{
			get;
			set;
		}

		#endregion				
	}
}
