 /*****************************************
Table  Name:Asset
Create Time:2016/8/7 17:48:07
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Asset
	/// This entiy code is generated by codesmith. this entity is Asset.
	/// </summary>
	[Serializable()]
	public class AssetEntity
	{
	    #region Public Properties	
		// 资产记录表
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 客户ID
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		// 余额
		private  decimal _BalanceAMT;
	 	public decimal BalanceAMT
		{
			get
			{
				return _BalanceAMT;
			}
			set
			{
				_BalanceAMT=value;
			}
		}

		// 可用积分
		private  int _AvailableIntegral;
	 	public int AvailableIntegral
		{
			get
			{
				return _AvailableIntegral;
			}
			set
			{
				_AvailableIntegral=value;
			}
		}

		// 冻结积分
		private  int _FreezingIntegral;
	 	public int FreezingIntegral
		{
			get
			{
				return _FreezingIntegral;
			}
			set
			{
				_FreezingIntegral=value;
			}
		}

		// 冻结金额
		private  decimal _FreezingAMT;
	 	public decimal FreezingAMT
		{
			get
			{
				return _FreezingAMT;
			}
			set
			{
				_FreezingAMT=value;
			}
		}

		// 账户状态0无效1有效
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
