 /*****************************************
Table  Name:AssetWithdraw
Create Time:2016/8/4 11:01:53
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>AssetWithdraw
	/// This entiy code is generated by codesmith. this entity is AssetWithdraw.
	/// </summary>
	[Serializable()]
	public class AssetWithdrawEntity
	{
	    #region Public Properties	
		// 提现记录表
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 客户ID
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		// 提现金额
		private  decimal _Amt;
	 	public decimal Amt
		{
			get
			{
				return _Amt;
			}
			set
			{
				_Amt=value;
			}
		}

		// 手续费
		private  decimal _CounterFee;
	 	public decimal CounterFee
		{
			get
			{
				return _CounterFee;
			}
			set
			{
				_CounterFee=value;
			}
		}

		// 提现方式（1支付宝，2银联，3微信红包）
		private  int _DrawType;
	 	public int DrawType
		{
			get
			{
				return _DrawType;
			}
			set
			{
				_DrawType=value;
			}
		}

		// 1待审核，2.审核通过，3,已提现
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		// 申请时间
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		// 实际提现时间
		private  DateTime _DrawTime;
	 	public DateTime DrawTime
		{
			get
			{
				return _DrawTime;
			}
			set
			{
				_DrawTime=value;
			}
		}

		// 交易序列号-银行提供
		private  string _TranSerialNum;
	 	public string TranSerialNum
		{
			get
			{
				return _TranSerialNum;
			}
			set
			{
				_TranSerialNum=value;
			}
		}

		// 银行卡号/支付宝账号/微信账号
		private  string _CardNo;
	 	public string CardNo
		{
			get
			{
				return _CardNo;
			}
			set
			{
				_CardNo=value;
			}
		}

		// 银行编码
		private  string _BankCode;
	 	public string BankCode
		{
			get
			{
				return _BankCode;
			}
			set
			{
				_BankCode=value;
			}
		}

		// 开户行
		private  string _BankName;
	 	public string BankName
		{
			get
			{
				return _BankName;
			}
			set
			{
				_BankName=value;
			}
		}

		// 开户行支行
		private  string _BankSubName;
	 	public string BankSubName
		{
			get
			{
				return _BankSubName;
			}
			set
			{
				_BankSubName=value;
			}
		}

		// 银行卡客户姓名，与MemberName一致
		private  string _CardName;
	 	public string CardName
		{
			get
			{
				return _CardName;
			}
			set
			{
				_CardName=value;
			}
		}

		// 手机通知号码
		private  string _MobilePhone;
	 	public string MobilePhone
		{
			get
			{
				return _MobilePhone;
			}
			set
			{
				_MobilePhone=value;
			}
		}

		#endregion				
	}
}
