 /*****************************************
Table  Name:FinanceRefund
Create Time:2017/1/16 12:07:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>FinanceRefund
	/// This entiy code is generated by codesmith. this entity is FinanceRefund.
	/// </summary>
	[Serializable()]
	public class FinanceRefundEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 订单编号,可重复
		/// <summary>
		private  Int64 _OrderCode;
	 	public Int64 OrderCode
		{
			get
			{
				return _OrderCode;
			}
			set
			{
				_OrderCode=value;
			}
		}

	    /// <summary>
		/// 支付交易编号
		/// <summary>
		private  string _PayTradeNo;
	 	public string PayTradeNo
		{
			get
			{
				return _PayTradeNo;
			}
			set
			{
				_PayTradeNo=value;
			}
		}

	    /// <summary>
		/// 退款金额,单次
		/// <summary>
		private  decimal _RebackFee;
	 	public decimal RebackFee
		{
			get
			{
				return _RebackFee;
			}
			set
			{
				_RebackFee=value;
			}
		}
        private decimal _ActRebackFee;
        public decimal ActRebackFee
        {
            get
            {
                return _ActRebackFee;
            }
            set
            {
                _ActRebackFee = value;
            }
        }
        //可退积分
        private int _ReBackIntegral;
        public int ReBackIntegral
        {
            get
            {
                return _ReBackIntegral;
            }
            set
            {
                _ReBackIntegral = value;
            }
        }
        private int _IntegralStatus;
        public int IntegralStatus
        {
            get
            {
                return _IntegralStatus;
            }
            set
            {
                _IntegralStatus = value;
            }
        }
        //已退积分
        private int _ActReBackIntegral;
        public int ActReBackIntegral
        {
            get
            {
                return _ActReBackIntegral;
            }
            set
            {
                _ActReBackIntegral = value;
            }
        }
        
        /// <summary>
        /// 退款说明
        /// <summary>
        private string _Description;
	 	public string Description
		{
			get
			{
				return _Description;
			}
			set
			{
				_Description=value;
			}
		}

	    /// <summary>
		/// 申请时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 退款状态
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

	    /// <summary>
		/// 财务退款时间
		/// <summary>
		private  DateTime _FinanceDealTime;
	 	public DateTime FinanceDealTime
		{
			get
			{
				return _FinanceDealTime;
			}
			set
			{
				_FinanceDealTime=value;
			}
		}

	    /// <summary>
		/// 处理人员
		/// <summary>
		private  int _DealManId;
	 	public int DealManId
		{
			get
			{
				return _DealManId;
			}
			set
			{
				_DealManId=value;
			}
		}

        /// <summary>
        /// 处理人员
        /// <summary>
        private int _ReturnXSId;
        public int ReturnXSId
        {
            get
            {
                return _ReturnXSId;
            }
            set
            {
                _ReturnXSId = value;
            }
        }
        

        #endregion
    }
}
