 /*****************************************
Table  Name:IntegralChange
Create Time:2016/12/1 14:30:50
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>IntegralChange
	/// This entiy code is generated by codesmith. this entity is IntegralChange.
	/// </summary>
	[Serializable()]
	public class IntegralChangeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 积分变动记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 人员Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 积分变动数量，增加为正值，减少为负值
		/// <summary>
		private  int _ChangeNum;
	 	public int ChangeNum
		{
			get
			{
				return _ChangeNum;
			}
			set
			{
				_ChangeNum=value;
			}
		}

	    /// <summary>
		/// 积分余额变动值
		/// <summary>
		private  int _BalanceChangeNum;
	 	public int BalanceChangeNum
		{
			get
			{
				return _BalanceChangeNum;
			}
			set
			{
				_BalanceChangeNum=value;
			}
		}

	    /// <summary>
		/// 可用积分变动值
		/// <summary>
		private  int _AvailableChangeNum;
	 	public int AvailableChangeNum
		{
			get
			{
				return _AvailableChangeNum;
			}
			set
			{
				_AvailableChangeNum=value;
			}
		}

	    /// <summary>
		/// 冻结积分变动值
		/// <summary>
		private  int _FreezingChangeNum;
	 	public int FreezingChangeNum
		{
			get
			{
				return _FreezingChangeNum;
			}
			set
			{
				_FreezingChangeNum=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _ChangeType;
	 	public int ChangeType
		{
			get
			{
				return _ChangeType;
			}
			set
			{
				_ChangeType=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _ChangeReason;
	 	public string ChangeReason
		{
			get
			{
				return _ChangeReason;
			}
			set
			{
				_ChangeReason=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _ChangeTime;
	 	public DateTime ChangeTime
		{
			get
			{
				return _ChangeTime;
			}
			set
			{
				_ChangeTime=value;
			}
		}

		#endregion				
	}
}
