 /*****************************************
Table  Name:Integral
Create Time:2016/12/1 14:30:50
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Integral
	/// This entiy code is generated by codesmith. this entity is Integral.
	/// </summary>
	[Serializable()]
	public class IntegralEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 用户积分记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 可用积分
		/// <summary>
		private  int _AvailableIntegral;
	 	public int AvailableIntegral
		{
			get
			{
				return _AvailableIntegral;
			}
			set
			{
				_AvailableIntegral=value;
			}
		}

	    /// <summary>
		/// 当前冻结积分
		/// <summary>
		private  int _FreezingIntegral;
	 	public int FreezingIntegral
		{
			get
			{
				return _FreezingIntegral;
			}
			set
			{
				_FreezingIntegral=value;
			}
		}

	    /// <summary>
		/// 状态
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
        /// <summary>
        /// 状态
        /// <summary>
        private string _TimeStrampCode;
        public string TimeStrampCode
        {
            get
            {
                return _TimeStrampCode;
            }
            set
            {
                _TimeStrampCode = value;
            }
        }
        #endregion
    }
}
