 /*****************************************
Table  Name:Coupons
Create Time:2017/3/25 18:44:10
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Coupons
	/// This entiy code is generated by codesmith. this entity is Coupons.
	/// </summary>
	[Serializable()]
	public class MemCouponsEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 会员优惠券记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 优惠券ID
		/// <summary>
		private  int _CouponsId;
	 	public int CouponsId
		{
			get
			{
				return _CouponsId;
			}
			set
			{
				_CouponsId=value;
			}
		}

	    /// <summary>
		/// 客户iD
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 赠送时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 优惠券截至时间
		/// <summary>
		private  DateTime _EndTime;
	 	public DateTime EndTime
		{
			get
			{
				return _EndTime;
			}
			set
			{
				_EndTime=value;
			}
		}

	    /// <summary>
		/// 数量
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

        /// <summary>
        /// 状态 1有效， endtime<now 过期,2已使用， 
        /// <summary>
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        public DicCouponsEntity DicCoupons;
		#endregion				
	}
}
