 /*****************************************
Table  Name:OrderAddress
Create Time:2016/8/4 11:01:53
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderAddress
	/// This entiy code is generated by codesmith. this entity is OrderAddress.
	/// </summary>
	[Serializable()]
	public class OrderAddressEntity
	{
	    #region Public Properties	
		// 邮寄地址表
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 关联客户Id
		private  long _OrderCode;
	 	public long OrderCode
        {
			get
			{
				return _OrderCode;
			}
			set
			{
                _OrderCode = value;
			}
		}

		// 收件人
		private  string _AccepterName;
	 	public string AccepterName
		{
			get
			{
				return _AccepterName;
			}
			set
			{
				_AccepterName=value;
			}
		}

		// 国家类别0国内1海外
		private  int _CtType;
	 	public int CtType
		{
			get
			{
				return _CtType;
			}
			set
			{
				_CtType=value;
			}
		}

		// 国家编号
		private  string _CountryCode;
	 	public string CountryCode
		{
			get
			{
				return _CountryCode;
			}
			set
			{
				_CountryCode=value;
			}
		}

		// 国家名称
		private  string _CountryName;
	 	public string CountryName
		{
			get
			{
				return _CountryName;
			}
			set
			{
				_CountryName=value;
			}
		}

		// 省
		private  int _ProvinceId;
	 	public int ProvinceId
		{
			get
			{
				return _ProvinceId;
			}
			set
			{
                _ProvinceId = value;
			}
		}

		// 市
		private  int _CityId;
	 	public int CityId
        {
			get
			{
				return _CityId;
			}
			set
			{
                _CityId = value;
			}
		}
        // 省
        private string _ProvinceName;
        public string ProvinceName
        {
            get
            {
                return _ProvinceName;
            }
            set
            {
                _ProvinceName = value;
            }
        }

        // 市
        private string _CityName;
        public string CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                _CityName = value;
            }
        }
        // 区县
        private  string _DistrictId;
	 	public string DistrictId
		{
			get
			{
				return _DistrictId;
			}
			set
			{
				_DistrictId=value;
			}
		}

		// 具体地址
		private  string _Address;
	 	public string Address
		{
			get
			{
				return _Address;
			}
			set
			{
				_Address=value;
			}
		}

		// 邮编
		private  string _Postcode;
	 	public string Postcode
		{
			get
			{
				return _Postcode;
			}
			set
			{
				_Postcode=value;
			}
		}

		// 电话号码
		private  string _Telephone;
	 	public string Telephone
		{
			get
			{
				return _Telephone;
			}
			set
			{
				_Telephone=value;
			}
		}

		// 手机号码
		private  string _MobilePhone;
	 	public string MobilePhone
		{
			get
			{
				return _MobilePhone;
			}
			set
			{
				_MobilePhone=value;
			}
		}

		// 默认邮寄地址
		private  int _IsDefault;
	 	public int IsDefault
		{
			get
			{
				return _IsDefault;
			}
			set
			{
				_IsDefault=value;
			}
		}

		// 邮寄地址排序
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
