/*****************************************
Table  Name:OrderDetail
Create Time:2016/8/6 10:38:15
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{
    /// <summary>OrderDetail
    /// This entiy code is generated by codesmith. this entity is OrderDetail.
    /// </summary>
    [Serializable()]
    public class OrderDetailEntity
    {
        #region Public Properties	
        // 订单产品明细
        private int _Id;
        public int Id
        {
            get
            {
                return _Id;
            }
            set
            {
                _Id = value;
            }
        }
        // 产品iD
        private int _ProductId;
        public int ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                _ProductId = value;
            }
        }
        private int _ProductDetailId;
        public int ProductDetailId
        {
            get
            {
                return _ProductDetailId;
            }
            set
            {
                _ProductDetailId = value;
            }
        }
        // 产品款式ID
        private string _Spec1;
        public string Spec1
        {
            get
            {
                return _Spec1;
            }
            set
            {
                _Spec1 = value;
            }
        }
        // 产品款式ID
        private string _Spec2;
        public string Spec2
        {
            get
            {
                return _Spec2;
            }
            set
            {
                _Spec2 = value;
            }
        }
        // 产品款式ID
        private string _Spec3;
        public string Spec3
        {
            get
            {
                return _Spec3;
            }
            set
            {
                _Spec3 = value;
            }
        }
        // 产品款式名称
        private string _ProductName;
        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }

        // 图片路径
        private string _ProductPic;
        public string ProductPic
        {
            get
            {
                return _ProductPic;
            }
            set
            {
                _ProductPic = value;
            }
        }

        // 图片后缀
        private string _ProductPicSuffix;
        public string ProductPicSuffix
        {
            get
            {
                return _ProductPicSuffix;
            }
            set
            {
                _ProductPicSuffix = value;
            }
        }

        // 折扣优惠Id
        private int _DiscountId;
        public int DiscountId
        {
            get
            {
                return _DiscountId;
            }
            set
            {
                _DiscountId = value;
            }
        }
        // 单价
        private decimal _Price;
        public decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                _Price = value;
            }
        }
        // 成本价
        private decimal _Cost;
        public decimal Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                _Cost = value;
            }
        }
        // 批发价
        private decimal _TradePrice;
        public decimal TradePrice
        {
            get
            {
                return _TradePrice;
            }
            set
            {
                _TradePrice = value;
            }
        }
        // 市场单价
        private decimal _MarketPrice;
        public decimal MarketPrice
        {
            get
            {
                return _MarketPrice;
            }
            set
            {
                _MarketPrice = value;
            }
        }

        // 实际单价
        private decimal _ActualPrice;
        public decimal ActualPrice
        {
            get
            {
                return _ActualPrice;
            }
            set
            {
                _ActualPrice = value;
            }
        }

        // 实际订单Id
        private Int64 _OrderCode;
        public Int64 OrderCode
        {
            get
            {
                return _OrderCode;
            }
            set
            {
                _OrderCode = value;
            }
        }

        // 商品数量
        private int _Num;
        public int Num
        {
            get
            {
                return _Num;
            }
            set
            {
                _Num = value;
            }
        }

        // 实际总价格
        private decimal _TotalPrice;
        public decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                _TotalPrice = value;
            }
        }

        // 总市场价
        private decimal _TotalMarketPrice;
        public decimal TotalMarketPrice
        {
            get
            {
                return _TotalMarketPrice;
            }
            set
            {
                _TotalMarketPrice = value;
            }
        }
        private int _IsFreeShipping;
        public int IsFreeShipping
        {
            get
            {
                return _IsFreeShipping;
            }
            set
            {
                _IsFreeShipping = value;
            }
        }
        private decimal _FreightFee;
        public decimal FreightFee
        {
            get
            {
                return _FreightFee;
            }
            set
            {
                _FreightFee = value;
            }
        }
        private decimal _Weight;
        public decimal Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                _Weight = value;
            }
        }
        private decimal _Volume;
        public decimal Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                _Volume = value;
            }
        }
        private int _PostDisCountId;
        public int PostDisCountId
        {
            get
            {
                return _PostDisCountId;
            }
            set
            {
                _PostDisCountId = value;
            }
        }
        public int _HasComment;
        public int HasComment
        {
            get
            {
                return _HasComment;
            }

            set
            {
                _HasComment = value;
            }
        }

        public int _HasReturn;
        public int HasReturn
        {
            get
            {
                return _HasReturn;
            }

            set
            {
                _HasReturn = value;
            }
        }

        public int _ReturnNum;
        public int ReturnNum
        {
            get
            {
                return _ReturnNum;
            }

            set
            {
                _ReturnNum = value;
            }
        }


        public int _IsDeliveried;
        public int IsDeliveried
        {
            get
            {
                return _IsDeliveried;
            }

            set
            {
                _IsDeliveried = value;
            }
        }


        /// <summary>
        /// 是否可退换货
        /// </summary>
        public int _CanReturn;
        public int CanReturn
        {
            get
            {
                return _CanReturn;
            }

            set
            {
                _CanReturn = value;
            }
        }


        /// <summary>
        /// OEM编码
        /// </summary>
        private string _OEM;
        public string OEM
        {
            get
            {
                return _OEM;
            }
            set
            {
                _OEM = value;
            }
        }

        /// <summary>
        /// 原厂地
        /// </summary>
        private string _OriginalPlace;
        public string OriginalPlace
        {
            get
            {
                return _OriginalPlace;
            }
            set
            {
                _OriginalPlace = value;
            }
        }


        /// <summary>
        /// 收货人名称
        /// </summary>
        private string _AccepterName;
        public string AccepterName
        {
            get
            {
                return _AccepterName;
            }

            set
            {
                _AccepterName = value;
            }
        }


        #endregion
    }
}
