/*****************************************
Table  Name:Order
Create Time:2016/8/6 11:59:27
Creator    :jc001
******************************************/
using System;
using System.Collections;
using System.Data;
using System.Text;

//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Order
	/// This entiy code is generated by codesmith. this entity is Order.
	/// </summary>
	[Serializable()]
	public class OrderEntity
	{
	    #region Public Properties	
		// 
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 订单编号
		private long _Code;
	 	public long Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

		// 
		private long _OrderVisualCode;
	 	public long OrderVisualCode
        {
			get
			{
				return _OrderVisualCode;
			}
			set
			{
                _OrderVisualCode = value;
			}
		}

		// 购货客户Id
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}
         
		// 是否商家
		private  int _IsStore;
	 	public int IsStore
		{
			get
			{
				return _IsStore;
			}
			set
			{
				_IsStore=value;
			}
		}

		// 订单状态（1订单下单初始状态=待付款，2支付完成=待确认，3卖家确认=待发货，4卖家发货=待收货，5买家收货=完成 100已关闭
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
         private int _FinancialStatus;
        public int FinancialStatus
        {
            get
            {
                return _FinancialStatus;
            }
            set
            {
                _FinancialStatus = value;
            }
        }
        // 订单状态（1订单下单初始状态=待付款，2支付完成=待确认，3卖家确认=待发货，4卖家发货=待收货，5买家收货=完成 100已关闭
        //private string _StatusName;

        public string StatusName
        {
            get
            {

                return EnumEntityShow.Instance.GetEnumDes((OrderStatus)Status);
            }
            
        }
        // 下单时间
        private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		// 订单类型：电话，网上，线下，换货等
		private  int _OrderType;
	 	public int OrderType
		{
			get
			{
				return _OrderType;
			}
			set
			{
				_OrderType=value;
			}
		}

		// 邮费
		private  decimal _TransFee;
	 	public decimal TransFee
        {
			get
			{
				return _TransFee;
			}
			set
			{
                _TransFee = value;
			}
		}

		// 是否需要发货
		private  int _NeedDeliver;
	 	public int NeedDeliver
		{
			get
			{
				return _NeedDeliver;
			}
			set
			{
				_NeedDeliver=value;
			}
		}

		// 折扣Id
		private  int _Integral;
	 	public int Integral
        {
			get
			{
				return _Integral;
			}
			set
			{
                _Integral = value;
			}
		}
        private decimal _ActPrice;
        public decimal ActPrice
        {
            get
            {
                return _ActPrice;
            }
            set
            {
                _ActPrice = value;
            }
        }
        private decimal _PayPrice;
        public decimal PayPrice
        {
            get
            {
                return _PayPrice;
            }
            set
            {
                _PayPrice = value;
            }
        }
        // 
        private  decimal _TotalPrice;
	 	public decimal TotalPrice
		{
			get
			{
				return _TotalPrice;
			}
			set
			{
				_TotalPrice=value;
			}
		}

		// 
		private  decimal _TotalMarketPrice;
	 	public decimal TotalMarketPrice
		{
			get
			{
				return _TotalMarketPrice;
			}
			set
			{
				_TotalMarketPrice=value;
			}
		}
        // 
        private decimal _PreDisCountPrice;
        public decimal PreDisCountPrice
        {
            get
            {
                return _PreDisCountPrice;
            }
            set
            {
                _PreDisCountPrice = value;
            }
        }
        private decimal _IntegralFee;
        public decimal IntegralFee
        {
            get
            {
                return _IntegralFee;
            }
            set
            {
                _IntegralFee = value;
            }
        }
        // 处理时间
        private  DateTime _DealTime;
	 	public DateTime DealTime
		{
			get
			{
				return _DealTime;
			}
			set
			{
				_DealTime=value;
			}
		}

		// 发货时间
		private  DateTime _DeliverTime;
	 	public DateTime DeliverTime
		{
			get
			{
				return _DeliverTime;
			}
			set
			{
				_DeliverTime=value;
			}
		}

		// 收货时间
		private  DateTime _ReciveTime;
	 	public DateTime ReciveTime
		{
			get
			{
				return _ReciveTime;
			}
			set
			{
				_ReciveTime=value;
			}
		}

		// 是否已开发票
		private  int _MakeBill;
	 	public int MakeBill
        {
			get
			{
				return _MakeBill;
			}
			set
			{
                _MakeBill = value;
			}
		}

		// 完成时间
		private  DateTime _FinishedTime;
	 	public DateTime FinishedTime
		{
			get
			{
				return _FinishedTime;
			}
			set
			{
				_FinishedTime=value;
			}
		}

        private int _MemLevel;
        /// <summary>
        /// 购买者会员级别
        /// </summary>
        public int MemLevel
        {
            get
            {
                return _MemLevel;
            }
            set
            {
                _MemLevel = value;
            }
        }
        private int _PayType;
        public int PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                _PayType = value;
            }
        }
        private string _Remark;
        public string Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                _Remark = value;
            }
        }
        private string _ReasonBack;
        public string ReasonBack
        {
            get
            {
                return _ReasonBack;
            }
            set
            {
                _ReasonBack = value;
            }
        }
        private int _BeforeCancelStatus;
        public int BeforeCancelStatus
        {
            get
            {
                return _BeforeCancelStatus;
            }
            set
            {
                _BeforeCancelStatus = value;
            }
        }

        private int _OrderStyle;
        public int OrderStyle
        {
            get
            {
                return _OrderStyle;
            }
            set
            {
                _OrderStyle = value;
            }
        }

        


        private DateTime _CancelTime;
        public DateTime CancelTime
        {
            get
            {
                return _CancelTime;
            }
            set
            {
                _CancelTime = value;
            }
        }

        private string _TimeStampCode;
        public string TimeStampCode
        {
            get
            {
                return _TimeStampCode;
            }
            set
            {
                _TimeStampCode = value;
            }
        }

        private int _CanReturn;
        public int CanReturn
        {
            get
            {
                return _CanReturn;
            }
            set
            {
                _CanReturn = value;
            }
        }


        /// <summary>
        /// 退款金额
        /// </summary>
        private decimal _ReBackFee;
  
        public decimal ReBackFee
        {
            get;
            set;
        }
        /// <summary>
        /// 退款积分
        /// </summary>
        private decimal _ReBackFeeIntegral;

        public decimal ReBackFeeIntegral
        {
            get;
            set;
        }
        
        #endregion
    }
}
