 /*****************************************
Table  Name:OrderDetailPreTemp
Create Time:2016/9/20 17:14:43
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderDetailPreTemp
	/// This entiy code is generated by codesmith. this entity is OrderDetailPreTemp.
	/// </summary>
	[Serializable()]
	public class OrderDetailPreTempEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 订单产品明细前置临时结算页
		/// <summary>
		private Int64 _Code;
	 	public Int64 Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}
        /// <summary>
        /// 产品价格类别Id
        /// <summary>
        private int _ProductDetailId;
        public int ProductDetailId
        {
            get
            {
                return _ProductDetailId;
            }
            set
            {
                _ProductDetailId = value;
            }
        }
        /// <summary>
        ///  
        /// <summary>
        private int _BrandId;
        public int BrandId
        {
            get
            {
                return _BrandId;
            }
            set
            {
                _BrandId = value;
            }
        }
        /// <summary>
        /// 产品iD
        /// <summary>
        private int _ClassId;
        public int ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                _ClassId = value;
            }
        }
        /// <summary>
        /// 产品iD
        /// <summary>
        private  int _ProductId;
	 	public int ProductId
		{
			get
			{
				return _ProductId;
			}
			set
			{
				_ProductId=value;
			}
		}
        /// <summary>
        /// 产品款式名称
        /// <summary>
        private string _ProductCode;
        public string ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                _ProductCode = value;
            }
        }
        /// <summary>
        /// 产品款式名称
        /// <summary>
        private  string _ProductName;
	 	public string ProductName
		{
			get
			{
				return _ProductName;
			}
			set
			{
				_ProductName=value;
			}
		}
        /// <summary>
        /// 产品款式名称
        /// <summary>
        private string _Spec1;
        public string Spec1
        {
            get
            {
                return _Spec1;
            }
            set
            {
                _Spec1 = value;
            }
        }
        /// <summary>
        /// 产品款式名称
        /// <summary>
        private string _Spec2;
        public string Spec2
        {
            get
            {
                return _Spec2;
            }
            set
            {
                _Spec2 = value;
            }
        }
        /// <summary>
        /// 产品款式名称
        /// <summary>
        private string _Spec3;
        public string Spec3
        {
            get
            {
                return _Spec3;
            }
            set
            {
                _Spec3 = value;
            }
        }
        /// <summary>
        /// 图片路径
        /// <summary>
        private  string _ProductPic;
	 	public string ProductPic
		{
			get
			{
				return _ProductPic;
			}
			set
			{
				_ProductPic=value;
			}
		}
        /// <summary>
        /// 图片路径
        /// <summary>
        private string _ProductPicSuffix;
        public string ProductPicSuffix
        {
            get
            {
                return _ProductPicSuffix;
            }
            set
            {
                _ProductPicSuffix = value;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicOld
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicBig
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "Big." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicNormal
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "Normal." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicSmall
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "Small." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicLittle
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "Little." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string ProductPicList
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "List." + ProductPicSuffix;
            }
        }
        /// <summary>
        /// 折扣优惠Id
        /// <summary>
        private  int _DiscountId;
	 	public int DiscountId
		{
			get
			{
				return _DiscountId;
			}
			set
			{
				_DiscountId=value;
			}
		}
        // 单价
        private decimal _Price;
        public decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                _Price = value;
            }
        }
        // 成本价
        private decimal _Cost;
        public decimal Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                _Cost = value;
            }
        }
        // 批发价
        private decimal _TradePrice;
        public decimal TradePrice
        {
            get
            {
                return _TradePrice;
            }
            set
            {
                _TradePrice = value;
            }
        }
        // 经销商价格
        private decimal _DealerPrice;
        public decimal DealerPrice
        {
            get
            {
                return _DealerPrice;
            }
            set
            {
                _DealerPrice = value;
            }
        }
        
        /// <summary>
        /// 市场单价
        /// <summary>
        private  decimal _MarketPrice;
	 	public decimal MarketPrice
		{
			get
			{
				return _MarketPrice;
			}
			set
			{
				_MarketPrice=value;
			}
		}

	    /// <summary>
		/// 实际单价
		/// <summary>
		private  decimal _ActualPrice;
	 	public decimal ActualPrice
		{
			get
			{
				return _ActualPrice;
			}
			set
			{
				_ActualPrice=value;
			}
		}

	    

	    /// <summary>
		/// 商品数量
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        private string _Remark;
        public string Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                _Remark = value;
            }
        }
        /// <summary>
        /// 实际总价格
        /// <summary>
        private  decimal _TotalPrice;
	 	public decimal TotalPrice
		{
			get
			{
				return _TotalPrice;
			}
			set
			{
				_TotalPrice=value;
			}
		}

	    /// <summary>
		/// 总市场价
		/// <summary>
		private  decimal _TotalMarketPrice;
	 	public decimal TotalMarketPrice
		{
			get
			{
				return _TotalMarketPrice;
			}
			set
			{
				_TotalMarketPrice=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}
   
        private int _TransFeeType;
        /// <summary>
        /// 计算运费的方式1,免运费 0：固定运费，2按照重量体积计算,3按照数量增加运费,
        /// </summary>
        public int TransFeeType
        {
            get
            {
                return _TransFeeType;
            }
            set
            {
                _TransFeeType = value;
            }
        }
        private decimal _TransFee;
        public decimal TransFee
        {
            get
            {
                return _TransFee;
            }
            set
            {
                _TransFee = value;
            }
        }
        private decimal _Weight;
        public decimal Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                _Weight = value;
            }
        }
        /// <summary>
        /// 产品价格类别Id
        /// <summary>
        private int _ProductType;
        public int ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                _ProductType = value;
            }
        }
        /// <summary>
        /// 产品价格类别Id
        /// <summary>
        private int _StockNum;
        public int StockNum
        {
            get
            {
                return _StockNum;
            }
            set
            {
                _StockNum = value;
            }
        }
        private int _Unit;
        public int Unit
        {
            get
            {
                return _Unit;
            }
            set
            {
                _Unit = value;
            }
        }
        private int _IsBP;
        public int IsBP
        {
            get
            {
                return _IsBP;
            }
            set
            {
                _IsBP = value;
            }
        }
        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }
        private int _IsAhmTake;
        public int IsAhmTake
        {
            get
            {
                return _IsAhmTake;
            }
            set
            {
                _IsAhmTake = value;
            }
        }
        #endregion
    }
}
