 /*****************************************
Table  Name:OrderCreateLog
Create Time:2017/1/16 14:22:41
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderCreateLog
	/// This entiy code is generated by codesmith. this entity is OrderCreateLog.
	/// </summary>
	[Serializable()]
	public class OrderCreateLogEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 订单后台生成订单表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _OldOrderCode;
	 	public Int64 OldOrderCode
		{
			get
			{
				return _OldOrderCode;
			}
			set
			{
				_OldOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _PreTempCode;
	 	public Int64 PreTempCode
		{
			get
			{
				return _PreTempCode;
			}
			set
			{
				_PreTempCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  Int64 _NewOrderCode;
	 	public Int64 NewOrderCode
		{
			get
			{
				return _NewOrderCode;
			}
			set
			{
				_NewOrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CreateManId;
	 	public int CreateManId
		{
			get
			{
				return _CreateManId;
			}
			set
			{
				_CreateManId=value;
			}
		}

		#endregion				
	}
}
