 /*****************************************
Table  Name:OrderVirtual
Create Time:2016/8/4 11:01:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderVirtual
	/// This entiy code is generated by codesmith. this entity is OrderVirtual.
	/// </summary>
	[Serializable()]
	public class OrderVirtualEntity
	{
	    #region Public Properties	
		// 下单的时候总订单表
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 总价格
		private  decimal _TotalPrice;
	 	public decimal TotalPrice
		{
			get
			{
				return _TotalPrice;
			}
			set
			{
				_TotalPrice=value;
			}
		}

		// 市场总价
		private  decimal _TotalMarketPrice;
	 	public decimal TotalMarketPrice
		{
			get
			{
				return _TotalMarketPrice;
			}
			set
			{
				_TotalMarketPrice=value;
			}
		}

		// 客户Id
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		// 是否支付
		private  int _IsPay;
	 	public int IsPay
		{
			get
			{
				return _IsPay;
			}
			set
			{
				_IsPay=value;
			}
		}

		// 支付时间
		private  DateTime _PayTime;
	 	public DateTime PayTime
		{
			get
			{
				return _PayTime;
			}
			set
			{
				_PayTime=value;
			}
		}

		// 支付方式(1.账户余额支付，2，支付宝支付，3,银联支付，4微信支付）
		private  int _PayConCode;
	 	public int PayConCode
		{
			get
			{
				return _PayConCode;
			}
			set
			{
				_PayConCode=value;
			}
		}

		// 支付交易编码（银行回传）
		private  string _TranSerialNum;
	 	public string TranSerialNum
		{
			get
			{
				return _TranSerialNum;
			}
			set
			{
				_TranSerialNum=value;
			}
		}

		#endregion				
	}
}
