 /*****************************************
Table  Name:OrderMsgMem
Create Time:2016/8/4 11:01:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderMsgMem
	/// This entiy code is generated by codesmith. this entity is OrderMsgMem.
	/// </summary>
	[Serializable()]
	public class OrderMsgMemEntity
	{
	    #region Public Properties	
		// 
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		// 总订单数量
		private  int _TotalNum;
	 	public int TotalNum
		{
			get
			{
				return _TotalNum;
			}
			set
			{
				_TotalNum=value;
			}
		}

		// 待支付订单数量
		private  int _WaitPayNum;
	 	public int WaitPayNum
        {
            get
            {
                return _WaitPayNum;
            }
            set
            {
                _WaitPayNum = value;
            }
        }
        // 待卖家发货订单数量
        private int _WaitSellerDeliverNum;
        public int WaitSellerDeliverNum
        {
            get
            {
                return _WaitSellerDeliverNum;
            }
            set
            {
                _WaitSellerDeliverNum = value;
            }
        }
        /// <summary>
        /// 待收货订单数量
        /// </summary> 
        private int _WaitReciveNum;
	 	public int WaitReciveNum
		{
			get
			{
				return _WaitReciveNum;
			}
			set
			{
				_WaitReciveNum=value;
			}
		}

		// 待评价数量
		private  int _WaitCommentNum;
	 	public int WaitCommentNum
		{
			get
			{
				return _WaitCommentNum;
			}
			set
			{
				_WaitCommentNum=value;
			}
		}

		// 取消订单数量
		private  int _CancelNum;
	 	public int CancelNum
		{
			get
			{
				return _CancelNum;
			}
			set
			{
				_CancelNum=value;
			}
		}

		#endregion				
	}
}
