 /*****************************************
Table  Name:OrderMsgStore
Create Time:2016/8/4 11:01:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>OrderMsgStore
	/// This entiy code is generated by codesmith. this entity is OrderMsgStore.
	/// </summary>
	[Serializable()]
	public class OrderMsgStoreEntity
	{
	    #region Public Properties	
		// 
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 商家MemId
		private  int _SellerId;
	 	public int SellerId
		{
			get
			{
				return _SellerId;
			}
			set
			{
				_SellerId=value;
			}
		}

		// 订单总数
		private  int _TotallNum;
	 	public int TotallNum
		{
			get
			{
				return _TotallNum;
			}
			set
			{
				_TotallNum=value;
			}
		}

		// 待处理确认订单数量
		private  int _WaitDealNum;
	 	public int WaitDealNum
		{
			get
			{
				return _WaitDealNum;
			}
			set
			{
				_WaitDealNum=value;
			}
		}

		// 待发货订单数量
		private  int _WaitDeliverNum;
	 	public int WaitDeliverNum
		{
			get
			{
				return _WaitDeliverNum;
			}
			set
			{
				_WaitDeliverNum=value;
			}
		}

		// 退货订单数量
		private  int _ReturnNum;
	 	public int ReturnNum
		{
			get
			{
				return _ReturnNum;
			}
			set
			{
				_ReturnNum=value;
			}
		}

		// 换货订单数量
		private  int _ExchangeNum;
	 	public int ExchangeNum
		{
			get
			{
				return _ExchangeNum;
			}
			set
			{
				_ExchangeNum=value;
			}
		}

		// 已完成订单数量
		private  int _FinishedNum;
	 	public int FinishedNum
		{
			get
			{
				return _FinishedNum;
			}
			set
			{
				_FinishedNum=value;
			}
		}

		// 拒绝订单数量
		private  int _RejectNum;
	 	public int RejectNum
		{
			get
			{
				return _RejectNum;
			}
			set
			{
				_RejectNum=value;
			}
		}

		#endregion				
	}
}
