 /*****************************************
Table  Name:PayEBank
Create Time:2016/10/9 10:37:33
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>PayEBank
	/// This entiy code is generated by codesmith. this entity is PayEBank.
	/// </summary>
	[Serializable()]
	public class PayEBankEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 记录支付路径表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 银行编号
		/// <summary>
		private  string _EBankCode;
	 	public string EBankCode
		{
			get
			{
				return _EBankCode;
			}
			set
			{
				_EBankCode=value;
			}
		}

	    /// <summary>
		/// 银行名称
		/// <summary>
		private  string _EBankName;
	 	public string EBankName
		{
			get
			{
				return _EBankName;
			}
			set
			{
				_EBankName=value;
			}
		}

	    /// <summary>
		/// POST/GET
		/// <summary>
		private  string _FormMethod;
	 	public string FormMethod
		{
			get
			{
				return _FormMethod;
			}
			set
			{
				_FormMethod=value;
			}
		}

	    /// <summary>
		/// FormAction
		/// <summary>
		private  string _FormAction;
	 	public string FormAction
		{
			get
			{
				return _FormAction;
			}
			set
			{
				_FormAction=value;
			}
		}

	    /// <summary>
		/// 响应地址
		/// <summary>
		private  string _ResponseURL;
	 	public string ResponseURL
		{
			get
			{
				return _ResponseURL;
			}
			set
			{
				_ResponseURL=value;
			}
		}

	    /// <summary>
		/// 私钥
		/// <summary>
		private  string _PrivateKey;
	 	public string PrivateKey
		{
			get
			{
				return _PrivateKey;
			}
			set
			{
				_PrivateKey=value;
			}
		}

	    /// <summary>
		/// 公钥
		/// <summary>
		private  string _PublicKey;
	 	public string PublicKey
		{
			get
			{
				return _PublicKey;
			}
			set
			{
				_PublicKey=value;
			}
		}

	    /// <summary>
		///  银行提供的商家ID
		/// <summary>
		private  string _MerchantCode;
	 	public string MerchantCode
		{
			get
			{
				return _MerchantCode;
			}
			set
			{
				_MerchantCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _EmailAddress;
	 	public string EmailAddress
		{
			get
			{
				return _EmailAddress;
			}
			set
			{
				_EmailAddress=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        private int _PayType;
        public int PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                _PayType = value;
            }
        }
        
        #endregion
    }
}
