 /*****************************************
Table  Name:PayTrade
Create Time:2016/10/9 10:37:33
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>PayTrade
	/// This entiy code is generated by codesmith. this entity is PayTrade.
	/// </summary>
	[Serializable()]
	public class PayTradeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private string _PayCode="";
	 	public string PayCode
		{
			get
			{
				return _PayCode;
			}
			set
			{
				_PayCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private Int64 _OrderCode;
	 	public Int64 OrderCode
		{
			get
			{
				return _OrderCode;
			}
			set
			{
				_OrderCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private decimal _OrderAmount;
	 	public decimal OrderAmount
		{
			get
			{
				return _OrderAmount;
			}
			set
			{
				_OrderAmount=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _PayBankCode = "";
	 	public string PayBankCode
		{
			get
			{
				return _PayBankCode;
			}
			set
			{
				_PayBankCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _TransCode = "";
	 	public string TransCode
		{
			get
			{
				return _TransCode;
			}
			set
			{
				_TransCode=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _MobilePhone = "";
	 	public string MobilePhone
		{
			get
			{
				return _MobilePhone;
			}
			set
			{
				_MobilePhone=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private DateTime _CreateTime;
        public DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                _CreateTime = value;
            }
        }
        /// <summary>
        ///  批量退换货编号
        /// </summary>
        public string Batch_No
        {
            get;
            set;
        } /// <summary>
          ///  批量退换货数量
          /// </summary>
        public int Batch_Num
        {
            get;
            set;
        } /// <summary>
          ///  批量退换货明细内容
          /// </summary>
        public string Refund_Data
        {
            get;
            set;
        } 
        #endregion
    }
}
