 /*****************************************
Table  Name:ReturnXSWL
Create Time:2017/1/16 12:07:55
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ReturnXSWL
	/// This entiy code is generated by codesmith. this entity is ReturnXSWL.
	/// </summary>
	[Serializable()]
	public class ReturnXSWLEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 退换货单Id
		/// <summary>
		private  int _ReturnId;
	 	public int ReturnId
		{
			get
			{
				return _ReturnId;
			}
			set
			{
				_ReturnId=value;
			}
		}
        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }
        private int _ReturnNum;
        public int ReturnNum
        {
            get
            {
                return _ReturnNum;
            }
            set
            {
                _ReturnNum = value;
            }
        }
        private long _NewOrderCode;
        public long NewOrderCode
        {
            get
            {
                return _NewOrderCode;
            }
            set
            {
                _NewOrderCode = value;
            }
        }
        private int _ReturnType;
        public int ReturnType
        {
            get
            {
                return _ReturnType;
            }
            set
            {
                _ReturnType = value;
            }
        }
        
        /// <summary>
        /// 易店心收货邮编
        /// <summary>
        private  string _AahamaPost;
	 	public string AahamaPost
		{
			get
			{
				return _AahamaPost;
			}
			set
			{
				_AahamaPost=value;
			}
		}

	    /// <summary>
		/// 易店心收货地址
		/// <summary>
		private  string _AahamaAddress;
	 	public string AahamaAddress
		{
			get
			{
				return _AahamaAddress;
			}
			set
			{
				_AahamaAddress=value;
			}
		}

	    /// <summary>
		/// 易店心收货电话
		/// <summary>
		private  string _AahamaPhone;
	 	public string AahamaPhone
		{
			get
			{
				return _AahamaPhone;
			}
			set
			{
				_AahamaPhone=value;
			}
		}

	    /// <summary>
		/// 易店心收货省份
		/// <summary>
		private  int _AahamaProvince;
	 	public int AahamaProvince
		{
			get
			{
				return _AahamaProvince;
			}
			set
			{
				_AahamaProvince=value;
			}
		}

	    /// <summary>
		/// 易店心收货城市
		/// <summary>
		private  int _AahamaCity;
	 	public int AahamaCity
		{
			get
			{
				return _AahamaCity;
			}
			set
			{
				_AahamaCity=value;
			}
		}

	    /// <summary>
		/// 易店心收货人
		/// <summary>
		private  string _AahamaName;
	 	public string AahamaName
		{
			get
			{
				return _AahamaName;
			}
			set
			{
				_AahamaName=value;
			}
		}

	    /// <summary>
		/// 退换货的物流编号
		/// <summary>
		private  string _WLCode;
	 	public string WLCode
		{
			get
			{
				return _WLCode;
			}
			set
			{
				_WLCode=value;
			}
		}

	    /// <summary>
		/// 退换货物流名称
		/// <summary>
		private  string _WLComName;
	 	public string WLComName
		{
			get
			{
				return _WLComName;
			}
			set
			{
				_WLComName=value;
			}
		}

	    /// <summary>
		/// 备注
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

	    /// <summary>
		/// 物流发送时间
		/// <summary>
		private  DateTime _WLTime;
	 	public DateTime WLTime
		{
			get
			{
				return _WLTime;
			}
			set
			{
				_WLTime=value;
			}
		}

        /// <summary>
        /// 备注
        /// <summary>
        private string _AccepterName;
        public string AccepterName
        {
            get
            {
                return _AccepterName;
            }
            set
            {
                _AccepterName = value;
            }
        }

        /// <summary>
        /// 备注
        /// <summary>
        private string _AccepterPhone;
        public string AccepterPhone
        {
            get
            {
                return _AccepterPhone;
            }
            set
            {
                _AccepterPhone = value;
            }
        }

        #endregion
    }
}
