 /*****************************************
Table  Name:ReturnXS
Create Time:2016/9/22 11:23:28
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ReturnXS
	/// This entiy code is generated by codesmith. this entity is ReturnXS.
	/// </summary>
	[Serializable()]
	public class ReturnXSEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 退换货主表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 款式Id
		/// <summary>
		private  int _ProductId;
	 	public int ProductId
        {
			get
			{
				return _ProductId;
			}
			set
			{
                _ProductId = value;
			}
		}

	  

	    /// <summary>
		/// 原订单Id
		/// <summary>
		private long _ReturnOrderCode;
	 	public long ReturnOrderCode
		{
			get
			{
				return _ReturnOrderCode;
			}
			set
			{
				_ReturnOrderCode=value;
			}
		}

	    /// <summary>
		/// 明细Id
		/// <summary>
		private  int _ReturnOrderDetailId;
	 	public int ReturnOrderDetailId
		{
			get
			{
				return _ReturnOrderDetailId;
			}
			set
			{
				_ReturnOrderDetailId=value;
			}
		}

	    /// <summary>
		/// 款式名称
		/// <summary>
		private  string _ProductName;
	 	public string ProductName
        {
			get
			{
				return _ProductName;
			}
			set
			{
                _ProductName = value;
			}
		}

	    /// <summary>
		/// 退货数量
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}

	    /// <summary>
		/// 价格
		/// <summary>
		private  decimal _Price;
	 	public decimal Price
		{
			get
			{
				return _Price;
			}
			set
			{
				_Price=value;
			}
		}

	    /// <summary>
		/// 1退货，2换货
		/// <summary>
		private  int _ReturnType;
	 	public int ReturnType
		{
			get
			{
				return _ReturnType;
			}
			set
			{
				_ReturnType=value;
			}
		}

	     

	    /// <summary>
		/// 换货的新订单号码
		/// <summary>
		private  string _NewOrderCode;
	 	public string NewOrderCode
		{
			get
			{
				return _NewOrderCode;
			}
			set
			{
				_NewOrderCode=value;
			}
		}

	    /// <summary>
		/// 退货说明
		/// <summary>
		private  string _ReturnDescription;
	 	public string ReturnDescription
		{
			get
			{
				return _ReturnDescription;
			}
			set
			{
				_ReturnDescription=value;
			}
		}

	    /// <summary>
		/// 退货原因
		/// <summary>
		private  string _ReturnReason;
	 	public string ReturnReason
		{
			get
			{
				return _ReturnReason;
			}
			set
			{
				_ReturnReason=value;
			}
		}

	    /// <summary>
		/// 退货申请时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 退货状态0申请中，1审核通过，2审核拒绝
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

	    /// <summary>
		/// 申请人ID
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 拒绝原因
		/// <summary>
		private  string _RejectReason;
	 	public string RejectReason
		{
			get
			{
				return _RejectReason;
			}
			set
			{
				_RejectReason=value;
			}
		}

	    /// <summary>
		/// 审核人ID
		/// <summary>
		private  string _CheckManId;
	 	public string CheckManId
		{
			get
			{
				return _CheckManId;
			}
			set
			{
				_CheckManId=value;
			}
		}

	    /// <summary>
		/// 审核时间
		/// <summary>
		private  DateTime _CheckTime;
	 	public DateTime CheckTime
		{
			get
			{
				return _CheckTime;
			}
			set
			{
				_CheckTime=value;
			}
		}


        /// <summary>
        /// 产品图片
        /// </summary>
        private string _ProductPic;
        public string ProductPic
        {
            get
            {
                return  _ProductPic ;
            }
            set
            {
                _ProductPic = value;
            }
        }
        /// <summary>
        /// 列表页显示图片地址
        /// <summary> 
        public string PicUrlSmall
        {
            get
            {
                return string.IsNullOrEmpty(ProductPic) ? "" : ProductPic + "Small." + ProductPicSuffix;
            }
        }

        /// <summary>
        /// 产品图片后缀名
        /// </summary>
        public string _ProductPicSuffix;
        public string ProductPicSuffix
        {
            get
            {
                return _ProductPicSuffix;
            }
            set
            {
                _ProductPicSuffix = value;
            }
        }

        /// <summary>
        /// 支付方式
        /// </summary>
        public int _PayType;
        public int PayType
        {
            get
            {
                return _PayType;
            }
            set
            {
                _PayType = value;
            }
        }

        /// <summary>
        /// 省份Id
        /// </summary>
        public int _ProvinceId;
        public int ProvinceId
        {
            get
            {
                return _ProvinceId;
            }
            set
            {
                _ProvinceId = value;
            }
        }

        /// <summary>
        /// 城市Id
        /// </summary>
        public int _CityId;
        public int CityId
        {
            get
            {
                return _CityId;
            }
            set
            {
                _CityId = value;
            }
        }

        /// <summary>
        /// 取件地址
        /// </summary>
        public string _GetAddress;
        public string GetAddress
        {
            get
            {
                return _GetAddress;
            }
            set
            {
                _GetAddress = value;
            }
        }

        /// <summary>
        /// 取件时间
        /// </summary>
        public DateTime _GetTime;
        public DateTime GetTime
        {
            get
            {
                return _GetTime;
            }
            set
            {
                _GetTime = value;
            }
        }

        /// <summary>
        /// 收货人姓名
        /// </summary>
        public string _AcceptName;
        public string AcceptName
        {
            get
            {
                return _AcceptName;
            }
            set
            {
                _AcceptName = value;
            }
        }

        /// <summary>
        /// 收货人电话
        /// </summary>
        public string _AcceptPhone;
        public string AcceptPhone
        {
            get
            {
                return _AcceptPhone;
            }
            set
            {
                _AcceptPhone = value;
            }
        }

        /// <summary>
        /// 退换货收货方式
        /// </summary>
        public int _AahamaReciveType;
        public int AahamaReciveType
        {
            get
            {
                return _AahamaReciveType;
            }
            set
            {
                _AahamaReciveType = value;
            }
        }







        #endregion
    }
}
