 /*****************************************
Table  Name:WLCompany
Create Time:2016/9/19 11:40:02
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WLCompany
	/// This entiy code is generated by codesmith. this entity is WLCompany.
	/// </summary>
	[Serializable()]
	public class WLCompanyEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 合作的物流公司记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 物流公司标号
		/// <summary>
		private  string _Code;
	 	public string Code
		{
			get
			{
				return _Code;
			}
			set
			{
				_Code=value;
			}
		}

	    /// <summary>
		/// 物流公司名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 是否默认物流公司
		/// <summary>
		private  int _IsDefault;
	 	public int IsDefault
		{
			get
			{
				return _IsDefault;
			}
			set
			{
				_IsDefault=value;
			}
		}

	    /// <summary>
		/// 优先级排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
