 /*****************************************
Table  Name:IssueContent
Create Time:2016/10/8 13:43:31
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>IssueContent
	/// This entiy code is generated by codesmith. this entity is IssueContent.
	/// </summary>
	[Serializable()]
	public class IssueContentEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 问题内容明细表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 分类Id
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}
        /// <summary>
        /// 分类Id
        /// <summary>
        private string _ClassName;
        public string ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                _ClassName = value;
            }
        }
        /// <summary>
        /// 问题标题
        /// <summary>
        private  string _IssueTitle;
	 	public string IssueTitle
		{
			get
			{
				return _IssueTitle;
			}
			set
			{
				_IssueTitle=value;
			}
		}

	    /// <summary>
		/// 内容明细
		/// <summary>
		private  string _IssueContent;
	 	public string IssueContent
		{
			get
			{
				return _IssueContent;
			}
			set
			{
				_IssueContent=value;
			}
		}

	    /// <summary>
		/// 是否有效
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 排序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

		#endregion				
	}
}
