 /*****************************************
Table  Name:IssueClass
Create Time:2016/10/8 13:43:31
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>IssueClass
	/// This entiy code is generated by codesmith. this entity is IssueClass.
	/// </summary>
	[Serializable()]
	public class IssueClassEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 常见问题分类表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 分类名称
		/// <summary>
		private  string _ClassName;
	 	public string ClassName
		{
			get
			{
				return _ClassName;
			}
			set
			{
				_ClassName=value;
			}
		}

	    /// <summary>
		/// 上级Id
		/// <summary>
		private  int _ParentId;
	 	public int ParentId
		{
			get
			{
				return _ParentId;
			}
			set
			{
				_ParentId=value;
			}
		}

	    /// <summary>
		/// 同级下的排序，降序
		/// <summary>
		private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}

	    /// <summary>
		/// 0,：普通帮助文档，1导航到分类明细，2导航到内容
		/// <summary>
		private  int _UrlMethod;
	 	public int UrlMethod
		{
			get
			{
				return _UrlMethod;
			}
			set
			{
				_UrlMethod=value;
			}
		}

	    /// <summary>
		/// 1直接有内容0直接没有内容需要从下级中继续找
		/// <summary>
		private  int _HasContent;
	 	public int HasContent
		{
			get
			{
				return _HasContent;
			}
			set
			{
				_HasContent=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}
        /// <summary>
        /// 
        /// <summary>
        private int _SystemType;
        public int SystemType
        {
            get
            {
                return _SystemType;
            }
            set
            {
                _SystemType = value;
            }
        }
        
        #endregion
    }
}
