 /*****************************************
Table  Name:BankInfo
Create Time:2016/8/1 13:49:38
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>BankInfo
	/// This entiy code is generated by codesmith. this entity is BankInfo.
	/// </summary>
	[Serializable()]
	public class BankInfoEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 
	 	public int MemId
		{
			get;
			set;
		}

		// 账户类型（1，支付宝，2银联，3微信
	 	public int AccountType
		{
			get;
			set;
		}

		// 账户号码，支付宝账号，银行账号，微信账号
	 	public string CardNo
		{
			get;
			set;
		}

		// 账户名
	 	public string CardName
		{
			get;
			set;
		}

		// 开户行
	 	public string BankName
		{
			get;
			set;
		}

		// 开户行支行
	 	public string BankSubName
		{
			get;
			set;
		}

		// 手机号码
	 	public string MobilePhone
		{
			get;
			set;
		}

		// 是否默认提现银行
	 	public int IsDeaultDraw
		{
			get;
			set;
		}

		// 
	 	public int IsActive
		{
			get;
			set;
		}

		#endregion				
	}
}
