 /*****************************************
Table  Name:MemBillCom
Create Time:2016/11/17 22:47:49
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemBillCom
	/// This entiy code is generated by codesmith. this entity is MemBillCom.
	/// </summary>
	[Serializable()]
	public class MemBillComEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 普通发票记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 抬头
		/// <summary>
		private  string _Title;
	 	public string Title
		{
			get
			{
				return _Title;
			}
			set
			{
				_Title=value;
			}
		}

	    /// <summary>
		/// 创建时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}
        /// <summary>
        /// 创建时间
        /// <summary>
        private DateTime _UpdateTime;
        public DateTime UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                _UpdateTime = value;
            }
        }
        /// <summary>
        /// 排序
        /// <summary>
        private  int _Sort;
	 	public int Sort
		{
			get
			{
				return _Sort;
			}
			set
			{
				_Sort=value;
			}
		}
        /// <summary>
        /// 状态
        /// <summary>
        private int _Status;
        public int Status
        {
            get
            {
                return _Status;
            }
            set
            {
                _Status = value;
            }
        }
        
        /// <summary>
        /// 
        /// <summary>
        private  int _IsDefault;
	 	public int IsDefault
		{
			get
			{
				return _IsDefault;
			}
			set
			{
				_IsDefault=value;
			}
		}

		#endregion				
	}
}
