 /*****************************************
Table  Name:Member
Create Time:2016/8/9 10:45:22
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Member
	/// This entiy code is generated by codesmith. this entity is Member.
	/// </summary>
	[Serializable()]
	public partial class MemberEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 账号
		/// <summary>
		private  string _MemCode;
	 	public string MemCode
		{
			get
			{
				return _MemCode;
			}
			set
			{
				_MemCode=value;
			}
		}
        /// <summary>
        /// 账号
        /// <summary>
        private string _MemNikeName;
        public string MemNikeName
        {
            get
            {
                return _MemNikeName;
            }
            set
            {
                _MemNikeName = value;
            }
        }
        
        /// <summary>
        /// Email地址
        /// <summary>
        private  string _Email;
	 	public string Email
		{
			get
			{
				return _Email;
			}
			set
			{
				_Email=value;
			}
		}

	    /// <summary>
		/// QQ
		/// <summary>
		private  string _QQ;
	 	public string QQ
		{
			get
			{
				return _QQ;
			}
			set
			{
				_QQ=value;
			}
		}

	    /// <summary>
		/// 微信账号
		/// <summary>
		private  string _WeChat;
	 	public string WeChat
		{
			get
			{
				return _WeChat;
			}
			set
			{
				_WeChat=value;
			}
		}

	    /// <summary>
		/// 手机号码
		/// <summary>
		private  string _MobilePhone;
	 	public string MobilePhone
		{
			get
			{
				return _MobilePhone;
			}
			set
			{
				_MobilePhone=value;
			}
		}

	    /// <summary>
		/// 密码
		/// <summary>
		private  string _PassWord;
	 	public string PassWord
		{
			get
			{
				return _PassWord;
			}
			set
			{
				_PassWord=value;
			}
		}

	    /// <summary>
		/// 注册时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 最后登录时间
		/// <summary>
		private  DateTime _LastLoginTime;
	 	public DateTime LastLoginTime
		{
			get
			{
				return _LastLoginTime;
			}
			set
			{
				_LastLoginTime=value;
			}
		}

	    /// <summary>
		/// 登录次数
		/// <summary>
		private  int _LoginNum;
	 	public int LoginNum
		{
			get
			{
				return _LoginNum;
			}
			set
			{
				_LoginNum=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _CreateIp;
	 	public string CreateIp
		{
			get
			{
				return _CreateIp;
			}
			set
			{
				_CreateIp=value;
			}
		}

	    /// <summary>
		/// 注册的客户端种类，枚举表
		/// <summary>
		private  int _CreateClientType;
	 	public int CreateClientType
		{
			get
			{
				return _CreateClientType;
			}
			set
			{
				_CreateClientType=value;
			}
		}
        /// <summary>
        /// 是否供应商
        /// <summary>
        private int _IsSupplier;
        public int IsSupplier
        {
            get
            {
                return _IsSupplier;
            }
            set
            {
                _IsSupplier = value;
            }
        }
        private int _IsSysUser;
        public int IsSysUser
        {
            get
            {
                return _IsSysUser;
            }
            set
            {
                _IsSysUser = value;
            }
        }
        
        /// <summary>
        /// 是否是商家
        /// <summary>
        private  int _IsStore;
	 	public int IsStore
		{
			get
			{
				return _IsStore;
			}
			set
			{
				_IsStore=value;
			}
		}
        /// <summary>
        ///  
        /// <summary>
        private int _StoreType;
        public int StoreType
        {
            get
            {
                return _StoreType;
            }
            set
            {
                _StoreType = value;
            }
        }
        /// <summary>
        /// 账号状态：1有效，2待审核，3锁定，
        /// <summary>
        private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
        public string StatusName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((MemberStatus)Status);
            } 
        }
        /// <summary>
        /// 用户级别(1普通客户，2铜牌客户，3银牌客户，4金牌客户，5钻石客户，10普通商家
        /// <summary>
        private  int _MemGrade;
	 	public int MemGrade
		{
			get
			{
				return _MemGrade;
			}
			set
			{
				_MemGrade=value;
			}
		}

	   

	    /// <summary>
		/// 
		/// <summary>
		private  string _RecommendCode;
	 	public string RecommendCode
		{
			get
			{
				return _RecommendCode;
			}
			set
			{
				_RecommendCode=value;
			}
		}


        /// <summary>
        /// 修改密码时需要验证的随机数
        /// <summary>
        private string _TimeStampTab;
        public string TimeStampTab
        {
            get
            {
                return _TimeStampTab;
            }
            set
            {
                _TimeStampTab = value;
            }
        }


        #endregion
    }
}
