 /*****************************************
Table  Name:MemBillVAT
Create Time:2016/11/17 22:47:49
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemBillVAT
	/// This entiy code is generated by codesmith. this entity is MemBillVAT.
	/// </summary>
	[Serializable()]
	public class MemBillVATEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 发票信息登记表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 公司名称
		/// <summary>
		private  string _CompanyName;
	 	public string CompanyName
		{
			get
			{
				return _CompanyName;
			}
			set
			{
				_CompanyName=value;
			}
		}

	    /// <summary>
		/// 公司编号，纳税识别码
		/// <summary>
		private  string _CompanyCode;
	 	public string CompanyCode
		{
			get
			{
				return _CompanyCode;
			}
			set
			{
				_CompanyCode=value;
			}
		}

	    /// <summary>
		/// 注册地址
		/// <summary>
		private  string _CompanyAddress;
	 	public string CompanyAddress
		{
			get
			{
				return _CompanyAddress;
			}
			set
			{
				_CompanyAddress=value;
			}
		}

	    /// <summary>
		/// 注册电话
		/// <summary>
		private  string _CompanyPhone;
	 	public string CompanyPhone
		{
			get
			{
				return _CompanyPhone;
			}
			set
			{
				_CompanyPhone=value;
			}
		}

	    /// <summary>
		/// 开户行
		/// <summary>
		private  string _CompanyBank;
	 	public string CompanyBank
		{
			get
			{
				return _CompanyBank;
			}
			set
			{
				_CompanyBank=value;
			}
		}

	    /// <summary>
		/// 账号
		/// <summary>
		private  string _BankAccount;
	 	public string BankAccount
		{
			get
			{
				return _BankAccount;
			}
			set
			{
				_BankAccount=value;
			}
		}

	    /// <summary>
		/// 收票人信息
		/// <summary>
		private  string _ReceiverName;
	 	public string ReceiverName
		{
			get
			{
				return _ReceiverName;
			}
			set
			{
				_ReceiverName=value;
			}
		}

	    /// <summary>
		/// 收票人手机
		/// <summary>
		private  string _ReceiverPhone;
	 	public string ReceiverPhone
		{
			get
			{
				return _ReceiverPhone;
			}
			set
			{
				_ReceiverPhone=value;
			}
		}

	    /// <summary>
		/// 收票省份
		/// <summary>
		private  int _ReceiverProvince;
	 	public int ReceiverProvince
		{
			get
			{
				return _ReceiverProvince;
			}
			set
			{
				_ReceiverProvince=value;
			}
		}

	    /// <summary>
		/// 收票城市
		/// <summary>
		private  int _ReceiverCity;
	 	public int ReceiverCity
		{
			get
			{
				return _ReceiverCity;
			}
			set
			{
				_ReceiverCity=value;
			}
		}

	    /// <summary>
		/// 收票地址
		/// <summary>
		private  string _ReceiverAddress;
	 	public string ReceiverAddress
		{
			get
			{
				return _ReceiverAddress;
			}
			set
			{
				_ReceiverAddress=value;
			}
		}

	    /// <summary>
		/// 状态0待审核1审核通过
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}
        /// <summary>
        /// 状态0待审核1审核通过
        /// <summary>
        private int _IsDefault;
        public int IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                _IsDefault = value;
            }
        }
        /// <summary>
        /// 状态0待审核1审核通过
        /// <summary>
        private int _BillType;
        public int BillType
        {
            get
            {
                return _BillType;
            }
            set
            {
                _BillType = value;
            }
        } 
        public string BillTypeName
        {
            get
            {
                return EnumEntityShow.Instance.GetEnumDes((BillType)BillType); 
            }
        }
        /// <summary>
        /// 申请时间
        /// <summary>
        private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _UpdateTime;
	 	public DateTime UpdateTime
		{
			get
			{
				return _UpdateTime;
			}
			set
			{
				_UpdateTime=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _CheckManId;
	 	public int CheckManId
		{
			get
			{
				return _CheckManId;
			}
			set
			{
				_CheckManId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  DateTime _CheckTime;
	 	public DateTime CheckTime
		{
			get
			{
				return _CheckTime;
			}
			set
			{
				_CheckTime=value;
			}
		}

		#endregion				
	}
}
