 /*****************************************
Table  Name:MemCGScope
Create Time:2017/9/22 15:02:31
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemCGScope
	/// This entiy code is generated by codesmith. this entity is MemCGScope.
	/// </summary>
	[Serializable()]
	public class MemCGScopeEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 供应商经营范围记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 供应商Id
		/// <summary>
		private  int _CGMemId;
	 	public int CGMemId
		{
			get
			{
				return _CGMemId;
			}
			set
			{
				_CGMemId=value;
			}
		}
        private int _IsActive;
        public int IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                _IsActive = value;
            }
        }

        /// <summary>
        /// 品牌Id
        /// <summary>
        private int _BrandId;
	 	public int BrandId
		{
			get
			{
				return _BrandId;
			}
			set
			{
				_BrandId=value;
			}
		}

	    /// <summary>
		/// 品牌名称
		/// <summary>
		private  string _BrandName;
	 	public string BrandName
		{
			get
			{
				return _BrandName;
			}
			set
			{
				_BrandName=value;
			}
		}

	    /// <summary>
		/// 产品分类Id
		/// <summary>
		private  int _ClassId;
	 	public int ClassId
		{
			get
			{
				return _ClassId;
			}
			set
			{
				_ClassId=value;
			}
		}

	    /// <summary>
		/// 产品分类名称
		/// <summary>
		private  string _ClassName;
	 	public string ClassName
		{
			get
			{
				return _ClassName;
			}
			set
			{
				_ClassName=value;
			}
		}

	    /// <summary>
		/// 建立人
		/// <summary>
		private  int _CreateManId;
	 	public int CreateManId
		{
			get
			{
				return _CreateManId;
			}
			set
			{
				_CreateManId=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}
        /// <summary>
        /// 建立人
        /// <summary>
        private int _ScopeType;
        public int ScopeType
        {
            get
            {
                return _ScopeType;
            }
            set
            {
                _ScopeType = value;
            }
        }
        #endregion
    }
}
