 /*****************************************
Table  Name:MemFavorites
Create Time:2017/5/5 9:14:54
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemFavorites
	/// This entiy code is generated by codesmith. this entity is MemFavorites.
	/// </summary>
	[Serializable()]
	public class MemFavoritesEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 我的收藏表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 产品明细Id
		/// <summary>
		private  int _ProductDetailId;
	 	public int ProductDetailId
		{
			get
			{
				return _ProductDetailId;
			}
			set
			{
				_ProductDetailId=value;
			}
		}

	    /// <summary>
		/// 用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 生成时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}
        /// <summary>
        /// 生成时间
        /// <summary>
        private DateTime _UpdateTime;
        public DateTime UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                _UpdateTime = value;
            }
        }

        /// <summary>
        /// 是否有效，用户删除后变0
        /// <summary>
        private int _IsActive;
	 	public int IsActive
		{
			get
			{
				return _IsActive;
			}
			set
			{
				_IsActive=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _SystemId;
	 	public int SystemId
		{
			get
			{
				return _SystemId;
			}
			set
			{
				_SystemId=value;
			}
		}

		#endregion				
	}
}
