 /*****************************************
Table  Name:MemGiftLog
Create Time:2017/6/8 14:42:03
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemGiftLog
	/// This entiy code is generated by codesmith. this entity is MemGiftLog.
	/// </summary>
	[Serializable()]
	public class MemGiftLogEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 赠送的礼物日志表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 用户Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 备注说明
		/// <summary>
		private  string _Remark;
	 	public string Remark
		{
			get
			{
				return _Remark;
			}
			set
			{
				_Remark=value;
			}
		}

	    /// <summary>
		/// 赠送时间
		/// <summary>
		private  DateTime _CreateTme;
	 	public DateTime CreateTme
		{
			get
			{
				return _CreateTme;
			}
			set
			{
				_CreateTme=value;
			}
		}

	    /// <summary>
		/// 状态，扩展的时候用
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
		}

		#endregion				
	}
}
