 /*****************************************
Table  Name:MemLoginLog
Create Time:2016/8/1 13:49:38
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemLoginLog
	/// This entiy code is generated by codesmith. this entity is MemLoginLog.
	/// </summary>
	[Serializable()]
	public class MemLoginLogEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 用户编号
	 	public int MemId
		{
			get;
			set;
		}

		// Ip地址
	 	public string LoginIP
		{
			get;
			set;
		}

		// 登录客户端种类
	 	public int ClientType
		{
			get;
			set;
		}

		// 登录时间
	 	public DateTime LoginTime
		{
			get;
			set;
		}

		#endregion				
	}
}
