 /*****************************************
Table  Name:PostAddress
Create Time:2016/8/1 13:49:39
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>PostAddress
	/// This entiy code is generated by codesmith. this entity is PostAddress.
	/// </summary>
	[Serializable()]
	public class MemPostAddressEntity
    {
	    #region Public Properties	
		// 邮寄地址表
	 	public int Id
		{
			get;
			set;
		}

		// 关联客户Id
	 	public int MemId
		{
			get;
			set;
		}

		// 收件人
	 	public string AccepterName
		{
			get;
			set;
		}

		// 国家类别0国内1海外
	 	public int CtType
		{
			get;
			set;
		}

		// 国家编号
	 	public string CountryCode
		{
			get;
			set;
		}

		// 国家名称
	 	public string CountryName
		{
			get;
			set;
		}

		// 省
	 	public int ProvinceId
        {
			get;
			set;
		}

		// 市
	 	public int CityId
        {
			get;
			set;
		}
        // 省
        public string ProvinceName
        {
            get;
            set;
        }

        // 市
        public string CityName
        {
            get;
            set;
        }
        // 区县
        public string District
		{
			get;
			set;
		}

		// 具体地址
	 	public string Address
		{
			get;
			set;
		}

		// 邮编
	 	public string Email
		{
			get;
			set;
		}

		// 电话号码
	 	public string Telephone
		{
			get;
			set;
		}

		// 手机号码
	 	public string MobilePhone
		{
			get;
			set;
		}

		// 默认邮寄地址
	 	public int IsDefault
		{
			get;
			set;
		}

		// 邮寄地址排序
	 	public int Sort
		{
			get;
			set;
		}

		#endregion				
	}
}
