 /*****************************************
Table  Name:MemRoleAuth
Create Time:2016/8/1 13:49:39
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemRoleAuth
	/// This entiy code is generated by codesmith. this entity is MemRoleAuth.
	/// </summary>
	[Serializable()]
	public class MemRoleAuthEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 角色Id
	 	public int RoleId
		{
			get;
			set;
		}

		// 权限Id
	 	public int AuthId
		{
			get;
			set;
		}

		#endregion				
	}
}
