 /*****************************************
Table  Name:MemRole
Create Time:2016/8/1 13:49:39
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemRole
	/// This entiy code is generated by codesmith. this entity is MemRole.
	/// </summary>
	[Serializable()]
	public class MemRoleEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 网站用户角色编码，与枚举值对应
	 	public string RoleCode
		{
			get;
			set;
		}

		// 网站用户角色名称，显示给用户的
	 	public string RoleName
		{
			get;
			set;
		}

		// 
	 	public string Remark
		{
			get;
			set;
		}

		// 是否有效
	 	public int IsActive
		{
			get;
			set;
		}

		#endregion				
	}
}
