 /*****************************************
Table  Name:MemRoleRelate
Create Time:2016/8/1 17:46:21
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemRoleRelate
	/// This entiy code is generated by codesmith. this entity is MemRoleRelate.
	/// </summary>
	[Serializable()]
	public class MemRoleRelateEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 
	 	public int RoleId
		{
			get;
			set;
		}

		// 
	 	public int MemId
		{
			get;
			set;
		}

		#endregion				
	}
}
