 /*****************************************
Table  Name:MemRecommend
Create Time:2016/8/2 11:49:49
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemRecommend
	/// This entiy code is generated by codesmith. this entity is MemRecommend.
	/// </summary>
	[Serializable()]
	public class MemRecommendEntity
	{
	    #region Public Properties	
		// 用户推荐码生成表
	 	public int Id
		{
			get;
			set;
		}

		// 用户Id
	 	public int MemId
		{
			get;
			set;
		}

		// 推荐码
	 	public string RecommendCode
		{
			get;
			set;
		}

		// 是否有效
	 	public int IsActive
		{
			get;
			set;
		}

		// 生成时间
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		#endregion				
	}
}
