 /*****************************************
Table  Name:ShoppCar
Create Time:2016/9/12 14:59:08
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>ShoppCar
	/// This entiy code is generated by codesmith. this entity is ShoppCar.
	/// </summary>
	[Serializable()]
	public class MemShoppCarEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 
		/// <summary>
		private bool _Check;
	 	public bool Check
		{
			get
			{
				return _Check;
			}
			set
			{
                _Check = value;
			}
		}
        
	    /// <summary>
		/// 物品Id
		/// <summary> 
	 	public int ProductId
		{
            get;
            set;
		}
        /// <summary>
        /// 库存
        /// </summary>
        public int StockNum
        {
            get;
            set;
        }
        public int ProductDetailId
        {
            get;
            set;

        }
	    /// <summary>
		/// 产品标题
		/// <summary>
		private  string _ProductName;
	 	public string ProductName
        {
			get
			{
				return _ProductName;
			}
			set
			{
                _ProductName = value;
			}
		}
	    /// <summary>
		/// 单价
		/// <summary>
		private  decimal _Price;
	 	public decimal Price
		{
			get
			{
				return _Price;
			}
			set
			{
				_Price=value;
			}
		}

	    /// <summary>
		/// 数量
		/// <summary>
		private  int _Num;
	 	public int Num
		{
			get
			{
				return _Num;
			}
			set
			{
				_Num=value;
			}
		}
        /// <summary>
        /// 供应商
        /// <summary>
        private int _CGMemId;
        public int CGMemId
        {
            get
            {
                return _CGMemId;
            }
            set
            {
                _CGMemId = value;
            }
        }
        /// <summary>
        /// 供应商名称
        /// <summary>
        private string _CGMemNickName;
        public string CGMemNickName
        {
            get
            {
                return _CGMemNickName;
            }
            set
            {
                _CGMemNickName = value;
            }
        }
        /// <summary>
        /// 是否易店心负责
        /// <summary>
        private int _IsAhmTake;
        public int IsAhmTake
        {
            get
            {
                return _IsAhmTake;
            }
            set
            {
                _IsAhmTake = value;
            }
        }
        /// <summary>
        /// 总价
        /// <summary>
        private  decimal _TotalPrice;
	 	public decimal TotalPrice
		{
			get
			{
				return _TotalPrice;
			}
			set
			{
				_TotalPrice=value;
			}
		}
        /// <summary>
        ///  
        /// <summary>
        private string _Spec1;
        public string Spec1
        {
            get
            {
                return _Spec1;
            }
            set
            {
                _Spec1 = value;
            }
        }
        /// <summary>
        ///  
        /// <summary>
        private string _Spec2;
        public string Spec2
        {
            get
            {
                return _Spec2;
            }
            set
            {
                _Spec2 = value;
            }
        }
        private string _Spec3;
        public string Spec3
        {
            get
            {
                return _Spec3;
            }
            set
            {
                _Spec3= value;
            }
        }
        /// <summary>
        /// 图片路径
        /// <summary>
        private  string _PicUrl;
	 	public string PicUrl
		{
			get
			{
				return _PicUrl;
			}
			set
			{
				_PicUrl=value;
			}
		}
        /// <summary>
        /// 图片路径
        /// <summary> 
        public string PicUrlList
        {
            get
            {
                return string.IsNullOrEmpty(PicUrl) ? "" : PicUrl + "200_200." + PicSuffix;
            }

        }
        /// <summary>
        /// 图片路径
        /// <summary> 
        public string PicUrlSmall
        {
            get
            {
                return string.IsNullOrEmpty(PicUrl) ? "" : PicUrl + "60_60." + PicSuffix;
            }

        }
        /// <summary>
        ///  图片后缀
        /// <summary>
        private string _PicSuffix;
        public string PicSuffix
        {
            get
            {
                return _PicSuffix;
            }
            set
            {
                _PicSuffix = value;
            }
        }
        public int ProductType
        {
            get;
            set;
        }
        public DateTime UpdateTime
        {
            get;
            set;
        }

        #endregion
    }

    public class ShoppCookie
    {
        /// <summary>
        /// 是否选中
        /// </summary>
        public int C 
        {
            get;
            set;
        }
        public int ProDId
        {
            get;
            set;
        }
        /// <summary>
        /// 数量
        /// </summary>
        public int Num
        {
            get;
            set;
        }
        /// <summary>
        /// 排序
        /// </summary>
        public int S
        {
            get;
            set;
        }
    }
}
