 /*****************************************
Table  Name:MemWareHouse
Create Time:2017/8/1 22:17:13
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemWareHouse
	/// This entiy code is generated by codesmith. this entity is MemWareHouse.
	/// </summary>
	[Serializable()]
	public class MemWareHouseEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 商家仓库记录表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 商家Id
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 仓库名称
		/// <summary>
		private  string _Name;
	 	public string Name
		{
			get
			{
				return _Name;
			}
			set
			{
				_Name=value;
			}
		}

	    /// <summary>
		/// 仓库地址
		/// <summary>
		private  string _Address;
	 	public string Address
		{
			get
			{
				return _Address;
			}
			set
			{
				_Address=value;
			}
		}

	    /// <summary>
		/// 联系人姓名
		/// <summary>
		private  string _ContractMemName;
	 	public string ContractMemName
		{
			get
			{
				return _ContractMemName;
			}
			set
			{
				_ContractMemName=value;
			}
		}

	    /// <summary>
		/// 联系人电话
		/// <summary>
		private  string _ContractMobile;
	 	public string ContractMobile
		{
			get
			{
				return _ContractMobile;
			}
			set
			{
				_ContractMobile=value;
			}
		}

	    /// <summary>
		/// 经度
		/// <summary>
		private  decimal _PositionLat;
	 	public decimal PositionLat
		{
			get
			{
				return _PositionLat;
			}
			set
			{
				_PositionLat=value;
			}
		}

	    /// <summary>
		/// 纬度
		/// <summary>
		private  decimal _PositionLng;
	 	public decimal PositionLng
		{
			get
			{
				return _PositionLng;
			}
			set
			{
				_PositionLng=value;
			}
		}

	    /// <summary>
		/// 建立时间
		/// <summary>
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		#endregion				
	}
}
