 /*****************************************
Table  Name:MemWeChatMsg
Create Time:2017/8/16 17:20:48
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>MemWeChatMsg
	/// This entiy code is generated by codesmith. this entity is MemWeChatMsg.
	/// </summary>
	[Serializable()]
	public class MemWeChatMsgEntity
	{
	    #region Public Properties	
	    /// <summary>
		/// 客户微信基本信息数据
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _UnionId;
	 	public string UnionId
		{
			get
			{
				return _UnionId;
			}
			set
			{
				_UnionId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _OpenId;
	 	public string OpenId
		{
			get
			{
				return _OpenId;
			}
			set
			{
				_OpenId=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _NickName;
	 	public string NickName
		{
			get
			{
				return _NickName;
			}
			set
			{
				_NickName=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  int _Sex;
	 	public int Sex
		{
			get
			{
				return _Sex;
			}
			set
			{
				_Sex=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Language;
	 	public string Language
		{
			get
			{
				return _Language;
			}
			set
			{
				_Language=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _City;
	 	public string City
		{
			get
			{
				return _City;
			}
			set
			{
				_City=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Province;
	 	public string Province
		{
			get
			{
				return _Province;
			}
			set
			{
				_Province=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _Country;
	 	public string Country
		{
			get
			{
				return _Country;
			}
			set
			{
				_Country=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _HeadimgUrl;
	 	public string HeadimgUrl
		{
			get
			{
				return _HeadimgUrl;
			}
			set
			{
				_HeadimgUrl=value;
			}
		}

	    /// <summary>
		/// 
		/// <summary>
		private  string _AppId;
	 	public string AppId
		{
			get
			{
				return _AppId;
			}
			set
			{
				_AppId=value;
			}
		}

	    /// <summary>
		/// 1,获取简易信息，2获取全部信息
		/// <summary>
		private  int _Status;
	 	public int Status
		{
			get
			{
				return _Status;
			}
			set
			{
				_Status=value;
			}
         
    }
        /// <summary>
        /// 
        /// <summary>
        private string _Access_Token;
        public string Access_Token
        {
            get
            {
                return _Access_Token;
            }
            set
            {
                _Access_Token = value;
            }
        }
        /// <summary>
        /// 
        /// <summary>
        private string _Refresh_Token;
        public string Refresh_Token
        {
            get
            {
                return _Refresh_Token;
            }
            set
            {
                _Refresh_Token = value;
            }
        }
        #endregion
    }
}
