 /*****************************************
Table  Name:WZ_ShopCart
Create Time:2016/9/18 12:34:41
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>WZShopCart
	/// This entiy code is generated by codesmith. this entity is WZShopCart.
	/// </summary>
	[Serializable()]
	public class MemWZShopCartEntity
    {
	    #region Public Properties	
	    /// <summary>
		/// 购物车表
		/// <summary>
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

	    /// <summary>
		/// 用户ID
		/// <summary>
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

	    /// <summary>
		/// 购买日期
		/// <summary>
		private  DateTime _BuyDate;
	 	public DateTime BuyDate
		{
			get
			{
				return _BuyDate;
			}
			set
			{
				_BuyDate=value;
			}
		}

	    /// <summary>
		/// 结束日期
		/// <summary>
		private  DateTime _EndDate;
	 	public DateTime EndDate
		{
			get
			{
				return _EndDate;
			}
			set
			{
				_EndDate=value;
			}
		}

	    /// <summary>
		/// 生成日期
		/// <summary>
		private  DateTime _AddDate;
	 	public DateTime AddDate
		{
			get
			{
				return _AddDate;
			}
			set
			{
				_AddDate=value;
			}
		}

	    /// <summary>
		/// cookie值
		/// <summary>
		private  string _CookieValue;
	 	public string CookieValue
		{
			get
			{
				return _CookieValue;
			}
			set
			{
				_CookieValue=value;
			}
		}
        /// <summary>
        /// cookie值
        /// <summary>
        private string _CookieValueXuQiu;
        public string CookieValueXuQiu
        {
            get
            {
                return _CookieValueXuQiu;
            }
            set
            {
                _CookieValueXuQiu = value;
            }
        }
        
        /// <summary>
        /// key
        /// <summary>
        private  string _CookieId;
	 	public string CookieId
		{
			get
			{
				return _CookieId;
			}
			set
			{
				_CookieId=value;
			}
		}

		#endregion				
	}
}
