 /*****************************************
Table  Name:SendEmailSms
Create Time:2016/8/2 14:16:00
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SendEmailSms
	/// This entiy code is generated by codesmith. this entity is SendEmailSms.
	/// </summary>
	[Serializable()]
	public class SendEmailSmsEntity
	{
	    #region Public Properties	
		// 邮件发送表（计划任务跑）
	 	public int Id
		{
			get;
			set;
		}

		// 标题
	 	public string Title
		{
			get;
			set;
		}

		// 发送到对象
	 	public string SendTo
		{
			get;
			set;
		}

		// 建立时间
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		// 来源
	 	public string CreateBy
		{
			get;
			set;
		}

		// 状态
	 	public int Status
		{
			get;
			set;
		}

		// 用户编码
	 	public string MemCode
		{
			get;
			set;
		}

		// 邮件内容
	 	public string EmailContent
		{
			get;
			set;
		}

		// 优先级
	 	public int PriorIndex
		{
			get;
			set;
		}

		#endregion				
	}
}
