 /*****************************************
Table  Name:Suggest
Create Time:2016/8/1 13:49:39
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>Suggest
	/// This entiy code is generated by codesmith. this entity is Suggest.
	/// </summary>
	[Serializable()]
	public class SuggestEntity
	{
	    #region Public Properties	
		// 用户建议记录表
	 	public int Id
		{
			get;
			set;
		}

		// 建议类别(1注册登录，2密码修改，3在线充值，4信用评价，5客户留言，6购物车，7支付问题，8物流问题
	 	public int SuggestType
		{
			get;
			set;
		}

		// 标题
	 	public string Title
		{
			get;
			set;
		}

		// 手机号码
	 	public string MobilePhone
		{
			get;
			set;
		}

		// 联系人姓名
	 	public string ManName
		{
			get;
			set;
		}

		// 邮箱
	 	public string Email
		{
			get;
			set;
		}

		// 建议内容
	 	public string SuggestContent
		{
			get;
			set;
		}

		// IP地址
	 	public string IpAddress
		{
			get;
			set;
		}

		// 客户端种类（1PC，2安卓，3IOS)
	 	public int ClientType
		{
			get;
			set;
		}

		// 状态，1待处理，2已处理，3无需处理
	 	public int Status
		{
			get;
			set;
		}

		// 提出时间
	 	public DateTime CreateTime
		{
			get;
			set;
		}

		#endregion				
	}
}
