 /*****************************************
Table  Name:SuggestDealLog
Create Time:2016/8/1 21:32:30
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SuggestDealLog
	/// This entiy code is generated by codesmith. this entity is SuggestDealLog.
	/// </summary>
	[Serializable()]
	public class SuggestDealLogEntity
	{
	    #region Public Properties	
		// 
	 	public int Id
		{
			get;
			set;
		}

		// 建议ID
	 	public int SuggestId
		{
			get;
			set;
		}

		// 处理人Id
	 	public int DealManId
		{
			get;
			set;
		}

		// 处理结果
	 	public string DealContent
		{
			get;
			set;
		}

		// 处理时间
	 	public DateTime DealTime
		{
			get;
			set;
		}

		#endregion				
	}
}
