 /*****************************************
Table  Name:SysMsg
Create Time:2016/8/8 10:21:35
Creator    :jc001
******************************************/
using System;
using System.Data;
using System.Text; 
 
//?DataEntityattrbute
namespace SuperMarket.Model
{ 	
	/// <summary>SysMsg
	/// This entiy code is generated by codesmith. this entity is SysMsg.
	/// </summary>
	[Serializable()]
	public class SysMsgEntity
	{
	    #region Public Properties	
		// 系统信息表
		private  int _Id;
	 	public int Id
		{
			get
			{
				return _Id;
			}
			set
			{
				_Id=value;
			}
		}

		// 用户ID
		private  int _MemId;
	 	public int MemId
		{
			get
			{
				return _MemId;
			}
			set
			{
				_MemId=value;
			}
		}

		// 信息内容
		private  string _MsgContent;
	 	public string MsgContent
		{
			get
			{
				return _MsgContent;
			}
			set
			{
				_MsgContent=value;
			}
		}

		// 是否阅读
		private  int _HasRead;
	 	public int HasRead
		{
			get
			{
				return _HasRead;
			}
			set
			{
				_HasRead=value;
			}
		}

		// 建立时间
		private  DateTime _CreateTime;
	 	public DateTime CreateTime
		{
			get
			{
				return _CreateTime;
			}
			set
			{
				_CreateTime=value;
			}
		}

		// 阅读时间
		private  DateTime _ReadTime;
	 	public DateTime ReadTime
		{
			get
			{
				return _ReadTime;
			}
			set
			{
				_ReadTime=value;
			}
		}

		#endregion				
	}
}
